// @generated by gen-shims.py — do not edit by hand
package android.app.job;

public class JobInfo {
    public android.os.PersistableBundle getExtras() { return null; }
    public int getId() { return 0; }
    public long getMinFlexMillis() { return 0; }
    public android.content.ComponentName getService() { return null; }

    public static class Builder {
        public android.app.job.JobInfo.Builder addTriggerContentUri(android.app.job.JobInfo.TriggerContentUri p0) { return null; }
        public android.app.job.JobInfo build() { return null; }
        public android.app.job.JobInfo.Builder setBackoffCriteria(long p0, int p1) { return null; }
        public android.app.job.JobInfo.Builder setExpedited(boolean p0) { return null; }
        public android.app.job.JobInfo.Builder setExtras(android.os.PersistableBundle p0) { return null; }
        public android.app.job.JobInfo.Builder setImportantWhileForeground(boolean p0) { return null; }
        public android.app.job.JobInfo.Builder setMinimumLatency(long p0) { return null; }
        public android.app.job.JobInfo.Builder setOverrideDeadline(long p0) { return null; }
        public android.app.job.JobInfo.Builder setPeriodic(long p0) { return null; }
        public android.app.job.JobInfo.Builder setPeriodic(long p0, long p1) { return null; }
        public android.app.job.JobInfo.Builder setPersisted(boolean p0) { return null; }
        public android.app.job.JobInfo.Builder setRequiredNetwork(android.net.NetworkRequest p0) { return null; }
        public android.app.job.JobInfo.Builder setRequiredNetworkType(int p0) { return null; }
        public android.app.job.JobInfo.Builder setRequiresBatteryNotLow(boolean p0) { return null; }
        public android.app.job.JobInfo.Builder setRequiresCharging(boolean p0) { return null; }
        public android.app.job.JobInfo.Builder setRequiresDeviceIdle(boolean p0) { return null; }
        public android.app.job.JobInfo.Builder setRequiresStorageNotLow(boolean p0) { return null; }
        public android.app.job.JobInfo.Builder setTraceTag(java.lang.String p0) { return null; }
        public android.app.job.JobInfo.Builder setTriggerContentMaxDelay(long p0) { return null; }
        public android.app.job.JobInfo.Builder setTriggerContentUpdateDelay(long p0) { return null; }
    }

    public static class TriggerContentUri {
    }
}
