// @generated by gen-shims.py — do not edit by hand
package android.app.job;

public class JobParameters {
    public void completeWork(android.app.job.JobWorkItem p0) {}
    public android.app.job.JobWorkItem dequeueWork() { return null; }
    public android.os.PersistableBundle getExtras() { return null; }
    public android.net.Network getNetwork() { return null; }
    public int getStopReason() { return 0; }
    public java.lang.String[] getTriggeredContentAuthorities() { return null; }
    public android.net.Uri[] getTriggeredContentUris() { return null; }
}
