// @generated by gen-shims.py — do not edit by hand
package android.app.job;

public class JobScheduler {
    public void cancel(int p0) {}
    public void cancelAll() {}
    public int enqueue(android.app.job.JobInfo p0, android.app.job.JobWorkItem p1) { return 0; }
    public android.app.job.JobScheduler forNamespace(java.lang.String p0) { return null; }
    public java.util.List getAllPendingJobs() { return null; }
    public android.app.job.JobInfo getPendingJob(int p0) { return null; }
    public int schedule(android.app.job.JobInfo p0) { return 0; }
}
