// @generated by gen-shims.py — do not edit by hand
package android.app.job;

public class JobService {
    public android.app.Application getApplication() { return null; }
    public android.content.Context getApplicationContext() { return null; }
    public void jobFinished(android.app.job.JobParameters p0, boolean p1) {}
    public void onCreate() {}
    public void onDestroy() {}
}
