// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class AbsListView {
    public boolean canScrollList(int p0) { return false; }
    public int getCheckedItemPosition() { return 0; }
    public android.util.SparseBooleanArray getCheckedItemPositions() { return null; }
    public android.view.View getChildAt(int p0) { return null; }
    public int getChildCount() { return 0; }
    public int getChoiceMode() { return 0; }
    public int getFirstVisiblePosition() { return 0; }
    public int getListPaddingBottom() { return 0; }
    public int getListPaddingTop() { return 0; }
    public int getPaddingTop() { return 0; }
    public android.graphics.drawable.Drawable getSelector() { return null; }
    public boolean isItemChecked(int p0) { return false; }
    public boolean isSelectedChildViewEnabled() { return false; }
    public void layoutChildren() {}
    public int pointToPosition(int p0, int p1) { return 0; }
    public void scrollListBy(int p0) {}
    public void setAdapter(android.widget.ListAdapter p0) {}
    public void setCacheColorHint(int p0) {}
    public void setChoiceMode(int p0) {}
    public void setDrawSelectorOnTop(boolean p0) {}
    public void setItemChecked(int p0, boolean p1) {}
    public void setOnScrollListener(android.widget.AbsListView.OnScrollListener p0) {}
    public void setSelectedChildViewEnabled(boolean p0) {}
    public void setSelectionFromTop(int p0, int p1) {}
    public void setSelector(android.graphics.drawable.Drawable p0) {}
    public void setTextFilterEnabled(boolean p0) {}
    public void smoothScrollToPositionFromTop(int p0, int p1, int p2) {}

    public static class LayoutParams {
    }

    public interface OnScrollListener {
    }
}
