// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class AbsSeekBar {
    public int getKeyProgressIncrement() { return 0; }
    public android.graphics.drawable.Drawable getThumb() { return null; }
    public int getThumbOffset() { return 0; }
    public void setKeyProgressIncrement(int p0) {}
    public void setThumb(android.graphics.drawable.Drawable p0) {}
}
