// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class AbsSpinner {
    public android.widget.SpinnerAdapter getAdapter() { return null; }
    public android.content.Context getContext() { return null; }
    public void setAdapter(android.widget.SpinnerAdapter p0) {}
    public void setSelection(int p0, boolean p1) {}
}
