// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class AdapterView {
    public android.widget.Adapter getAdapter() { return null; }
    public int getCount() { return 0; }
    public int getFirstVisiblePosition() { return 0; }
    public java.lang.Object getItemAtPosition(int p0) { return null; }
    public long getItemIdAtPosition(int p0) { return 0; }
    public int getLastVisiblePosition() { return 0; }
    public android.widget.AdapterView.OnItemClickListener getOnItemClickListener() { return null; }
    public int getPositionForView(android.view.View p0) { return 0; }
    public java.lang.Object getSelectedItem() { return null; }
    public long getSelectedItemId() { return 0; }
    public int getSelectedItemPosition() { return 0; }
    public android.view.View getSelectedView() { return null; }
    public boolean performItemClick(android.view.View p0, int p1, long p2) { return false; }
    public void setAdapter(android.widget.Adapter p0) {}
    public void setEmptyView(android.view.View p0) {}
    public void setOnItemClickListener(android.widget.AdapterView.OnItemClickListener p0) {}
    public void setOnItemSelectedListener(android.widget.AdapterView.OnItemSelectedListener p0) {}
    public void setSelection(int p0) {}

    public static class AdapterContextMenuInfo {
    }

    public interface OnItemClickListener {
        void onItemClick(android.widget.AdapterView p0, android.view.View p1, int p2, long p3);
    }

    public interface OnItemLongClickListener {
    }

    public interface OnItemSelectedListener {
    }
}
