// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ArrayAdapter {
    public void add(java.lang.Object p0) {}
    public void addAll(java.util.Collection p0) {}
    public void clear() {}
    public android.widget.ArrayAdapter createFromResource(android.content.Context p0, int p1, int p2) { return null; }
    public android.content.Context getContext() { return null; }
    public int getCount() { return 0; }
    public java.lang.Object getItem(int p0) { return null; }
    public int getPosition(java.lang.Object p0) { return 0; }
    public android.view.View getView(int p0, android.view.View p1, android.view.ViewGroup p2) { return null; }
    public void notifyDataSetChanged() {}
    public void notifyDataSetInvalidated() {}
    public void remove(java.lang.Object p0) {}
    public void setDropDownViewResource(int p0) {}
    public void setNotifyOnChange(boolean p0) {}
    public void sort(java.util.Comparator p0) {}
}
