// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class BaseAdapter {
    public boolean areAllItemsEnabled() { return false; }
    public int getItemViewType(int p0) { return 0; }
    public boolean isEnabled(int p0) { return false; }
    public void notifyDataSetChanged() {}
    public void notifyDataSetInvalidated() {}
    public void registerDataSetObserver(android.database.DataSetObserver p0) {}
}
