// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class CalendarView {
    public long getDate() { return 0; }
    public void setDate(long p0) {}
    public void setOnDateChangeListener(android.widget.CalendarView.OnDateChangeListener p0) {}

    public interface OnDateChangeListener {
        void onSelectedDayChange(android.widget.CalendarView p0, int p1, int p2, int p3);
    }
}
