// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class CheckedTextView {
    public void drawableStateChanged() {}
    public android.graphics.drawable.Drawable getCheckMarkDrawable() { return null; }
    public android.content.res.ColorStateList getCheckMarkTintList() { return null; }
    public android.graphics.PorterDuff.Mode getCheckMarkTintMode() { return null; }
    public android.content.Context getContext() { return null; }
    public android.view.ActionMode.Callback getCustomSelectionActionModeCallback() { return null; }
    public int[] getDrawableState() { return null; }
    public android.graphics.Typeface getTypeface() { return null; }
    public boolean isChecked() { return false; }
    public android.view.inputmethod.InputConnection onCreateInputConnection(android.view.inputmethod.EditorInfo p0) { return null; }
    public void setAllCaps(boolean p0) {}
    public void setBackgroundDrawable(android.graphics.drawable.Drawable p0) {}
    public void setBackgroundResource(int p0) {}
    public void setCheckMarkDrawable(android.graphics.drawable.Drawable p0) {}
    public void setCheckMarkTintList(android.content.res.ColorStateList p0) {}
    public void setCheckMarkTintMode(android.graphics.PorterDuff.Mode p0) {}
    public void setChecked(boolean p0) {}
    public void setCompoundDrawablePadding(int p0) {}
    public void setCompoundDrawables(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1, android.graphics.drawable.Drawable p2, android.graphics.drawable.Drawable p3) {}
    public void setCompoundDrawablesRelative(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1, android.graphics.drawable.Drawable p2, android.graphics.drawable.Drawable p3) {}
    public void setCustomSelectionActionModeCallback(android.view.ActionMode.Callback p0) {}
    public void setDuplicateParentStateEnabled(boolean p0) {}
    public void setMaxLines(int p0) {}
    public void setOnClickListener(android.view.View.OnClickListener p0) {}
    public void setText(java.lang.CharSequence p0) {}
    public void setTextAppearance(android.content.Context p0, int p1) {}
    public void setTextColor(android.content.res.ColorStateList p0) {}
    public void setTypeface(android.graphics.Typeface p0, int p1) {}
    public void setVisibility(int p0) {}
}
