// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class DatePicker {
    public int getDayOfMonth() { return 0; }
    public int getMonth() { return 0; }
    public int getYear() { return 0; }
    public void init(int p0, int p1, int p2, android.widget.DatePicker.OnDateChangedListener p3) {}

    public interface OnDateChangedListener {
        void onDateChanged(android.widget.DatePicker p0, int p1, int p2, int p3);
    }
}
