// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class EdgeEffect {
    public boolean draw(android.graphics.Canvas p0) { return false; }
    public void finish() {}
    public float getDistance() { return 0f; }
    public boolean isFinished() { return false; }
    public void onAbsorb(int p0) {}
    public void onPull(float p0) {}
    public void onPull(float p0, float p1) {}
    public float onPullDistance(float p0, float p1) { return 0f; }
    public void onRelease() {}
    public void setColor(int p0) {}
    public void setSize(int p0, int p1) {}
}
