// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ExpandableListView {
    public void setAdapter(android.widget.ExpandableListAdapter p0) {}
    public void setChildDivider(android.graphics.drawable.Drawable p0) {}
    public void setIndicatorBounds(int p0, int p1) {}
    public void setIndicatorBoundsRelative(int p0, int p1) {}
}
