// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class Filter {
    public java.lang.CharSequence convertResultToString(java.lang.Object p0) { return null; }
    public void filter(java.lang.CharSequence p0, android.widget.Filter.FilterListener p1) {}
    public void filter(java.lang.CharSequence p0) {}

    public interface FilterListener {
    }

    public static class FilterResults {
    }
}
