// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class GridLayout {
    public void addView(android.view.View p0) {}
    public void draw(android.graphics.Canvas p0) {}
    public int getChildCount() { return 0; }
    public boolean isOpaque() { return false; }
    public void setColumnCount(int p0) {}

    public static class LayoutParams {
    }
}
