// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class GridView {
    public android.view.View findViewById(int p0) { return null; }
    public android.widget.ListAdapter getAdapter() { return null; }
    public android.view.View getChildAt(int p0) { return null; }
    public int getChildCount() { return 0; }
    public android.content.Context getContext() { return null; }
    public int getNumColumns() { return 0; }
    public int getSelectedItemPosition() { return 0; }
    public int getWidth() { return 0; }
    public void onAttachedToWindow() {}
    public void onDraw(android.graphics.Canvas p0) {}
    public void onFocusChanged(boolean p0, int p1, android.graphics.Rect p2) {}
    public boolean onKeyDown(int p0, android.view.KeyEvent p1) { return false; }
    public void onMeasure(int p0, int p1) {}
    public void setAdapter(android.widget.ListAdapter p0) {}
    public void setEnabled(boolean p0) {}
    public void setNextFocusLeftId(int p0) {}
    public void setNextFocusRightId(int p0) {}
    public void setNumColumns(int p0) {}
    public void setOnItemClickListener(android.widget.AdapterView.OnItemClickListener p0) {}
    public void setSelection(int p0) {}
}
