// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class HeaderViewListAdapter {
    public int getHeadersCount() { return 0; }
    public android.widget.ListAdapter getWrappedAdapter() { return null; }
}
