// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class LinearLayout {
    public void addFocusables(java.util.ArrayList p0, int p1, int p2) {}
    public void addOnLayoutChangeListener(android.view.View.OnLayoutChangeListener p0) {}
    public void addView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public void addView(android.view.View p0) {}
    public void addView(android.view.View p0, int p1, android.view.ViewGroup.LayoutParams p2) {}
    public android.view.ViewPropertyAnimator animate() { return null; }
    public void bringChildToFront(android.view.View p0) {}
    public void bringToFront() {}
    public void dispatchDraw(android.graphics.Canvas p0) {}
    public boolean dispatchHoverEvent(android.view.MotionEvent p0) { return false; }
    public boolean dispatchKeyEvent(android.view.KeyEvent p0) { return false; }
    public void dispatchProvideAutofillStructure(android.view.ViewStructure p0, int p1) {}
    public void dispatchRestoreInstanceState(android.util.SparseArray p0) {}
    public boolean dispatchTouchEvent(android.view.MotionEvent p0) { return false; }
    public boolean dispatchTrackballEvent(android.view.MotionEvent p0) { return false; }
    public void draw(android.graphics.Canvas p0) {}
    public void drawableStateChanged() {}
    public android.view.View findViewById(int p0) { return null; }
    public boolean fitSystemWindows(android.graphics.Rect p0) { return false; }
    public android.view.View focusSearch(android.view.View p0, int p1) { return null; }
    public void focusableViewAvailable(android.view.View p0) {}
    public android.view.accessibility.AccessibilityNodeProvider getAccessibilityNodeProvider() { return null; }
    public android.view.autofill.AutofillId getAutofillId() { return null; }
    public android.graphics.drawable.Drawable getBackground() { return null; }
    public int getBaseline() { return 0; }
    public int getBottom() { return 0; }
    public android.view.View getChildAt(int p0) { return null; }
    public int getChildCount() { return 0; }
    public java.lang.CharSequence getContentDescription() { return null; }
    public android.content.Context getContext() { return null; }
    public int[] getDrawableState() { return null; }
    public android.view.View getFocusedChild() { return null; }
    public void getFocusedRect(android.graphics.Rect p0) {}
    public android.graphics.drawable.Drawable getForeground() { return null; }
    public boolean getGlobalVisibleRect(android.graphics.Rect p0, android.graphics.Point p1) { return false; }
    public int getHeight() { return 0; }
    public android.view.ViewGroup.LayoutParams getLayoutParams() { return null; }
    public int getLeft() { return 0; }
    public int getMeasuredHeight() { return 0; }
    public int getMeasuredWidth() { return 0; }
    public int getMeasuredWidthAndState() { return 0; }
    public int getMinimumHeight() { return 0; }
    public int getOrientation() { return 0; }
    public int getPaddingBottom() { return 0; }
    public int getPaddingLeft() { return 0; }
    public int getPaddingRight() { return 0; }
    public int getPaddingTop() { return 0; }
    public android.view.ViewParent getParent() { return null; }
    public android.content.res.Resources getResources() { return null; }
    public int getRight() { return 0; }
    public int getTop() { return 0; }
    public int getVisibility() { return 0; }
    public int getWidth() { return 0; }
    public int indexOfChild(android.view.View p0) { return 0; }
    public void invalidate() {}
    public void invalidateDrawable(android.graphics.drawable.Drawable p0) {}
    public boolean isEnabled() { return false; }
    public boolean isFocused() { return false; }
    public boolean isHovered() { return false; }
    public boolean isOpaque() { return false; }
    public boolean isSelected() { return false; }
    public void jumpDrawablesToCurrentState() {}
    public void measure(int p0, int p1) {}
    public int[] mergeDrawableStates(int[] p0, int[] p1) { return null; }
    public void onAttachedToWindow() {}
    public void onConfigurationChanged(android.content.res.Configuration p0) {}
    public void onCreateContextMenu(android.view.ContextMenu p0) {}
    public int[] onCreateDrawableState(int p0) { return null; }
    public void onDetachedFromWindow() {}
    public void onDraw(android.graphics.Canvas p0) {}
    public void onFinishInflate() {}
    public void onInitializeAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0) {}
    public void onInitializeAccessibilityNodeInfo(android.view.accessibility.AccessibilityNodeInfo p0) {}
    public void onLayout(boolean p0, int p1, int p2, int p3, int p4) {}
    public void onMeasure(int p0, int p1) {}
    public void onProvideAutofillStructure(android.view.ViewStructure p0, int p1) {}
    public void onProvideAutofillVirtualStructure(android.view.ViewStructure p0, int p1) {}
    public boolean onRequestFocusInDescendants(int p0, android.graphics.Rect p1) { return false; }
    public void onRestoreInstanceState(android.os.Parcelable p0) {}
    public void onRtlPropertiesChanged(int p0) {}
    public android.os.Parcelable onSaveInstanceState() { return null; }
    public void onSizeChanged(int p0, int p1, int p2, int p3) {}
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public void onViewRemoved(android.view.View p0) {}
    public boolean performClick() { return false; }
    public boolean performLongClick() { return false; }
    public void playSoundEffect(int p0) {}
    public void refreshDrawableState() {}
    public void removeAllViews() {}
    public void removeView(android.view.View p0) {}
    public void removeViewAt(int p0) {}
    public void requestChildFocus(android.view.View p0, android.view.View p1) {}
    public void requestLayout() {}
    public boolean requestRectangleOnScreen(android.graphics.Rect p0, boolean p1) { return false; }
    public void restoreHierarchyState(android.util.SparseArray p0) {}
    public void saveAttributeDataForStyleable(android.content.Context p0, int[] p1, android.util.AttributeSet p2, android.content.res.TypedArray p3, int p4, int p5) {}
    public void saveHierarchyState(android.util.SparseArray p0) {}
    public void sendAccessibilityEvent(int p0) {}
    public void setAccessibilityDelegate(android.view.View.AccessibilityDelegate p0) {}
    public void setActivated(boolean p0) {}
    public void setAddStatesFromChildren(boolean p0) {}
    public void setBackground(android.graphics.drawable.Drawable p0) {}
    public void setBackgroundColor(int p0) {}
    public void setBackgroundDrawable(android.graphics.drawable.Drawable p0) {}
    public void setBackgroundResource(int p0) {}
    public void setChildrenDrawingOrderEnabled(boolean p0) {}
    public void setClickable(boolean p0) {}
    public void setClipChildren(boolean p0) {}
    public void setClipToPadding(boolean p0) {}
    public void setContentDescription(java.lang.CharSequence p0) {}
    public void setElevation(float p0) {}
    public void setEnabled(boolean p0) {}
    public void setFocusable(boolean p0) {}
    public void setFocusableInTouchMode(boolean p0) {}
    public void setGravity(int p0) {}
    public void setId(int p0) {}
    public void setImportantForAccessibility(int p0) {}
    public void setImportantForAutofill(int p0) {}
    public void setKeyboardNavigationCluster(boolean p0) {}
    public void setLayoutParams(android.view.ViewGroup.LayoutParams p0) {}
    public void setMeasuredDimension(int p0, int p1) {}
    public void setMinimumHeight(int p0) {}
    public void setMinimumWidth(int p0) {}
    public void setNextFocusLeftId(int p0) {}
    public void setNextFocusRightId(int p0) {}
    public void setOnClickListener(android.view.View.OnClickListener p0) {}
    public void setOnLongClickListener(android.view.View.OnLongClickListener p0) {}
    public void setOnTouchListener(android.view.View.OnTouchListener p0) {}
    public void setOrientation(int p0) {}
    public void setPadding(int p0, int p1, int p2, int p3) {}
    public void setPaddingRelative(int p0, int p1, int p2, int p3) {}
    public void setPressed(boolean p0) {}
    public void setSelected(boolean p0) {}
    public void setTag(java.lang.Object p0) {}
    public void setTouchscreenBlocksFocus(boolean p0) {}
    public void setVisibility(int p0) {}
    public void setWeightSum(float p0) {}
    public void setWillNotDraw(boolean p0) {}
    public boolean verifyDrawable(android.graphics.drawable.Drawable p0) { return false; }
    public boolean willNotDraw() { return false; }

    public static class LayoutParams {
        public int getMarginStart() { return 0; }
        public void setMarginEnd(int p0) {}
        public void setMarginStart(int p0) {}
        public void setMargins(int p0, int p1, int p2, int p3) {}
    }
}
