// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ListPopupWindow {
    public android.view.View.OnTouchListener createDragToOpenListener(android.view.View p0) { return null; }
    public void dismiss() {}
    public android.widget.ListView getListView() { return null; }
    public boolean isShowing() { return false; }
    public void setAdapter(android.widget.ListAdapter p0) {}
    public void setAnchorView(android.view.View p0) {}
    public void setWidth(int p0) {}
    public void show() {}
}
