// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class Magnifier {
    public void dismiss() {}
    public int getHeight() { return 0; }
    public int getWidth() { return 0; }
    public void setZoom(float p0) {}
    public void show(float p0, float p1) {}
    public void show(float p0, float p1, float p2, float p3) {}
    public void update() {}

    public static class Builder {
        public android.widget.Magnifier build() { return null; }
        public android.widget.Magnifier.Builder setClippingEnabled(boolean p0) { return null; }
        public android.widget.Magnifier.Builder setCornerRadius(float p0) { return null; }
        public android.widget.Magnifier.Builder setElevation(float p0) { return null; }
        public android.widget.Magnifier.Builder setInitialZoom(float p0) { return null; }
        public android.widget.Magnifier.Builder setSize(int p0, int p1) { return null; }
    }
}
