// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class MultiAutoCompleteTextView {
    public void drawableStateChanged() {}
    public android.content.Context getContext() { return null; }
    public int getInputType() { return 0; }
    public boolean isClickable() { return false; }
    public boolean isFocusable() { return false; }
    public boolean isLongClickable() { return false; }
    public android.view.inputmethod.InputConnection onCreateInputConnection(android.view.inputmethod.EditorInfo p0) { return null; }
    public void setBackgroundDrawable(android.graphics.drawable.Drawable p0) {}
    public void setBackgroundResource(int p0) {}
    public void setClickable(boolean p0) {}
    public void setCompoundDrawables(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1, android.graphics.drawable.Drawable p2, android.graphics.drawable.Drawable p3) {}
    public void setCompoundDrawablesRelative(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1, android.graphics.drawable.Drawable p2, android.graphics.drawable.Drawable p3) {}
    public void setDropDownBackgroundDrawable(android.graphics.drawable.Drawable p0) {}
    public void setFocusable(boolean p0) {}
    public void setKeyListener(android.text.method.KeyListener p0) {}
    public void setLongClickable(boolean p0) {}
    public void setRawInputType(int p0) {}
    public void setTextAppearance(android.content.Context p0, int p1) {}
}
