// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class NumberPicker {
    public void clearFocus() {}
    public int getValue() { return 0; }
    public void setMaxValue(int p0) {}
    public void setMinValue(int p0) {}
    public void setOnValueChangedListener(android.widget.NumberPicker.OnValueChangeListener p0) {}
    public void setValue(int p0) {}

    public interface OnValueChangeListener {
        void onValueChange(android.widget.NumberPicker p0, int p1, int p2);
    }
}
