// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class OverScroller {
    public void abortAnimation() {}
    public boolean computeScrollOffset() { return false; }
    public void fling(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {}
    public void fling(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9) {}
    public void forceFinished(boolean p0) {}
    public float getCurrVelocity() { return 0f; }
    public int getCurrX() { return 0; }
    public int getCurrY() { return 0; }
    public int getFinalX() { return 0; }
    public int getFinalY() { return 0; }
    public boolean isFinished() { return false; }
    public boolean isOverScrolled() { return false; }
    public void notifyHorizontalEdgeReached(int p0, int p1, int p2) {}
    public void notifyVerticalEdgeReached(int p0, int p1, int p2) {}
    public boolean springBack(int p0, int p1, int p2, int p3, int p4, int p5) { return false; }
    public void startScroll(int p0, int p1, int p2, int p3) {}
    public void startScroll(int p0, int p1, int p2, int p3, int p4) {}
}
