// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class PopupMenu {
    public void dismiss() {}
    public android.view.View.OnTouchListener getDragToOpenListener() { return null; }
    public android.view.Menu getMenu() { return null; }
    public android.view.MenuInflater getMenuInflater() { return null; }
    public void inflate(int p0) {}
    public void setOnMenuItemClickListener(android.widget.PopupMenu.OnMenuItemClickListener p0) {}
    public void show() {}

    public interface OnMenuItemClickListener {
    }
}
