// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ProgressBar {
    public android.content.Context getContext() { return null; }
    public android.graphics.drawable.Drawable getIndeterminateDrawable() { return null; }
    public android.view.ViewGroup.LayoutParams getLayoutParams() { return null; }
    public int getMax() { return 0; }
    public android.view.ViewParent getParent() { return null; }
    public int getProgress() { return 0; }
    public android.graphics.drawable.Drawable getProgressDrawable() { return null; }
    public int getSecondaryProgress() { return 0; }
    public int getVisibility() { return 0; }
    public void incrementProgressBy(int p0) {}
    public void invalidate() {}
    public boolean isIndeterminate() { return false; }
    public void onAttachedToWindow() {}
    public void onDetachedFromWindow() {}
    public void onLayout(boolean p0, int p1, int p2, int p3, int p4) {}
    public void onVisibilityChanged(android.view.View p0, int p1) {}
    public void onWindowVisibilityChanged(int p0) {}
    public boolean postDelayed(java.lang.Runnable p0, long p1) { return false; }
    public boolean removeCallbacks(java.lang.Runnable p0) { return false; }
    public void requestLayout() {}
    public void setAlpha(float p0) {}
    public void setIndeterminate(boolean p0) {}
    public void setIndeterminateDrawable(android.graphics.drawable.Drawable p0) {}
    public void setMax(int p0) {}
    public void setProgress(int p0) {}
    public void setProgress(int p0, boolean p1) {}
    public void setProgressDrawable(android.graphics.drawable.Drawable p0) {}
    public void setProgressTintList(android.content.res.ColorStateList p0) {}
    public void setSecondaryProgress(int p0) {}
    public void setTag(java.lang.Object p0) {}
    public void setVisibility(int p0) {}
    public void startAnimation(android.view.animation.Animation p0) {}
}
