// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class RadioGroup {
    public void addView(android.view.View p0) {}
    public void check(int p0) {}
    public void clearCheck() {}
    public int getCheckedRadioButtonId() { return 0; }
    public android.view.View getChildAt(int p0) { return null; }
    public int getChildCount() { return 0; }
    public void setOnCheckedChangeListener(android.widget.RadioGroup.OnCheckedChangeListener p0) {}
    public void setVisibility(int p0) {}

    public static class LayoutParams {
    }

    public interface OnCheckedChangeListener {
        void onCheckedChanged(android.widget.RadioGroup p0, int p1);
    }
}
