// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class RatingBar {
    public android.content.Context getContext() { return null; }
    public int getMeasuredHeight() { return 0; }
    public int getNumStars() { return 0; }
    public float getRating() { return 0f; }
    public void onMeasure(int p0, int p1) {}
    public void setMeasuredDimension(int p0, int p1) {}
    public void setOnRatingBarChangeListener(android.widget.RatingBar.OnRatingBarChangeListener p0) {}
    public void setRating(float p0) {}

    public interface OnRatingBarChangeListener {
        void onRatingChanged(android.widget.RatingBar p0, float p1, boolean p2);
    }
}
