// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class RemoteViewsService {
    public android.content.Context getApplicationContext() { return null; }

    public static class RemoteViewsFactory {
    }
}
