// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ScrollView {
    public void addView(android.view.View p0) {}
    public boolean awakenScrollBars() { return false; }
    public boolean fullScroll(int p0) { return false; }
    public android.view.View getChildAt(int p0) { return null; }
    public int getChildCount() { return 0; }
    public int getHeight() { return 0; }
    public void getLocationInWindow(int[] p0) {}
    public void onDraw(android.graphics.Canvas p0) {}
    public void onFinishInflate() {}
    public boolean onInterceptTouchEvent(android.view.MotionEvent p0) { return false; }
    public void onScrollChanged(int p0, int p1, int p2, int p3) {}
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public boolean pageScroll(int p0) { return false; }
    public void requestChildFocus(android.view.View p0, android.view.View p1) {}
    public boolean requestChildRectangleOnScreen(android.view.View p0, android.graphics.Rect p1, boolean p2) { return false; }
    public void setFillViewport(boolean p0) {}
    public void setForceDarkAllowed(boolean p0) {}
    public void setLayoutParams(android.view.ViewGroup.LayoutParams p0) {}
    public void setSmoothScrollingEnabled(boolean p0) {}
    public void setTag(java.lang.Object p0) {}
    public void setVerticalScrollBarEnabled(boolean p0) {}
    public void setVisibility(int p0) {}
    public void smoothScrollTo(int p0, int p1) {}
}
