// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class Scroller {
    public void abortAnimation() {}
    public boolean computeScrollOffset() { return false; }
    public void fling(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {}
    public void forceFinished(boolean p0) {}
    public int getCurrX() { return 0; }
    public int getCurrY() { return 0; }
    public int getFinalX() { return 0; }
    public int getFinalY() { return 0; }
    public int getStartX() { return 0; }
    public int getStartY() { return 0; }
    public boolean isFinished() { return false; }
    public void setFinalX(int p0) {}
    public void startScroll(int p0, int p1, int p2, int p3) {}
    public void startScroll(int p0, int p1, int p2, int p3, int p4) {}
}
