// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class SearchView {
    public android.content.Context getContext() { return null; }
    public java.lang.CharSequence getQuery() { return null; }
    public boolean isIconified() { return false; }
    public boolean isQueryRefinementEnabled() { return false; }
    public boolean isSubmitButtonEnabled() { return false; }
    public void onActionViewCollapsed() {}
    public void setIconified(boolean p0) {}
    public void setImeOptions(int p0) {}
    public void setInputType(int p0) {}
    public void setMaxWidth(int p0) {}
    public void setOnCloseListener(android.widget.SearchView.OnCloseListener p0) {}
    public void setOnQueryTextListener(android.widget.SearchView.OnQueryTextListener p0) {}
    public void setOnSuggestionListener(android.widget.SearchView.OnSuggestionListener p0) {}
    public void setQuery(java.lang.CharSequence p0, boolean p1) {}
    public void setQueryHint(java.lang.CharSequence p0) {}
    public void setQueryRefinementEnabled(boolean p0) {}
    public void setSearchableInfo(android.app.SearchableInfo p0) {}
    public void setSubmitButtonEnabled(boolean p0) {}

    public interface OnCloseListener {
    }

    public interface OnQueryTextListener {
    }

    public interface OnSuggestionListener {
    }
}
