// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class SimpleExpandableListAdapter {
    public android.view.View getGroupView(int p0, boolean p1, android.view.View p2, android.view.ViewGroup p3) { return null; }
}
