// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class SpinnerAdapter {
    public int getCount() { return 0; }
    public android.view.View getDropDownView(int p0, android.view.View p1, android.view.ViewGroup p2) { return null; }
    public java.lang.Object getItem(int p0) { return null; }
    public long getItemId(int p0) { return 0; }
    public int getItemViewType(int p0) { return 0; }
    public android.view.View getView(int p0, android.view.View p1, android.view.ViewGroup p2) { return null; }
    public boolean hasStableIds() { return false; }
    public void registerDataSetObserver(android.database.DataSetObserver p0) {}
    public void unregisterDataSetObserver(android.database.DataSetObserver p0) {}
}
