// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class Switch {
    public boolean isChecked() { return false; }
    public void setOnCheckedChangeListener(android.widget.CompoundButton.OnCheckedChangeListener p0) {}
    public void setSwitchTextAppearance(android.content.Context p0, int p1) {}
    public void setTextOff(java.lang.CharSequence p0) {}
    public void setTextOn(java.lang.CharSequence p0) {}
}
