// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class TabHost {
    public void addTab(android.widget.TabHost.TabSpec p0) {}
    public void addView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public android.view.View findViewById(int p0) { return null; }
    public int getCurrentTab() { return 0; }
    public java.lang.String getCurrentTabTag() { return null; }
    public int getId() { return 0; }
    public android.widget.TabWidget getTabWidget() { return null; }
    public android.widget.TabHost.TabSpec newTabSpec(java.lang.String p0) { return null; }
    public void onAttachedToWindow() {}
    public void onDetachedFromWindow() {}
    public void onRestoreInstanceState(android.os.Parcelable p0) {}
    public android.os.Parcelable onSaveInstanceState() { return null; }
    public void setCurrentTab(int p0) {}
    public void setCurrentTabByTag(java.lang.String p0) {}
    public void setId(int p0) {}
    public void setOnTabChangedListener(android.widget.TabHost.OnTabChangeListener p0) {}
    public void setup() {}

    public interface OnTabChangeListener {
        void onTabChanged(java.lang.String p0);
    }

    public static class TabContentFactory {
    }

    public static class TabSpec {
        public java.lang.String getTag() { return null; }
        public android.widget.TabHost.TabSpec setContent(android.widget.TabHost.TabContentFactory p0) { return null; }
        public android.widget.TabHost.TabSpec setIndicator(java.lang.CharSequence p0) { return null; }
    }
}
