// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class TableRow {
    public void addView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public int getChildCount() { return 0; }
    public void setLayoutParams(android.view.ViewGroup.LayoutParams p0) {}
    public void setPadding(int p0, int p1, int p2, int p3) {}
    public void setVisibility(int p0) {}

    public static class LayoutParams {
    }
}
