// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class TableLayout {
    public void addView(android.view.View p0) {}
    public void addView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public boolean isColumnCollapsed(int p0) { return false; }
    public void setColumnCollapsed(int p0, boolean p1) {}
    public void setColumnShrinkable(int p0, boolean p1) {}
    public void setColumnStretchable(int p0, boolean p1) {}
    public void setShrinkAllColumns(boolean p0) {}
    public void setStretchAllColumns(boolean p0) {}

    public static class LayoutParams {
    }
}
