// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class TextSwitcher {
    public void setCurrentText(java.lang.CharSequence p0) {}
    public void setInAnimation(android.view.animation.Animation p0) {}
    public void setOutAnimation(android.view.animation.Animation p0) {}
    public void setText(java.lang.CharSequence p0) {}
    public void setVisibility(int p0) {}
}
