// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ThemedSpinnerAdapter {
    public android.content.res.Resources.Theme getDropDownViewTheme() { return null; }
    public void setDropDownViewTheme(android.content.res.Resources.Theme p0) {}
}
