// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class TimePicker {
    public java.lang.Integer getCurrentHour() { return null; }
    public java.lang.Integer getCurrentMinute() { return null; }
    public int getHour() { return 0; }
    public int getMinute() { return 0; }
    public void setCurrentHour(java.lang.Integer p0) {}
    public void setCurrentMinute(java.lang.Integer p0) {}
    public void setHour(int p0) {}
    public void setIs24HourView(java.lang.Boolean p0) {}
    public void setMinute(int p0) {}
    public void setOnTimeChangedListener(android.widget.TimePicker.OnTimeChangedListener p0) {}

    public interface OnTimeChangedListener {
        void onTimeChanged(android.widget.TimePicker p0, int p1, int p2);
    }
}
