// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class Toast {
    public void cancel() {}
    public android.widget.Toast makeText(android.content.Context p0, int p1, int p2) { return null; }
    public void setGravity(int p0, int p1, int p2) {}
    public void setText(int p0) {}
    public void setView(android.view.View p0) {}
    public void show() {}
}
