// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ToggleButton {
    public void drawableStateChanged() {}
    public android.content.Context getContext() { return null; }
    public void setAllCaps(boolean p0) {}
    public void setBackgroundDrawable(android.graphics.drawable.Drawable p0) {}
    public void setBackgroundResource(int p0) {}
    public void setChecked(boolean p0) {}
    public void setCompoundDrawables(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1, android.graphics.drawable.Drawable p2, android.graphics.drawable.Drawable p3) {}
    public void setCompoundDrawablesRelative(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1, android.graphics.drawable.Drawable p2, android.graphics.drawable.Drawable p3) {}
    public void setEnabled(boolean p0) {}
    public void setFilters(android.text.InputFilter[] p0) {}
    public void setOnCheckedChangeListener(android.widget.CompoundButton.OnCheckedChangeListener p0) {}
    public void setOnClickListener(android.view.View.OnClickListener p0) {}
}
