// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class Toolbar {
    public android.view.View findViewById(int p0) { return null; }
    public void findViewsWithText(java.util.ArrayList p0, java.lang.CharSequence p1, int p2) {}
    public android.view.View getChildAt(int p0) { return null; }
    public int getChildCount() { return 0; }
    public java.lang.CharSequence getNavigationContentDescription() { return null; }
    public android.graphics.drawable.Drawable getNavigationIcon() { return null; }
    public android.graphics.drawable.Drawable getOverflowIcon() { return null; }
    public java.lang.CharSequence getSubtitle() { return null; }
    public java.lang.CharSequence getTitle() { return null; }
    public int getTitleMarginBottom() { return 0; }
    public int getTitleMarginEnd() { return 0; }
    public int getTitleMarginStart() { return 0; }
    public int getTitleMarginTop() { return 0; }
    public void setNavigationContentDescription(java.lang.CharSequence p0) {}
    public void setNavigationIcon(android.graphics.drawable.Drawable p0) {}
    public void setNavigationOnClickListener(android.view.View.OnClickListener p0) {}
    public void setSubtitle(java.lang.CharSequence p0) {}
    public void setTitleMarginStart(int p0) {}
}
