// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class VideoView {
    public boolean isPlaying() { return false; }
    public void onMeasure(int p0, int p1) {}
    public void pause() {}
    public void setMediaController(android.widget.MediaController p0) {}
    public void setOnErrorListener(android.media.MediaPlayer.OnErrorListener p0) {}
    public void setOnPreparedListener(android.media.MediaPlayer.OnPreparedListener p0) {}
    public void setVideoURI(android.net.Uri p0, java.util.Map p1) {}
    public void start() {}
}
