// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ViewFlipper {
    public int getChildCount() { return 0; }
    public int getDisplayedChild() { return 0; }
    public int indexOfChild(android.view.View p0) { return 0; }
    public void setDisplayedChild(int p0) {}
    public void setVisibility(int p0) {}
}
