// @generated by gen-shims.py — do not edit by hand
package android.widget;

public class ViewSwitcher {
    public android.view.View getCurrentView() { return null; }
    public void showNext() {}
    public void showPrevious() {}
}
