// @generated by gen-shims.py — do not edit by hand
package android.opengl;

public class GLU {
    public java.lang.String gluErrorString(int p0) { return null; }
    public void gluOrtho2D(javax.microedition.khronos.opengles.GL10 p0, float p1, float p2, float p3, float p4) {}
    public int gluUnProject(float p0, float p1, float p2, float[] p3, int p4, float[] p5, int p6, int[] p7, int p8, float[] p9, int p10) { return 0; }
}
