// @generated by gen-shims.py — do not edit by hand
package android.text.util;

public class Linkify {
    public boolean addLinks(android.widget.TextView p0, int p1) { return false; }
    public void addLinks(android.widget.TextView p0, java.util.regex.Pattern p1, java.lang.String p2) {}
    public void addLinks(android.widget.TextView p0, java.util.regex.Pattern p1, java.lang.String p2, android.text.util.Linkify.MatchFilter p3, android.text.util.Linkify.TransformFilter p4) {}
    public void addLinks(android.widget.TextView p0, java.util.regex.Pattern p1, java.lang.String p2, java.lang.String[] p3, android.text.util.Linkify.MatchFilter p4, android.text.util.Linkify.TransformFilter p5) {}

    public static class MatchFilter {
        public boolean acceptMatch(java.lang.CharSequence p0, int p1, int p2) { return false; }
    }

    public static class TransformFilter {
        public java.lang.String transformUrl(java.util.regex.Matcher p0, java.lang.String p1) { return null; }
    }
}
