// @generated by gen-shims.py — do not edit by hand
package android.media;

public class ApplicationMediaCapabilities {

    public static class Builder {
        public android.media.ApplicationMediaCapabilities.Builder addSupportedHdrType(java.lang.String p0) { return null; }
        public android.media.ApplicationMediaCapabilities.Builder addSupportedVideoMimeType(java.lang.String p0) { return null; }
        public android.media.ApplicationMediaCapabilities build() { return null; }
    }
}
