// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioRouting {
    public android.media.AudioDeviceInfo getRoutedDevice() { return null; }

    public interface OnRoutingChangedListener {
    }
}
