// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioFormat {

    public static class Builder {
        public android.media.AudioFormat build() { return null; }
        public android.media.AudioFormat.Builder setChannelMask(int p0) { return null; }
        public android.media.AudioFormat.Builder setEncoding(int p0) { return null; }
        public android.media.AudioFormat.Builder setSampleRate(int p0) { return null; }
    }
}
