// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioRecord {
    public int getMinBufferSize(int p0, int p1, int p2) { return 0; }
    public int getState() { return 0; }
    public int read(short[] p0, int p1, int p2) { return 0; }
    public void release() {}
    public void startRecording() {}
    public void stop() {}
}
