// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioManager {
    public int abandonAudioFocus(android.media.AudioManager.OnAudioFocusChangeListener p0) { return 0; }
    public int abandonAudioFocusRequest(android.media.AudioFocusRequest p0) { return 0; }
    public void adjustStreamVolume(int p0, int p1, int p2) {}
    public int generateAudioSessionId() { return 0; }
    public java.util.List getAudioDevicesForAttributes(android.media.AudioAttributes p0) { return null; }
    public android.media.AudioDeviceInfo getCommunicationDevice() { return null; }
    public android.media.AudioDeviceInfo[] getDevices(int p0) { return null; }
    public java.util.List getDirectProfilesForAttributes(android.media.AudioAttributes p0) { return null; }
    public int getMode() { return 0; }
    public java.lang.String getParameters(java.lang.String p0) { return null; }
    public int getPlaybackOffloadSupport(android.media.AudioFormat p0, android.media.AudioAttributes p1) { return 0; }
    public int getRingerMode() { return 0; }
    public android.media.Spatializer getSpatializer() { return null; }
    public int getStreamMaxVolume(int p0) { return 0; }
    public int getStreamMinVolume(int p0) { return 0; }
    public int getStreamVolume(int p0) { return 0; }
    public boolean isBluetoothA2dpOn() { return false; }
    public boolean isBluetoothScoAvailableOffCall() { return false; }
    public boolean isBluetoothScoOn() { return false; }
    public boolean isMusicActive() { return false; }
    public boolean isOffloadedPlaybackSupported(android.media.AudioFormat p0, android.media.AudioAttributes p1) { return false; }
    public boolean isSpeakerphoneOn() { return false; }
    public boolean isStreamMute(int p0) { return false; }
    public boolean isVolumeFixed() { return false; }
    public void playSoundEffect(int p0) {}
    public void playSoundEffect(int p0, float p1) {}
    public void registerAudioDeviceCallback(android.media.AudioDeviceCallback p0, android.os.Handler p1) {}
    public void registerMediaButtonEventReceiver(android.app.PendingIntent p0) {}
    public void registerRemoteControlClient(android.media.RemoteControlClient p0) {}
    public int requestAudioFocus(android.media.AudioManager.OnAudioFocusChangeListener p0, int p1, int p2) { return 0; }
    public int requestAudioFocus(android.media.AudioFocusRequest p0) { return 0; }
    public void setMode(int p0) {}
    public void setParameters(java.lang.String p0) {}
    public void setStreamMute(int p0, boolean p1) {}
    public void setStreamVolume(int p0, int p1, int p2) {}
    public void unloadSoundEffects() {}
    public void unregisterAudioDeviceCallback(android.media.AudioDeviceCallback p0) {}
    public void unregisterMediaButtonEventReceiver(android.app.PendingIntent p0) {}
    public void unregisterRemoteControlClient(android.media.RemoteControlClient p0) {}

    public interface OnAudioFocusChangeListener {
        void onAudioFocusChange(int p0);
    }
}
