// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioProfile {
    public int[] getChannelMasks() { return null; }
    public int getEncapsulationType() { return 0; }
    public int getFormat() { return 0; }
}
