// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioDeviceInfo {
    public int[] getEncodings() { return null; }
    public int getId() { return 0; }
    public int getType() { return 0; }
    public boolean isSink() { return false; }
}
