// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioAttributes {
    public boolean equals(java.lang.Object p0) { return false; }
    public int getContentType() { return 0; }
    public int getFlags() { return 0; }
    public int getUsage() { return 0; }
    public int getVolumeControlStream() { return 0; }
    public int hashCode() { return 0; }

    public static class Builder {
        public android.media.AudioAttributes build() { return null; }
        public android.media.AudioAttributes.Builder setAllowedCapturePolicy(int p0) { return null; }
        public android.media.AudioAttributes.Builder setContentType(int p0) { return null; }
        public android.media.AudioAttributes.Builder setFlags(int p0) { return null; }
        public android.media.AudioAttributes.Builder setHapticChannelsMuted(boolean p0) { return null; }
        public android.media.AudioAttributes.Builder setIsContentSpatialized(boolean p0) { return null; }
        public android.media.AudioAttributes.Builder setLegacyStreamType(int p0) { return null; }
        public android.media.AudioAttributes.Builder setSpatializationBehavior(int p0) { return null; }
        public android.media.AudioAttributes.Builder setUsage(int p0) { return null; }
    }
}
