// @generated by gen-shims.py — do not edit by hand
package android.media;

public class AudioTrack {
    public void addOnRoutingChangedListener(android.media.AudioRouting.OnRoutingChangedListener p0, android.os.Handler p1) {}
    public int attachAuxEffect(int p0) { return 0; }
    public void flush() {}
    public int getAudioSessionId() { return 0; }
    public int getBufferSizeInFrames() { return 0; }
    public int getMinBufferSize(int p0, int p1, int p2) { return 0; }
    public int getPlayState() { return 0; }
    public int getPlaybackHeadPosition() { return 0; }
    public android.media.PlaybackParams getPlaybackParams() { return null; }
    public int getSampleRate() { return 0; }
    public int getState() { return 0; }
    public boolean getTimestamp(android.media.AudioTimestamp p0) { return false; }
    public int getUnderrunCount() { return 0; }
    public boolean isDirectPlaybackSupported(android.media.AudioFormat p0, android.media.AudioAttributes p1) { return false; }
    public boolean isOffloadedPlayback() { return false; }
    public void pause() {}
    public void play() {}
    public void registerStreamEventCallback(java.util.concurrent.Executor p0, android.media.AudioTrack.StreamEventCallback p1) {}
    public void release() {}
    public void removeOnRoutingChangedListener(android.media.AudioRouting.OnRoutingChangedListener p0) {}
    public int setAuxEffectSendLevel(float p0) { return 0; }
    public void setLogSessionId(android.media.metrics.LogSessionId p0) {}
    public void setOffloadDelayPadding(int p0, int p1) {}
    public void setOffloadEndOfStream() {}
    public void setPlaybackParams(android.media.PlaybackParams p0) {}
    public boolean setPreferredDevice(android.media.AudioDeviceInfo p0) { return false; }
    public int setStereoVolume(float p0, float p1) { return 0; }
    public int setVolume(float p0) { return 0; }
    public void stop() {}
    public void unregisterStreamEventCallback(android.media.AudioTrack.StreamEventCallback p0) {}
    public int write(short[] p0, int p1, int p2) { return 0; }
    public int write(java.nio.ByteBuffer p0, int p1, int p2, long p3) { return 0; }

    public static class Builder {
        public android.media.AudioTrack build() { return null; }
        public android.media.AudioTrack.Builder setAudioAttributes(android.media.AudioAttributes p0) { return null; }
        public android.media.AudioTrack.Builder setAudioFormat(android.media.AudioFormat p0) { return null; }
        public android.media.AudioTrack.Builder setBufferSizeInBytes(int p0) { return null; }
        public android.media.AudioTrack.Builder setContext(android.content.Context p0) { return null; }
        public android.media.AudioTrack.Builder setOffloadedPlayback(boolean p0) { return null; }
        public android.media.AudioTrack.Builder setSessionId(int p0) { return null; }
        public android.media.AudioTrack.Builder setTransferMode(int p0) { return null; }
    }

    public interface StreamEventCallback {
    }
}
