// @generated by gen-shims.py — do not edit by hand
package android.media;

public class DrmInitData {
    public android.media.DrmInitData.SchemeInitData getSchemeInitDataAt(int p0) { return null; }
    public int getSchemeInitDataCount() { return 0; }

    public static class SchemeInitData {
    }
}
