// @generated by gen-shims.py — do not edit by hand
package android.media;

public class Image {
    public void close() {}
    public android.hardware.SyncFence getFence() { return null; }
    public android.hardware.HardwareBuffer getHardwareBuffer() { return null; }
    public int getHeight() { return 0; }
    public android.media.Image.Plane[] getPlanes() { return null; }
    public int getWidth() { return 0; }

    public static class Plane {
        public java.nio.ByteBuffer getBuffer() { return null; }
        public int getPixelStride() { return 0; }
        public int getRowStride() { return 0; }
    }
}
