// @generated by gen-shims.py — do not edit by hand
package android.media;

public class ImageReader {
    public android.media.Image acquireLatestImage() { return null; }
    public void close() {}
    public int getHeight() { return 0; }
    public android.view.Surface getSurface() { return null; }
    public int getWidth() { return 0; }
    public android.media.ImageReader newInstance(int p0, int p1, int p2, int p3) { return null; }
    public android.media.ImageReader newInstance(int p0, int p1, int p2, int p3, long p4) { return null; }
    public void setOnImageAvailableListener(android.media.ImageReader.OnImageAvailableListener p0, android.os.Handler p1) {}

    public static class Builder {
        public android.media.ImageReader build() { return null; }
        public android.media.ImageReader.Builder setImageFormat(int p0) { return null; }
        public android.media.ImageReader.Builder setMaxImages(int p0) { return null; }
        public android.media.ImageReader.Builder setUsage(long p0) { return null; }
    }

    public interface OnImageAvailableListener {
    }
}
