// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaDescription {
    public java.lang.CharSequence getDescription() { return null; }
    public android.os.Bundle getExtras() { return null; }
    public android.graphics.Bitmap getIconBitmap() { return null; }
    public android.net.Uri getIconUri() { return null; }
    public java.lang.String getMediaId() { return null; }
    public android.net.Uri getMediaUri() { return null; }
    public java.lang.CharSequence getSubtitle() { return null; }
    public java.lang.CharSequence getTitle() { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}

    public static class Builder {
        public android.media.MediaDescription build() { return null; }
        public android.media.MediaDescription.Builder setDescription(java.lang.CharSequence p0) { return null; }
        public android.media.MediaDescription.Builder setExtras(android.os.Bundle p0) { return null; }
        public android.media.MediaDescription.Builder setIconBitmap(android.graphics.Bitmap p0) { return null; }
        public android.media.MediaDescription.Builder setIconUri(android.net.Uri p0) { return null; }
        public android.media.MediaDescription.Builder setMediaId(java.lang.String p0) { return null; }
        public android.media.MediaDescription.Builder setMediaUri(android.net.Uri p0) { return null; }
        public android.media.MediaDescription.Builder setSubtitle(java.lang.CharSequence p0) { return null; }
        public android.media.MediaDescription.Builder setTitle(java.lang.CharSequence p0) { return null; }
    }
}
