// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaMetadataRetriever {
    public java.lang.String extractMetadata(int p0) { return null; }
    public byte[] getEmbeddedPicture() { return null; }
    public android.graphics.Bitmap getFrameAtIndex(int p0, android.media.MediaMetadataRetriever.BitmapParams p1) { return null; }
    public android.graphics.Bitmap getFrameAtTime(long p0, int p1) { return null; }
    public android.graphics.Bitmap getFrameAtTime(long p0, int p1, android.media.MediaMetadataRetriever.BitmapParams p2) { return null; }
    public android.graphics.Bitmap getScaledFrameAtTime(long p0, int p1, int p2, int p3) { return null; }
    public android.graphics.Bitmap getScaledFrameAtTime(long p0, int p1, int p2, int p3, android.media.MediaMetadataRetriever.BitmapParams p4) { return null; }
    public void release() {}
    public void setDataSource(android.media.MediaDataSource p0) {}
    public void setDataSource(java.io.FileDescriptor p0, long p1, long p2) {}
    public void setDataSource(android.content.Context p0, android.net.Uri p1) {}

    public static class BitmapParams {
        public void setPreferredConfig(android.graphics.Bitmap.Config p0) {}
    }
}
