// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaParser {
    public boolean advance(android.media.MediaParser.SeekableInputReader p0) { return false; }
    public android.media.MediaParser create(android.media.MediaParser.OutputConsumer p0, java.lang.String[] p1) { return null; }
    public android.media.MediaParser createByName(java.lang.String p0, android.media.MediaParser.OutputConsumer p1) { return null; }
    public java.lang.String getParserName() { return null; }
    public void release() {}
    public void seek(android.media.MediaParser.SeekPoint p0) {}
    public void setLogSessionId(android.media.metrics.LogSessionId p0) {}
    public android.media.MediaParser setParameter(java.lang.String p0, java.lang.Object p1) { return null; }

    public static class InputReader {
        public long getLength() { return 0; }
        public int read(byte[] p0, int p1, int p2) { return 0; }
    }

    public static class OutputConsumer {
    }

    public static class SeekMap {
        public long getDurationMicros() { return 0; }
        public android.util.Pair getSeekPoints(long p0) { return null; }
        public boolean isSeekable() { return false; }
    }

    public static class SeekPoint {
    }

    public static class SeekableInputReader {
    }

    public static class TrackData {
    }
}
