// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaMetadataEditor {
    public android.media.MediaMetadataEditor putObject(int p0, java.lang.Object p1) { return null; }
}
