// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaCodecList {
    public int getCodecCount() { return 0; }
    public android.media.MediaCodecInfo getCodecInfoAt(int p0) { return null; }
    public android.media.MediaCodecInfo[] getCodecInfos() { return null; }
}
