// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaMetadata {
    public android.graphics.Bitmap getBitmap(java.lang.String p0) { return null; }
    public long getLong(java.lang.String p0) { return 0; }
    public android.media.Rating getRating(java.lang.String p0) { return null; }
    public java.lang.CharSequence getText(java.lang.String p0) { return null; }
    public java.util.Set keySet() { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}

    public static class Builder {
        public android.media.MediaMetadata build() { return null; }
        public android.media.MediaMetadata.Builder putBitmap(java.lang.String p0, android.graphics.Bitmap p1) { return null; }
        public android.media.MediaMetadata.Builder putLong(java.lang.String p0, long p1) { return null; }
        public android.media.MediaMetadata.Builder putRating(java.lang.String p0, android.media.Rating p1) { return null; }
        public android.media.MediaMetadata.Builder putString(java.lang.String p0, java.lang.String p1) { return null; }
        public android.media.MediaMetadata.Builder putText(java.lang.String p0, java.lang.CharSequence p1) { return null; }
    }
}
