// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaRecorder {
    public void prepare() {}
    public void release() {}
    public void reset() {}
    public void setAudioEncoder(int p0) {}
    public void setAudioSource(int p0) {}
    public void setOutputFile(java.lang.String p0) {}
    public void setOutputFormat(int p0) {}
    public void start() {}
    public void stop() {}
}
