// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaDataSource {
    public long getSize() { return 0; }
    public int readAt(long p0, byte[] p1, int p2, int p3) { return 0; }
}
