// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaExtractor {
    public boolean advance() { return false; }
    public long getCachedDuration() { return 0; }
    public java.util.Map getPsshInfo() { return null; }
    public boolean getSampleCryptoInfo(android.media.MediaCodec.CryptoInfo p0) { return false; }
    public int getSampleFlags() { return 0; }
    public long getSampleTime() { return 0; }
    public int getSampleTrackIndex() { return 0; }
    public int getTrackCount() { return 0; }
    public android.media.MediaFormat getTrackFormat(int p0) { return null; }
    public int readSampleData(java.nio.ByteBuffer p0, int p1) { return 0; }
    public void release() {}
    public void seekTo(long p0, int p1) {}
    public void selectTrack(int p0) {}
    public void setDataSource(android.media.MediaDataSource p0) {}
    public void setDataSource(java.io.FileDescriptor p0, long p1, long p2) {}
    public void unselectTrack(int p0) {}
}
