// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaScannerConnection {
    public void scanFile(android.content.Context p0, java.lang.String[] p1, java.lang.String[] p2, android.media.MediaScannerConnection.OnScanCompletedListener p3) {}

    public interface OnScanCompletedListener {
    }
}
