// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaRouter {
    public void addCallback(int p0, android.media.MediaRouter.Callback p1) {}
    public android.media.MediaRouter.RouteInfo getSelectedRoute(int p0) { return null; }
    public void removeCallback(android.media.MediaRouter.Callback p0) {}

    public interface Callback {
    }

    public static class RouteInfo {
        public android.view.Display getPresentationDisplay() { return null; }
    }

    public interface SimpleCallback {
    }
}
