// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaFormat {
    public boolean containsKey(java.lang.String p0) { return false; }
    public java.nio.ByteBuffer getByteBuffer(java.lang.String p0) { return null; }
    public float getFloat(java.lang.String p0) { return 0f; }
    public float getFloat(java.lang.String p0, float p1) { return 0f; }
    public int getInteger(java.lang.String p0) { return 0; }
    public int getInteger(java.lang.String p0, int p1) { return 0; }
    public long getLong(java.lang.String p0, long p1) { return 0; }
    public long getLong(java.lang.String p0) { return 0; }
    public java.lang.String getString(java.lang.String p0) { return null; }
    public int getValueTypeForKey(java.lang.String p0) { return 0; }
    public void setByteBuffer(java.lang.String p0, java.nio.ByteBuffer p1) {}
    public void setFeatureEnabled(java.lang.String p0, boolean p1) {}
    public void setFloat(java.lang.String p0, float p1) {}
    public void setInteger(java.lang.String p0, int p1) {}
    public void setLong(java.lang.String p0, long p1) {}
    public void setString(java.lang.String p0, java.lang.String p1) {}
}
