// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaCrypto {
    public void release() {}
    public boolean requiresSecureDecoderComponent(java.lang.String p0) { return false; }
    public void setMediaDrmSession(byte[] p0) {}
}
