// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaPlayer {
    public android.media.MediaPlayer create(android.content.Context p0, int p1) { return null; }
    public int getCurrentPosition() { return 0; }
    public int getDuration() { return 0; }
    public android.os.PersistableBundle getMetrics() { return null; }
    public android.media.MediaPlayer.TrackInfo[] getTrackInfo() { return null; }
    public int getVideoHeight() { return 0; }
    public int getVideoWidth() { return 0; }
    public boolean isLooping() { return false; }
    public boolean isPlaying() { return false; }
    public void pause() {}
    public void prepare() {}
    public void prepareAsync() {}
    public void release() {}
    public void reset() {}
    public void seekTo(int p0) {}
    public void setAudioAttributes(android.media.AudioAttributes p0) {}
    public void setAudioStreamType(int p0) {}
    public void setDataSource(java.io.FileDescriptor p0, long p1, long p2) {}
    public void setDataSource(java.lang.String p0) {}
    public void setDataSource(android.content.Context p0, android.net.Uri p1) {}
    public void setDisplay(android.view.SurfaceHolder p0) {}
    public void setLooping(boolean p0) {}
    public void setOnBufferingUpdateListener(android.media.MediaPlayer.OnBufferingUpdateListener p0) {}
    public void setOnCompletionListener(android.media.MediaPlayer.OnCompletionListener p0) {}
    public void setOnErrorListener(android.media.MediaPlayer.OnErrorListener p0) {}
    public void setOnInfoListener(android.media.MediaPlayer.OnInfoListener p0) {}
    public void setOnPreparedListener(android.media.MediaPlayer.OnPreparedListener p0) {}
    public void setOnSeekCompleteListener(android.media.MediaPlayer.OnSeekCompleteListener p0) {}
    public void setOnVideoSizeChangedListener(android.media.MediaPlayer.OnVideoSizeChangedListener p0) {}
    public void setScreenOnWhilePlaying(boolean p0) {}
    public void setSurface(android.view.Surface p0) {}
    public void setVolume(float p0, float p1) {}
    public void start() {}
    public void stop() {}

    public interface OnBufferingUpdateListener {
    }

    public interface OnCompletionListener {
    }

    public interface OnErrorListener {
    }

    public interface OnInfoListener {
    }

    public interface OnPreparedListener {
    }

    public interface OnSeekCompleteListener {
    }

    public interface OnVideoSizeChangedListener {
    }

    public static class TrackInfo {
        public android.media.MediaFormat getFormat() { return null; }
        public int getTrackType() { return 0; }
    }
}
