// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaCodec {
    public void configure(android.media.MediaFormat p0, android.view.Surface p1, android.media.MediaCrypto p2, int p3) {}
    public android.media.MediaCodec createByCodecName(java.lang.String p0) { return null; }
    public int dequeueInputBuffer(long p0) { return 0; }
    public int dequeueOutputBuffer(android.media.MediaCodec.BufferInfo p0, long p1) { return 0; }
    public void detachOutputSurface() {}
    public void flush() {}
    public java.nio.ByteBuffer getInputBuffer(int p0) { return null; }
    public java.nio.ByteBuffer[] getInputBuffers() { return null; }
    public android.os.PersistableBundle getMetrics() { return null; }
    public java.nio.ByteBuffer getOutputBuffer(int p0) { return null; }
    public java.nio.ByteBuffer[] getOutputBuffers() { return null; }
    public android.media.MediaFormat getOutputFormat() { return null; }
    public void queueInputBuffer(int p0, int p1, int p2, long p3, int p4) {}
    public void queueSecureInputBuffer(int p0, int p1, android.media.MediaCodec.CryptoInfo p2, long p3, int p4) {}
    public void release() {}
    public void releaseOutputBuffer(int p0, long p1) {}
    public void setCallback(android.media.MediaCodec.Callback p0, android.os.Handler p1) {}
    public void setOnFrameRenderedListener(android.media.MediaCodec.OnFrameRenderedListener p0, android.os.Handler p1) {}
    public void setOutputSurface(android.view.Surface p0) {}
    public void setParameters(android.os.Bundle p0) {}
    public void setVideoScalingMode(int p0) {}
    public void start() {}
    public void stop() {}
    public void subscribeToVendorParameters(java.util.List p0) {}

    public static class BufferInfo {
        public void set(int p0, int p1, long p2, int p3) {}
    }

    public interface Callback {
    }

    public static class CodecException {
        public java.lang.String getDiagnosticInfo() { return null; }
        public int getErrorCode() { return 0; }
        public boolean isRecoverable() { return false; }
    }

    public static class CryptoException {
        public int getErrorCode() { return 0; }
        public java.lang.String getMessage() { return null; }
    }

    public static class CryptoInfo {
        public void set(int p0, int[] p1, int[] p2, byte[] p3, byte[] p4, int p5) {}
        public void setPattern(Object p0) {}
        public java.lang.String toString() { return null; }
    }

    public interface OnFrameRenderedListener {
    }

    public static class Pattern {
        public void set(int p0, int p1) {}
    }
}
