// @generated by gen-shims.py — do not edit by hand
package android.media;

public class MediaCodecInfo {
    public android.media.MediaCodecInfo.CodecCapabilities getCapabilitiesForType(java.lang.String p0) { return null; }
    public java.lang.String getName() { return null; }
    public java.lang.String[] getSupportedTypes() { return null; }
    public boolean isAlias() { return false; }
    public boolean isEncoder() { return false; }
    public boolean isHardwareAccelerated() { return false; }
    public boolean isSoftwareOnly() { return false; }
    public boolean isVendor() { return false; }

    public static class AudioCapabilities {
        public int getMaxInputChannelCount() { return 0; }
        public boolean isSampleRateSupported(int p0) { return false; }
    }

    public static class CodecCapabilities {
        public android.media.MediaCodecInfo.AudioCapabilities getAudioCapabilities() { return null; }
        public int getMaxSupportedInstances() { return 0; }
        public android.media.MediaCodecInfo.VideoCapabilities getVideoCapabilities() { return null; }
        public boolean isFeatureRequired(java.lang.String p0) { return false; }
        public boolean isFeatureSupported(java.lang.String p0) { return false; }
    }

    public static class CodecProfileLevel {
    }

    public static class PerformancePoint {
        public boolean covers(Object p0) { return false; }
    }

    public static class VideoCapabilities {
        public boolean areSizeAndRateSupported(int p0, int p1, double p2) { return false; }
        public android.util.Range getAchievableFrameRatesFor(int p0, int p1) { return null; }
        public android.util.Range getBitrateRange() { return null; }
        public int getHeightAlignment() { return 0; }
        public android.util.Range getSupportedFrameRates() { return null; }
        public android.util.Range getSupportedHeights() { return null; }
        public java.util.List getSupportedPerformancePoints() { return null; }
        public android.util.Range getSupportedWidths() { return null; }
        public int getWidthAlignment() { return 0; }
        public boolean isSizeSupported(int p0, int p1) { return false; }
    }
}
