// @generated by gen-shims.py — do not edit by hand
package android.media;

public class PlaybackParams {
    public android.media.PlaybackParams allowDefaults() { return null; }
    public float getPitch() { return 0f; }
    public float getSpeed() { return 0f; }
    public android.media.PlaybackParams setAudioFallbackMode(int p0) { return null; }
    public android.media.PlaybackParams setPitch(float p0) { return null; }
    public android.media.PlaybackParams setSpeed(float p0) { return null; }
}
