// @generated by gen-shims.py — do not edit by hand
package android.media;

public class Rating {
    public float getPercentRating() { return 0f; }
    public int getRatingStyle() { return 0; }
    public float getStarRating() { return 0f; }
    public boolean hasHeart() { return false; }
    public boolean isRated() { return false; }
    public boolean isThumbUp() { return false; }
    public android.media.Rating newHeartRating(boolean p0) { return null; }
    public android.media.Rating newPercentageRating(float p0) { return null; }
    public android.media.Rating newStarRating(int p0, float p1) { return null; }
    public android.media.Rating newThumbRating(boolean p0) { return null; }
    public android.media.Rating newUnratedRating(int p0) { return null; }
}
