// @generated by gen-shims.py — do not edit by hand
package android.media;

public class RemoteControlClient {
    public android.media.RemoteControlClient.MetadataEditor editMetadata(boolean p0) { return null; }
    public void setMetadataUpdateListener(android.media.RemoteControlClient.OnMetadataUpdateListener p0) {}
    public void setOnGetPlaybackPositionListener(android.media.RemoteControlClient.OnGetPlaybackPositionListener p0) {}
    public void setPlaybackPositionUpdateListener(android.media.RemoteControlClient.OnPlaybackPositionUpdateListener p0) {}
    public void setPlaybackState(int p0) {}
    public void setPlaybackState(int p0, long p1, float p2) {}
    public void setTransportControlFlags(int p0) {}

    public static class MetadataEditor {
        public void addEditableKey(int p0) {}
        public void apply() {}
        public android.media.RemoteControlClient.MetadataEditor putBitmap(int p0, android.graphics.Bitmap p1) { return null; }
        public android.media.RemoteControlClient.MetadataEditor putLong(int p0, long p1) { return null; }
        public android.media.MediaMetadataEditor putObject(int p0, java.lang.Object p1) { return null; }
        public android.media.RemoteControlClient.MetadataEditor putString(int p0, java.lang.String p1) { return null; }
    }

    public interface OnGetPlaybackPositionListener {
    }

    public interface OnMetadataUpdateListener {
    }

    public interface OnPlaybackPositionUpdateListener {
    }
}
