// @generated by gen-shims.py — do not edit by hand
package android.media;

public class RingtoneManager {
    public android.net.Uri getDefaultUri(int p0) { return null; }
    public void setActualDefaultRingtoneUri(android.content.Context p0, int p1, android.net.Uri p2) {}
}
