// @generated by gen-shims.py — do not edit by hand
package android.media;

public class RouteDiscoveryPreference {

    public static class Builder {
        public android.media.RouteDiscoveryPreference build() { return null; }
    }
}
