// @generated by gen-shims.py — do not edit by hand
package android.media;

public class SoundPool {
    public void autoPause() {}
    public void autoResume() {}
    public int load(android.content.res.AssetFileDescriptor p0, int p1) { return 0; }
    public int load(android.content.Context p0, int p1, int p2) { return 0; }
    public void pause(int p0) {}
    public int play(int p0, float p1, float p2, int p3, int p4, float p5) { return 0; }
    public void release() {}
    public void resume(int p0) {}
    public void setLoop(int p0, int p1) {}
    public void setOnLoadCompleteListener(android.media.SoundPool.OnLoadCompleteListener p0) {}
    public void setRate(int p0, float p1) {}
    public void setVolume(int p0, float p1, float p2) {}
    public void stop(int p0) {}
    public boolean unload(int p0) { return false; }

    public static class Builder {
        public android.media.SoundPool build() { return null; }
        public android.media.SoundPool.Builder setAudioAttributes(android.media.AudioAttributes p0) { return null; }
        public android.media.SoundPool.Builder setMaxStreams(int p0) { return null; }
    }

    public interface OnLoadCompleteListener {
    }
}
