// @generated by gen-shims.py — do not edit by hand
package android.text;

public class Annotation {
    public java.lang.String getKey() { return null; }
    public java.lang.String getValue() { return null; }
}
