// @generated by gen-shims.py — do not edit by hand
package android.text;

public class DynamicLayout {
    public void draw(android.graphics.Canvas p0) {}
    public int getHeight() { return 0; }
    public int getWidth() { return 0; }
}
