// @generated by gen-shims.py — do not edit by hand
package android.text;

public class Html {
    public java.lang.String escapeHtml(java.lang.CharSequence p0) { return null; }
    public android.text.Spanned fromHtml(java.lang.String p0) { return null; }
    public android.text.Spanned fromHtml(java.lang.String p0, int p1) { return null; }
    public android.text.Spanned fromHtml(java.lang.String p0, int p1, android.text.Html.ImageGetter p2, android.text.Html.TagHandler p3) { return null; }
    public android.text.Spanned fromHtml(java.lang.String p0, android.text.Html.ImageGetter p1, android.text.Html.TagHandler p2) { return null; }
    public java.lang.String toHtml(android.text.Spanned p0) { return null; }
    public java.lang.String toHtml(android.text.Spanned p0, int p1) { return null; }

    public static class ImageGetter {
    }

    public interface TagHandler {
    }
}
