// @generated by gen-shims.py — do not edit by hand
package android.text;

public class InputFilter {
    public java.lang.CharSequence filter(java.lang.CharSequence p0, int p1, int p2, android.text.Spanned p3, int p4, int p5) { return null; }

    public static class LengthFilter {
        public int getMax() { return 0; }
    }
}
