// @generated by gen-shims.py — do not edit by hand
package android.text;

public class Layout {
    public void draw(android.graphics.Canvas p0) {}
    public int getBottomPadding() { return 0; }
    public float getDesiredWidth(java.lang.CharSequence p0, android.text.TextPaint p1) { return 0f; }
    public float getDesiredWidth(java.lang.CharSequence p0, int p1, int p2, android.text.TextPaint p3) { return 0f; }
    public int getEllipsisCount(int p0) { return 0; }
    public int getEllipsisStart(int p0) { return 0; }
    public int getEllipsizedWidth() { return 0; }
    public int getHeight() { return 0; }
    public int getLineAscent(int p0) { return 0; }
    public int getLineBaseline(int p0) { return 0; }
    public int getLineBottom(int p0) { return 0; }
    public int getLineCount() { return 0; }
    public int getLineDescent(int p0) { return 0; }
    public int getLineEnd(int p0) { return 0; }
    public int getLineForOffset(int p0) { return 0; }
    public int getLineForVertical(int p0) { return 0; }
    public float getLineLeft(int p0) { return 0f; }
    public float getLineRight(int p0) { return 0f; }
    public int getLineStart(int p0) { return 0; }
    public int getLineTop(int p0) { return 0; }
    public float getLineWidth(int p0) { return 0f; }
    public int getOffsetForHorizontal(int p0, float p1) { return 0; }
    public android.text.TextPaint getPaint() { return null; }
    public android.text.Layout.Alignment getParagraphAlignment(int p0) { return null; }
    public int getParagraphDirection(int p0) { return 0; }
    public float getPrimaryHorizontal(int p0) { return 0f; }
    public int[] getRangeForRect(android.graphics.RectF p0, android.text.SegmentFinder p1, android.text.Layout.TextInclusionStrategy p2) { return null; }
    public float getSecondaryHorizontal(int p0) { return 0f; }
    public void getSelectionPath(int p0, int p1, android.graphics.Path p2) {}
    public float getSpacingAdd() { return 0f; }
    public float getSpacingMultiplier() { return 0f; }
    public java.lang.CharSequence getText() { return null; }
    public int getTopPadding() { return 0; }
    public int getWidth() { return 0; }
    public boolean isRtlCharAt(int p0) { return false; }

    public static class Alignment {
        public int hashCode() { return 0; }
        public int ordinal() { return 0; }
        public android.text.Layout.Alignment[] values() { return null; }
    }

    public static class TextInclusionStrategy {
    }
}
