// @generated by gen-shims.py — do not edit by hand
package android.text;

public class PrecomputedText {
    public android.text.PrecomputedText create(java.lang.CharSequence p0, android.text.PrecomputedText.Params p1) { return null; }
    public int getParagraphCount() { return 0; }
    public int getParagraphEnd(int p0) { return 0; }
    public int getParagraphStart(int p0) { return 0; }
    public java.lang.Object[] getSpans(int p0, int p1, java.lang.Class p2) { return null; }
    public void removeSpan(java.lang.Object p0) {}
    public void setSpan(java.lang.Object p0, int p1, int p2, int p3) {}

    public static class Builder {
        public android.text.PrecomputedText.Params build() { return null; }
        public Object setBreakStrategy(int p0) { return null; }
        public Object setHyphenationFrequency(int p0) { return null; }
        public Object setTextDirection(android.text.TextDirectionHeuristic p0) { return null; }
    }

    public static class Params {
        public boolean equals(java.lang.Object p0) { return false; }
        public int getBreakStrategy() { return 0; }
        public int getHyphenationFrequency() { return 0; }
        public android.text.TextDirectionHeuristic getTextDirection() { return null; }
        public android.text.TextPaint getTextPaint() { return null; }
    }
}
