// @generated by gen-shims.py — do not edit by hand
package android.text;

public class Selection {
    public boolean extendDown(android.text.Spannable p0, android.text.Layout p1) { return false; }
    public boolean extendUp(android.text.Spannable p0, android.text.Layout p1) { return false; }
    public int getSelectionEnd(java.lang.CharSequence p0) { return 0; }
    public int getSelectionStart(java.lang.CharSequence p0) { return 0; }
    public boolean moveDown(android.text.Spannable p0, android.text.Layout p1) { return false; }
    public boolean moveUp(android.text.Spannable p0, android.text.Layout p1) { return false; }
    public void removeSelection(android.text.Spannable p0) {}
    public void setSelection(android.text.Spannable p0, int p1) {}
    public void setSelection(android.text.Spannable p0, int p1, int p2) {}
}
