// @generated by gen-shims.py — do not edit by hand
package android.text;

public class SpannedString {
    public int length() { return 0; }
    public android.text.SpannedString valueOf(java.lang.CharSequence p0) { return null; }
}
