// @generated by gen-shims.py — do not edit by hand
package android.text;

public class Spanned {
    public int getSpanEnd(java.lang.Object p0) { return 0; }
    public int getSpanFlags(java.lang.Object p0) { return 0; }
    public int getSpanStart(java.lang.Object p0) { return 0; }
    public java.lang.Object[] getSpans(int p0, int p1, java.lang.Class p2) { return null; }
    public int length() { return 0; }
    public int nextSpanTransition(int p0, int p1, java.lang.Class p2) { return 0; }
}
