// @generated by gen-shims.py — do not edit by hand
package android.text;

public class SpannableString {
    public boolean equals(java.lang.Object p0) { return false; }
    public int getSpanEnd(java.lang.Object p0) { return 0; }
    public int getSpanStart(java.lang.Object p0) { return 0; }
    public java.lang.Object[] getSpans(int p0, int p1, java.lang.Class p2) { return null; }
    public int length() { return 0; }
    public void removeSpan(java.lang.Object p0) {}
    public void setSpan(java.lang.Object p0, int p1, int p2, int p3) {}
    public android.text.SpannableString valueOf(java.lang.CharSequence p0) { return null; }
}
