// @generated by gen-shims.py — do not edit by hand
package android.text;

public class SpanWatcher {
    public void onSpanAdded(android.text.Spannable p0, java.lang.Object p1, int p2, int p3) {}
    public void onSpanChanged(android.text.Spannable p0, java.lang.Object p1, int p2, int p3, int p4, int p5) {}
    public void onSpanRemoved(android.text.Spannable p0, java.lang.Object p1, int p2, int p3) {}
}
