// @generated by gen-shims.py — do not edit by hand
package android.text;

public class StaticLayout {
    public void draw(android.graphics.Canvas p0) {}
    public int getHeight() { return 0; }
    public int getLineAscent(int p0) { return 0; }
    public int getLineBaseline(int p0) { return 0; }
    public int getLineCount() { return 0; }
    public int getLineDescent(int p0) { return 0; }
    public int getLineEnd(int p0) { return 0; }
    public float getLineLeft(int p0) { return 0f; }
    public int getLineStart(int p0) { return 0; }
    public int getLineTop(int p0) { return 0; }
    public float getLineWidth(int p0) { return 0f; }
    public float getSpacingAdd() { return 0f; }
    public float getSpacingMultiplier() { return 0f; }
    public java.lang.CharSequence getText() { return null; }
    public int getWidth() { return 0; }
    public boolean isFallbackLineSpacingEnabled() { return false; }

    public static class Builder {
        public android.text.StaticLayout build() { return null; }
        public android.text.StaticLayout.Builder obtain(java.lang.CharSequence p0, int p1, int p2, android.text.TextPaint p3, int p4) { return null; }
        public android.text.StaticLayout.Builder setAlignment(android.text.Layout.Alignment p0) { return null; }
        public android.text.StaticLayout.Builder setBreakStrategy(int p0) { return null; }
        public android.text.StaticLayout.Builder setEllipsize(android.text.TextUtils.TruncateAt p0) { return null; }
        public android.text.StaticLayout.Builder setEllipsizedWidth(int p0) { return null; }
        public android.text.StaticLayout.Builder setHyphenationFrequency(int p0) { return null; }
        public android.text.StaticLayout.Builder setIncludePad(boolean p0) { return null; }
        public android.text.StaticLayout.Builder setIndents(int[] p0, int[] p1) { return null; }
        public android.text.StaticLayout.Builder setJustificationMode(int p0) { return null; }
        public android.text.StaticLayout.Builder setLineBreakConfig(android.graphics.text.LineBreakConfig p0) { return null; }
        public android.text.StaticLayout.Builder setLineSpacing(float p0, float p1) { return null; }
        public android.text.StaticLayout.Builder setMaxLines(int p0) { return null; }
        public android.text.StaticLayout.Builder setTextDirection(android.text.TextDirectionHeuristic p0) { return null; }
        public android.text.StaticLayout.Builder setUseBoundsForWidth(boolean p0) { return null; }
        public android.text.StaticLayout.Builder setUseLineSpacingFromFallbacks(boolean p0) { return null; }
    }
}
