// @generated by gen-shims.py — do not edit by hand
package android.text;

public class TextPaint {
    public float ascent() { return 0f; }
    public float descent() { return 0f; }
    public int getAlpha() { return 0; }
    public int getColor() { return 0; }
    public int getFlags() { return 0; }
    public java.lang.String getFontFeatureSettings() { return null; }
    public float getFontMetrics(android.graphics.Paint.FontMetrics p0) { return 0f; }
    public android.graphics.Paint.FontMetrics getFontMetrics() { return null; }
    public int getFontMetricsInt(android.graphics.Paint.FontMetricsInt p0) { return 0; }
    public android.graphics.Paint.FontMetricsInt getFontMetricsInt() { return null; }
    public java.lang.String getFontVariationSettings() { return null; }
    public float getLetterSpacing() { return 0f; }
    public android.graphics.Paint.Style getStyle() { return null; }
    public void getTextBounds(java.lang.String p0, int p1, int p2, android.graphics.Rect p3) {}
    public java.util.Locale getTextLocale() { return null; }
    public android.os.LocaleList getTextLocales() { return null; }
    public void getTextPath(java.lang.String p0, int p1, int p2, float p3, float p4, android.graphics.Path p5) {}
    public int getTextRunCursor(java.lang.CharSequence p0, int p1, int p2, boolean p3, int p4, int p5) { return 0; }
    public float getTextScaleX() { return 0f; }
    public float getTextSize() { return 0f; }
    public float getTextSkewX() { return 0f; }
    public android.graphics.Typeface getTypeface() { return null; }
    public int hashCode() { return 0; }
    public boolean isElegantTextHeight() { return false; }
    public float measureText(java.lang.CharSequence p0, int p1, int p2) { return 0f; }
    public float measureText(java.lang.String p0) { return 0f; }
    public void reset() {}
    public void set(android.graphics.Paint p0) {}
    public void setAlpha(int p0) {}
    public void setAntiAlias(boolean p0) {}
    public void setColor(int p0) {}
    public void setFakeBoldText(boolean p0) {}
    public void setFilterBitmap(boolean p0) {}
    public void setFlags(int p0) {}
    public boolean setFontVariationSettings(java.lang.String p0) { return false; }
    public void setLetterSpacing(float p0) {}
    public void setLinearText(boolean p0) {}
    public android.graphics.Shader setShader(android.graphics.Shader p0) { return null; }
    public void setShadowLayer(float p0, float p1, float p2, int p3) {}
    public void setStrokeWidth(float p0) {}
    public void setStyle(android.graphics.Paint.Style p0) {}
    public void setTextAlign(android.graphics.Paint.Align p0) {}
    public void setTextLocales(android.os.LocaleList p0) {}
    public void setTextSize(float p0) {}
    public void setTextSkewX(float p0) {}
    public android.graphics.Typeface setTypeface(android.graphics.Typeface p0) { return null; }
}
