// @generated by gen-shims.py — do not edit by hand
package android.text;

public class TextUtils {
    public java.lang.CharSequence concat(java.lang.CharSequence[] p0) { return null; }
    public void copySpansFrom(android.text.Spanned p0, int p1, int p2, java.lang.Class p3, android.text.Spannable p4, int p5) {}
    public java.lang.CharSequence ellipsize(java.lang.CharSequence p0, android.text.TextPaint p1, float p2, android.text.TextUtils.TruncateAt p3) { return null; }
    public java.lang.CharSequence ellipsize(java.lang.CharSequence p0, android.text.TextPaint p1, float p2, android.text.TextUtils.TruncateAt p3, boolean p4, android.text.TextUtils.EllipsizeCallback p5) { return null; }
    public boolean equals(java.lang.CharSequence p0, java.lang.CharSequence p1) { return false; }
    public java.lang.CharSequence expandTemplate(java.lang.CharSequence p0, java.lang.CharSequence[] p1) { return null; }
    public int getCapsMode(java.lang.CharSequence p0, int p1, int p2) { return 0; }
    public void getChars(java.lang.CharSequence p0, int p1, int p2, char[] p3, int p4) {}
    public int getLayoutDirectionFromLocale(java.util.Locale p0) { return 0; }
    public int getTrimmedLength(java.lang.CharSequence p0) { return 0; }
    public java.lang.String htmlEncode(java.lang.String p0) { return null; }
    public int indexOf(java.lang.CharSequence p0, char p1, int p2, int p3) { return 0; }
    public boolean isDigitsOnly(java.lang.CharSequence p0) { return false; }
    public boolean isEmpty(java.lang.CharSequence p0) { return false; }
    public boolean isGraphic(java.lang.CharSequence p0) { return false; }
    public java.lang.String join(java.lang.CharSequence p0, java.lang.Iterable p1) { return null; }
    public java.lang.String[] split(java.lang.String p0, java.lang.String p1) { return null; }
    public java.lang.String substring(java.lang.CharSequence p0, int p1, int p2) { return null; }
    public void writeToParcel(java.lang.CharSequence p0, android.os.Parcel p1, int p2) {}

    public interface EllipsizeCallback {
    }

    public static class TruncateAt {
        public int ordinal() { return 0; }
        public android.text.TextUtils.TruncateAt[] values() { return null; }
    }
}
