// @generated by gen-shims.py — do not edit by hand
package android.text;

public class TextDirectionHeuristic {
    public boolean isRtl(java.lang.CharSequence p0, int p1, int p2) { return false; }
}
