// @generated by gen-shims.py — do not edit by hand
package android.text;

public class TextWatcher {
    public void afterTextChanged(android.text.Editable p0) {}
    public void beforeTextChanged(java.lang.CharSequence p0, int p1, int p2, int p3) {}
    public void onTextChanged(java.lang.CharSequence p0, int p1, int p2, int p3) {}
}
