// @generated by gen-shims.py — do not edit by hand
package android.accounts;

public class AccountManager {
    public boolean addAccountExplicitly(android.accounts.Account p0, java.lang.String p1, android.os.Bundle p2) { return false; }
    public android.accounts.AccountManager get(android.content.Context p0) { return null; }
    public android.accounts.Account[] getAccounts() { return null; }
    public android.accounts.Account[] getAccountsByType(java.lang.String p0) { return null; }
    public android.accounts.AccountManagerFuture getAccountsByTypeAndFeatures(java.lang.String p0, java.lang.String[] p1, android.accounts.AccountManagerCallback p2, android.os.Handler p3) { return null; }
    public android.accounts.AccountManagerFuture getAuthToken(android.accounts.Account p0, java.lang.String p1, android.os.Bundle p2, boolean p3, android.accounts.AccountManagerCallback p4, android.os.Handler p5) { return null; }
    public android.accounts.AccountManagerFuture getAuthTokenByFeatures(java.lang.String p0, java.lang.String p1, java.lang.String[] p2, android.app.Activity p3, android.os.Bundle p4, android.os.Bundle p5, android.accounts.AccountManagerCallback p6, android.os.Handler p7) { return null; }
    public java.lang.String getPassword(android.accounts.Account p0) { return null; }
    public java.lang.String getUserData(android.accounts.Account p0, java.lang.String p1) { return null; }
    public void invalidateAuthToken(java.lang.String p0, java.lang.String p1) {}
    public android.content.Intent newChooseAccountIntent(android.accounts.Account p0, java.util.List p1, java.lang.String[] p2, java.lang.String p3, java.lang.String p4, java.lang.String[] p5, android.os.Bundle p6) { return null; }
    public java.lang.String peekAuthToken(android.accounts.Account p0, java.lang.String p1) { return null; }
    public android.accounts.AccountManagerFuture removeAccount(android.accounts.Account p0, android.accounts.AccountManagerCallback p1, android.os.Handler p2) { return null; }
    public boolean removeAccountExplicitly(android.accounts.Account p0) { return false; }
    public void setPassword(android.accounts.Account p0, java.lang.String p1) {}
    public void setUserData(android.accounts.Account p0, java.lang.String p1, java.lang.String p2) {}
}
