// @generated by gen-shims.py — do not edit by hand
package android.accounts;

public class Account {
    public boolean equals(java.lang.Object p0) { return false; }
    public int hashCode() { return 0; }
}
