// @generated by gen-shims.py — do not edit by hand
package android.accounts;

public class AccountAuthenticatorResponse {
    public void onError(int p0, java.lang.String p1) {}
    public void onResult(android.os.Bundle p0) {}
}
