// @generated by gen-shims.py — do not edit by hand
package android.print.pdf;

public class PrintedPdfDocument {
    public void close() {}
    public void finishPage(android.graphics.pdf.PdfDocument.Page p0) {}
    public android.graphics.pdf.PdfDocument.Page startPage(int p0) { return null; }
    public void writeTo(java.io.OutputStream p0) {}
}
