// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class BidirectionalStream {
    public void cancel() {}
    public void flush() {}
    public boolean isDone() { return false; }
    public void read(java.nio.ByteBuffer p0) {}
    public void start() {}
    public void write(java.nio.ByteBuffer p0, boolean p1) {}

    public static class Builder {
        public android.net.http.BidirectionalStream.Builder addHeader(java.lang.String p0, java.lang.String p1) { return null; }
        public android.net.http.BidirectionalStream build() { return null; }
        public android.net.http.BidirectionalStream.Builder setDelayRequestHeadersUntilFirstFlushEnabled(boolean p0) { return null; }
        public android.net.http.BidirectionalStream.Builder setHttpMethod(java.lang.String p0) { return null; }
        public android.net.http.BidirectionalStream.Builder setPriority(int p0) { return null; }
        public android.net.http.BidirectionalStream.Builder setTrafficStatsTag(int p0) { return null; }
        public android.net.http.BidirectionalStream.Builder setTrafficStatsUid(int p0) { return null; }
    }

    public interface Callback {
    }
}
