// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class ConnectionMigrationOptions {

    public static class Builder {
        public android.net.http.ConnectionMigrationOptions build() { return null; }
        public android.net.http.ConnectionMigrationOptions.Builder setAllowNonDefaultNetworkUsage(int p0) { return null; }
        public android.net.http.ConnectionMigrationOptions.Builder setDefaultNetworkMigration(int p0) { return null; }
        public android.net.http.ConnectionMigrationOptions.Builder setPathDegradationMigration(int p0) { return null; }
    }
}
