// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class DnsOptions {

    public static class Builder {
        public android.net.http.DnsOptions.StaleDnsOptions build() { return null; }
        public Object setAllowCrossNetworkUsage(int p0) { return null; }
        public Object setFreshLookupTimeout(java.time.Duration p0) { return null; }
        public Object setMaxExpiredDelay(java.time.Duration p0) { return null; }
        public Object setUseStaleOnNameNotResolved(int p0) { return null; }
    }

    public static class StaleDnsOptions {
    }
}
