// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class HeaderBlock {
    public java.util.List getAsList() { return null; }
    public java.util.Map getAsMap() { return null; }
}
