// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class HttpResponseCache {
    public void close() {}
    public android.net.http.HttpResponseCache getInstalled() { return null; }
    public android.net.http.HttpResponseCache install(java.io.File p0, long p1) { return null; }
}
