// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class HttpEngine {
    public void bindToNetwork(android.net.Network p0) {}
    public java.net.URLStreamHandlerFactory createUrlStreamHandlerFactory() { return null; }
    public java.lang.String getVersionString() { return null; }
    public android.net.http.BidirectionalStream.Builder newBidirectionalStreamBuilder(java.lang.String p0, java.util.concurrent.Executor p1, android.net.http.BidirectionalStream.Callback p2) { return null; }
    public android.net.http.UrlRequest.Builder newUrlRequestBuilder(java.lang.String p0, java.util.concurrent.Executor p1, android.net.http.UrlRequest.Callback p2) { return null; }
    public java.net.URLConnection openConnection(java.net.URL p0) { return null; }
    public void shutdown() {}

    public static class Builder {
        public android.net.http.HttpEngine.Builder addPublicKeyPins(java.lang.String p0, java.util.Set p1, boolean p2, java.time.Instant p3) { return null; }
        public android.net.http.HttpEngine.Builder addQuicHint(java.lang.String p0, int p1, int p2) { return null; }
        public android.net.http.HttpEngine build() { return null; }
        public java.lang.String getDefaultUserAgent() { return null; }
        public android.net.http.HttpEngine.Builder setConnectionMigrationOptions(android.net.http.ConnectionMigrationOptions p0) { return null; }
        public android.net.http.HttpEngine.Builder setDnsOptions(android.net.http.DnsOptions p0) { return null; }
        public android.net.http.HttpEngine.Builder setEnableBrotli(boolean p0) { return null; }
        public android.net.http.HttpEngine.Builder setEnableHttp2(boolean p0) { return null; }
        public android.net.http.HttpEngine.Builder setEnableHttpCache(int p0, long p1) { return null; }
        public android.net.http.HttpEngine.Builder setEnablePublicKeyPinningBypassForLocalTrustAnchors(boolean p0) { return null; }
        public android.net.http.HttpEngine.Builder setEnableQuic(boolean p0) { return null; }
        public android.net.http.HttpEngine.Builder setQuicOptions(android.net.http.QuicOptions p0) { return null; }
        public android.net.http.HttpEngine.Builder setStoragePath(java.lang.String p0) { return null; }
        public android.net.http.HttpEngine.Builder setUserAgent(java.lang.String p0) { return null; }
    }
}
