// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class NetworkException {
    public int getErrorCode() { return 0; }
    public java.lang.String getMessage() { return null; }
    public boolean isImmediatelyRetryable() { return false; }
}
