// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class QuicOptions {

    public static class Builder {
        public android.net.http.QuicOptions.Builder addAllowedQuicHost(java.lang.String p0) { return null; }
        public android.net.http.QuicOptions build() { return null; }
        public android.net.http.QuicOptions.Builder setHandshakeUserAgent(java.lang.String p0) { return null; }
        public android.net.http.QuicOptions.Builder setIdleConnectionTimeout(java.time.Duration p0) { return null; }
        public android.net.http.QuicOptions.Builder setInMemoryServerConfigsCacheSize(int p0) { return null; }
    }
}
