// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class SslError {
    public int getPrimaryError() { return 0; }
    public java.lang.String getUrl() { return null; }
}
