// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class UploadDataSink {
    public void onReadError(java.lang.Exception p0) {}
    public void onReadSucceeded(boolean p0) {}
    public void onRewindError(java.lang.Exception p0) {}
    public void onRewindSucceeded() {}
}
