// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class UrlRequest {
    public void cancel() {}
    public void followRedirect() {}
    public void getStatus(android.net.http.UrlRequest.StatusListener p0) {}
    public boolean isDone() { return false; }
    public void read(java.nio.ByteBuffer p0) {}
    public void start() {}

    public static class Builder {
        public android.net.http.UrlRequest.Builder addHeader(java.lang.String p0, java.lang.String p1) { return null; }
        public android.net.http.UrlRequest.Builder bindToNetwork(android.net.Network p0) { return null; }
        public android.net.http.UrlRequest build() { return null; }
        public android.net.http.UrlRequest.Builder setCacheDisabled(boolean p0) { return null; }
        public android.net.http.UrlRequest.Builder setDirectExecutorAllowed(boolean p0) { return null; }
        public android.net.http.UrlRequest.Builder setHttpMethod(java.lang.String p0) { return null; }
        public android.net.http.UrlRequest.Builder setPriority(int p0) { return null; }
        public android.net.http.UrlRequest.Builder setTrafficStatsTag(int p0) { return null; }
        public android.net.http.UrlRequest.Builder setUploadDataProvider(android.net.http.UploadDataProvider p0, java.util.concurrent.Executor p1) { return null; }
    }

    public interface Callback {
    }

    public interface StatusListener {
    }
}
