// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class UrlResponseInfo {
    public android.net.http.HeaderBlock getHeaders() { return null; }
    public int getHttpStatusCode() { return 0; }
    public java.lang.String getHttpStatusText() { return null; }
    public java.lang.String getNegotiatedProtocol() { return null; }
    public long getReceivedByteCount() { return 0; }
    public java.lang.String getUrl() { return null; }
    public java.util.List getUrlChain() { return null; }
    public boolean wasCached() { return false; }
}
