// @generated by gen-shims.py — do not edit by hand
package android.net.http;

public class X509TrustManagerExtensions {
    public java.util.List checkServerTrusted(java.security.cert.X509Certificate[] p0, java.lang.String p1, java.lang.String p2) { return null; }
    public java.util.List checkServerTrusted(java.security.cert.X509Certificate[] p0, byte[] p1, byte[] p2, java.lang.String p3, java.lang.String p4) { return null; }
}
