// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class ActivityInfo {
    public int getIconResource() { return 0; }
    public android.content.res.XmlResourceParser loadXmlMetaData(android.content.pm.PackageManager p0, java.lang.String p1) { return null; }
}
