// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class ApplicationInfo {
    public boolean isResourceOverlay() { return false; }
    public android.graphics.drawable.Drawable loadIcon(android.content.pm.PackageManager p0) { return null; }
    public java.lang.CharSequence loadLabel(android.content.pm.PackageManager p0) { return null; }
}
