// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class InstallSourceInfo {
    public java.lang.String getInitiatingPackageName() { return null; }
    public java.lang.String getInstallingPackageName() { return null; }
    public java.lang.String getUpdateOwnerPackageName() { return null; }
}
