// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class IPackageInstaller {
    public void abandonSession(int p0) {}
    public android.os.IBinder asBinder() { return null; }
    public android.content.pm.IPackageInstallerSession openSession(int p0) { return null; }

    public static class Stub {
        public android.content.pm.IPackageInstaller asInterface(android.os.IBinder p0) { return null; }
    }
}
