// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class IPackageInstallerSession {
    public android.os.IBinder asBinder() { return null; }

    public static class Stub {
        public android.content.pm.IPackageInstallerSession asInterface(android.os.IBinder p0) { return null; }
    }
}
