// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class PackageInstaller {
    public void abandonSession(int p0) {}
    public void commitSessionAfterInstallConstraintsAreMet(int p0, android.content.IntentSender p1, android.content.pm.PackageInstaller.InstallConstraints p2, long p3) {}
    public int createSession(android.content.pm.PackageInstaller.SessionParams p0) { return 0; }
    public java.util.List getAllSessions() { return null; }
    public java.util.List getMySessions() { return null; }
    public android.content.pm.PackageInstaller.SessionInfo getSessionInfo(int p0) { return null; }
    public android.content.pm.PackageInstaller.Session openSession(int p0) { return null; }
    public void registerSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0) {}
    public void registerSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0, android.os.Handler p1) {}
    public void uninstall(java.lang.String p0, android.content.IntentSender p1) {}
    public void unregisterSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0) {}

    public static class InstallConstraints {
    }

    public static class Session {
        public void abandon() {}
        public void close() {}
        public void commit(android.content.IntentSender p0) {}
        public void fsync(java.io.OutputStream p0) {}
        public java.io.OutputStream openWrite(java.lang.String p0, long p1, long p2) { return null; }
    }

    public interface SessionCallback {
    }

    public static class SessionInfo {
        public java.lang.String getAppPackageName() { return null; }
        public java.lang.String getInstallerPackageName() { return null; }
        public int getSessionId() { return 0; }
    }

    public static class SessionParams {
        public void setAppPackageName(java.lang.String p0) {}
        public void setApplicationEnabledSettingPersistent() {}
        public void setInstallLocation(int p0) {}
        public void setInstallReason(int p0) {}
        public void setInstallerPackageName(java.lang.String p0) {}
        public void setOriginatingUid(int p0) {}
        public void setPackageSource(int p0) {}
        public void setRequestUpdateOwnership(boolean p0) {}
        public void setRequireUserAction(int p0) {}
        public void setSize(long p0) {}
        public void setUnarchiveId(int p0) {}
    }
}
