// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class PermissionGroupInfo {
    public java.lang.CharSequence loadLabel(android.content.pm.PackageManager p0) { return null; }
}
