// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class PermissionInfo {
    public int getProtection() { return 0; }
    public int getProtectionFlags() { return 0; }
    public java.lang.CharSequence loadDescription(android.content.pm.PackageManager p0) { return null; }
    public java.lang.CharSequence loadLabel(android.content.pm.PackageManager p0) { return null; }
}
