// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class ResolveInfo {
    public android.graphics.drawable.Drawable loadIcon(android.content.pm.PackageManager p0) { return null; }
    public java.lang.CharSequence loadLabel(android.content.pm.PackageManager p0) { return null; }
    public java.lang.String toString() { return null; }
}
