// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class SharedLibraryInfo {
    public long getLongVersion() { return 0; }
    public java.lang.String getName() { return null; }
    public int getVersion() { return 0; }
}
