// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class ShortcutInfo {
    public android.content.ComponentName getActivity() { return null; }
    public java.util.Set getCategories() { return null; }
    public java.lang.CharSequence getDisabledMessage() { return null; }
    public int getDisabledReason() { return 0; }
    public android.os.PersistableBundle getExtras() { return null; }
    public java.lang.String getId() { return null; }
    public android.content.Intent[] getIntents() { return null; }
    public long getLastChangedTimestamp() { return 0; }
    public android.content.LocusId getLocusId() { return null; }
    public java.lang.CharSequence getLongLabel() { return null; }
    public java.lang.String getPackage() { return null; }
    public int getRank() { return 0; }
    public java.lang.CharSequence getShortLabel() { return null; }
    public android.os.UserHandle getUserHandle() { return null; }
    public boolean hasKeyFieldsOnly() { return false; }
    public boolean isCached() { return false; }
    public boolean isDeclaredInManifest() { return false; }
    public boolean isDynamic() { return false; }
    public boolean isEnabled() { return false; }
    public boolean isImmutable() { return false; }
    public boolean isPinned() { return false; }

    public static class Builder {
        public android.content.pm.ShortcutInfo build() { return null; }
        public android.content.pm.ShortcutInfo.Builder setActivity(android.content.ComponentName p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setCategories(java.util.Set p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setDisabledMessage(java.lang.CharSequence p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setExcludedFromSurfaces(int p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setExtras(android.os.PersistableBundle p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setIcon(android.graphics.drawable.Icon p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setIntent(android.content.Intent p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setIntents(android.content.Intent[] p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setLocusId(android.content.LocusId p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setLongLabel(java.lang.CharSequence p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setLongLived(boolean p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setPersons(android.app.Person[] p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setRank(int p0) { return null; }
        public android.content.pm.ShortcutInfo.Builder setShortLabel(java.lang.CharSequence p0) { return null; }
    }
}
