// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class ShortcutManager {
    public boolean addDynamicShortcuts(java.util.List p0) { return false; }
    public android.content.Intent createShortcutResultIntent(android.content.pm.ShortcutInfo p0) { return null; }
    public void disableShortcuts(java.util.List p0, java.lang.CharSequence p1) {}
    public void enableShortcuts(java.util.List p0) {}
    public java.util.List getDynamicShortcuts() { return null; }
    public int getIconMaxHeight() { return 0; }
    public int getIconMaxWidth() { return 0; }
    public java.util.List getManifestShortcuts() { return null; }
    public int getMaxShortcutCountPerActivity() { return 0; }
    public java.util.List getPinnedShortcuts() { return null; }
    public java.util.List getShortcuts(int p0) { return null; }
    public boolean isRateLimitingActive() { return false; }
    public boolean isRequestPinShortcutSupported() { return false; }
    public void pushDynamicShortcut(android.content.pm.ShortcutInfo p0) {}
    public void removeAllDynamicShortcuts() {}
    public void removeDynamicShortcuts(java.util.List p0) {}
    public void removeLongLivedShortcuts(java.util.List p0) {}
    public void reportShortcutUsed(java.lang.String p0) {}
    public boolean requestPinShortcut(android.content.pm.ShortcutInfo p0, android.content.IntentSender p1) { return false; }
    public boolean setDynamicShortcuts(java.util.List p0) { return false; }
    public boolean updateShortcuts(java.util.List p0) { return false; }
}
