// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class SigningInfo {
    public android.content.pm.Signature[] getApkContentsSigners() { return null; }
    public android.content.pm.Signature[] getSigningCertificateHistory() { return null; }
    public boolean hasMultipleSigners() { return false; }
    public boolean hasPastSigningCertificates() { return false; }
}
