// @generated by gen-shims.py — do not edit by hand
package android.content.pm;

public class Signature {
    public boolean equals(java.lang.Object p0) { return false; }
    public byte[] toByteArray() { return null; }
    public java.lang.String toCharsString() { return null; }
}
