// @generated by gen-shims.py — do not edit by hand
package android.gesture;

public class GestureOverlayView {
    public void addOnGesturePerformedListener(android.gesture.GestureOverlayView.OnGesturePerformedListener p0) {}
    public void setEnabled(boolean p0) {}

    public interface OnGesturePerformedListener {
    }
}
