// @generated by gen-shims.py — do not edit by hand
package android.gesture;

public class GestureLibrary {
    public java.util.Set getGestureEntries() { return null; }
    public java.util.ArrayList getGestures(java.lang.String p0) { return null; }
    public boolean load() { return false; }
    public java.util.ArrayList recognize(android.gesture.Gesture p0) { return null; }
}
