// @generated by gen-shims.py — do not edit by hand
package android.gesture;

public class GestureLibraries {
    public android.gesture.GestureLibrary fromRawResource(android.content.Context p0, int p1) { return null; }
}
