// @generated by gen-shims.py — do not edit by hand
package android.window;

public class BackEvent {
    public long getFrameTimeMillis() { return 0; }
    public float getProgress() { return 0f; }
    public int getSwipeEdge() { return 0; }
    public float getTouchX() { return 0f; }
    public float getTouchY() { return 0f; }
}
