// @generated by gen-shims.py — do not edit by hand
package android.window;

public class SplashScreen {
    public void setOnExitAnimationListener(android.window.SplashScreen.OnExitAnimationListener p0) {}

    public interface OnExitAnimationListener {
    }
}
