// @generated by gen-shims.py — do not edit by hand
package android.security.keystore;

public class KeyGenParameterSpec {
    public java.lang.String[] getBlockModes() { return null; }
    public java.lang.String[] getEncryptionPaddings() { return null; }
    public int getKeySize() { return 0; }
    public java.lang.String getKeystoreAlias() { return null; }
    public int getPurposes() { return 0; }
    public int getUserAuthenticationValidityDurationSeconds() { return 0; }
    public boolean isUserAuthenticationRequired() { return false; }

    public static class Builder {
        public android.security.keystore.KeyGenParameterSpec build() { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setBlockModes(java.lang.String[] p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setCertificateNotAfter(java.util.Date p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setCertificateNotBefore(java.util.Date p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setCertificateSerialNumber(java.math.BigInteger p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setCertificateSubject(javax.security.auth.x500.X500Principal p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setDigests(java.lang.String[] p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setEncryptionPaddings(java.lang.String[] p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setInvalidatedByBiometricEnrollment(boolean p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setIsStrongBoxBacked(boolean p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setKeySize(int p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setRandomizedEncryptionRequired(boolean p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setUnlockedDeviceRequired(boolean p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setUserAuthenticationParameters(int p0, int p1) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setUserAuthenticationRequired(boolean p0) { return null; }
        public android.security.keystore.KeyGenParameterSpec.Builder setUserAuthenticationValidityDurationSeconds(int p0) { return null; }
    }
}
