// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class AnimationDrawable {
    public void addFrame(android.graphics.drawable.Drawable p0, int p1) {}
    public int getDuration(int p0) { return 0; }
    public android.graphics.drawable.Drawable getFrame(int p0) { return null; }
    public int getNumberOfFrames() { return 0; }
    public boolean isOneShot() { return false; }
    public boolean setLevel(int p0) { return false; }
    public void setOneShot(boolean p0) {}
    public void start() {}
    public void stop() {}
}
