// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class AnimatedStateListDrawable {
    public void addTransition(int p0, int p1, android.graphics.drawable.Drawable p2, boolean p3) {}
}
