// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class AnimatedImageDrawable {
    public void clearAnimationCallbacks() {}
    public int getIntrinsicHeight() { return 0; }
    public int getIntrinsicWidth() { return 0; }
    public void registerAnimationCallback(android.graphics.drawable.Animatable2.AnimationCallback p0) {}
    public void setRepeatCount(int p0) {}
    public void stop() {}
}
