// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class AnimatedVectorDrawable {
    public void clearAnimationCallbacks() {}
    public boolean isRunning() { return false; }
    public void registerAnimationCallback(android.graphics.drawable.Animatable2.AnimationCallback p0) {}
    public void start() {}
    public void stop() {}
    public boolean unregisterAnimationCallback(android.graphics.drawable.Animatable2.AnimationCallback p0) { return false; }
}
