// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class Animatable {
    public boolean isRunning() { return false; }
    public void start() {}
    public void stop() {}
}
