// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class BitmapDrawable {
    public void draw(android.graphics.Canvas p0) {}
    public android.graphics.Bitmap getBitmap() { return null; }
    public android.graphics.Paint getPaint() { return null; }
    public void invalidateSelf() {}
    public void onBoundsChange(android.graphics.Rect p0) {}
    public void setAlpha(int p0) {}
    public void setBounds(int p0, int p1, int p2, int p3) {}
    public void setColorFilter(android.graphics.ColorFilter p0) {}
    public void setTargetDensity(int p0) {}
    public void setTileModeX(android.graphics.Shader.TileMode p0) {}
    public void setTileModeXY(android.graphics.Shader.TileMode p0, android.graphics.Shader.TileMode p1) {}
}
