// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class ColorDrawable {
    public void draw(android.graphics.Canvas p0) {}
    public int getColor() { return 0; }
    public void setColor(int p0) {}
}
