// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class ColorStateListDrawable {
    public android.content.res.ColorStateList getColorStateList() { return null; }
}
