// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class DrawableContainer {
    public android.graphics.drawable.Drawable.ConstantState getConstantState() { return null; }

    public static class DrawableContainerState {
        public android.graphics.drawable.Drawable getChild(int p0) { return null; }
        public int getChildCount() { return 0; }
        public android.graphics.drawable.Drawable[] getChildren() { return null; }
    }
}
