// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class DrawableWrapper {
    public android.graphics.drawable.Drawable getDrawable() { return null; }
    public void setDrawable(android.graphics.drawable.Drawable p0) {}
}
