// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class Drawable {
    public void applyTheme(android.content.res.Resources.Theme p0) {}
    public boolean canApplyTheme() { return false; }
    public void clearColorFilter() {}
    public void copyBounds(android.graphics.Rect p0) {}
    public android.graphics.drawable.Drawable createFromStream(java.io.InputStream p0, java.lang.String p1) { return null; }
    public android.graphics.drawable.Drawable createFromXmlInner(android.content.res.Resources p0, org.xmlpull.v1.XmlPullParser p1, android.util.AttributeSet p2) { return null; }
    public android.graphics.drawable.Drawable createFromXmlInner(android.content.res.Resources p0, org.xmlpull.v1.XmlPullParser p1, android.util.AttributeSet p2, android.content.res.Resources.Theme p3) { return null; }
    public void draw(android.graphics.Canvas p0) {}
    public int getAlpha() { return 0; }
    public android.graphics.Rect getBounds() { return null; }
    public android.graphics.drawable.Drawable.Callback getCallback() { return null; }
    public int getChangingConfigurations() { return 0; }
    public android.graphics.ColorFilter getColorFilter() { return null; }
    public android.graphics.drawable.Drawable.ConstantState getConstantState() { return null; }
    public android.graphics.drawable.Drawable getCurrent() { return null; }
    public android.graphics.Rect getDirtyBounds() { return null; }
    public void getHotspotBounds(android.graphics.Rect p0) {}
    public int getIntrinsicHeight() { return 0; }
    public int getIntrinsicWidth() { return 0; }
    public int getLayoutDirection() { return 0; }
    public int getLevel() { return 0; }
    public int getMinimumHeight() { return 0; }
    public int getMinimumWidth() { return 0; }
    public int getOpacity() { return 0; }
    public android.graphics.Insets getOpticalInsets() { return null; }
    public void getOutline(android.graphics.Outline p0) {}
    public boolean getPadding(android.graphics.Rect p0) { return false; }
    public int[] getState() { return null; }
    public android.graphics.Region getTransparentRegion() { return null; }
    public int hashCode() { return 0; }
    public void inflate(android.content.res.Resources p0, org.xmlpull.v1.XmlPullParser p1, android.util.AttributeSet p2) {}
    public void inflate(android.content.res.Resources p0, org.xmlpull.v1.XmlPullParser p1, android.util.AttributeSet p2, android.content.res.Resources.Theme p3) {}
    public void invalidateSelf() {}
    public boolean isAutoMirrored() { return false; }
    public boolean isStateful() { return false; }
    public boolean isVisible() { return false; }
    public void jumpToCurrentState() {}
    public android.graphics.drawable.Drawable mutate() { return null; }
    public void onBoundsChange(android.graphics.Rect p0) {}
    public boolean onLayoutDirectionChanged(int p0) { return false; }
    public boolean onLevelChange(int p0) { return false; }
    public boolean onStateChange(int[] p0) { return false; }
    public int resolveOpacity(int p0, int p1) { return 0; }
    public void scheduleSelf(java.lang.Runnable p0, long p1) {}
    public void setAlpha(int p0) {}
    public void setAutoMirrored(boolean p0) {}
    public void setBounds(int p0, int p1, int p2, int p3) {}
    public void setBounds(android.graphics.Rect p0) {}
    public void setCallback(android.graphics.drawable.Drawable.Callback p0) {}
    public void setChangingConfigurations(int p0) {}
    public void setColorFilter(android.graphics.ColorFilter p0) {}
    public void setColorFilter(int p0, android.graphics.PorterDuff.Mode p1) {}
    public void setDither(boolean p0) {}
    public void setFilterBitmap(boolean p0) {}
    public void setHotspot(float p0, float p1) {}
    public void setHotspotBounds(int p0, int p1, int p2, int p3) {}
    public boolean setLayoutDirection(int p0) { return false; }
    public boolean setLevel(int p0) { return false; }
    public boolean setState(int[] p0) { return false; }
    public void setTint(int p0) {}
    public void setTintBlendMode(android.graphics.BlendMode p0) {}
    public void setTintList(android.content.res.ColorStateList p0) {}
    public void setTintMode(android.graphics.PorterDuff.Mode p0) {}
    public boolean setVisible(boolean p0, boolean p1) { return false; }
    public void unscheduleSelf(java.lang.Runnable p0) {}

    public interface Callback {
        void invalidateDrawable(android.graphics.drawable.Drawable p0);
        void scheduleDrawable(android.graphics.drawable.Drawable p0, java.lang.Runnable p1, long p2);
        void unscheduleDrawable(android.graphics.drawable.Drawable p0, java.lang.Runnable p1);
    }

    public static class ConstantState {
        public boolean canApplyTheme() { return false; }
        public int getChangingConfigurations() { return 0; }
        public android.graphics.drawable.Drawable newDrawable() { return null; }
        public android.graphics.drawable.Drawable newDrawable(android.content.res.Resources p0) { return null; }
        public android.graphics.drawable.Drawable newDrawable(android.content.res.Resources p0, android.content.res.Resources.Theme p1) { return null; }
    }
}
