// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class GradientDrawable {
    public android.graphics.drawable.Drawable.ConstantState getConstantState() { return null; }
    public void setAlpha(int p0) {}
    public void setColor(int p0) {}
    public void setColors(int[] p0) {}
    public void setCornerRadius(float p0) {}
    public void setOrientation(android.graphics.drawable.GradientDrawable.Orientation p0) {}
    public void setShape(int p0) {}
    public void setStroke(int p0, int p1) {}

    public static class Orientation {
    }
}
