// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class Icon {
    public android.graphics.drawable.Icon createWithAdaptiveBitmap(android.graphics.Bitmap p0) { return null; }
    public android.graphics.drawable.Icon createWithAdaptiveBitmapContentUri(android.net.Uri p0) { return null; }
    public android.graphics.drawable.Icon createWithBitmap(android.graphics.Bitmap p0) { return null; }
    public android.graphics.drawable.Icon createWithContentUri(android.net.Uri p0) { return null; }
    public android.graphics.drawable.Icon createWithData(byte[] p0, int p1, int p2) { return null; }
    public android.graphics.drawable.Icon createWithResource(android.content.Context p0, int p1) { return null; }
    public int getResId() { return 0; }
    public java.lang.String getResPackage() { return null; }
    public int getType() { return 0; }
    public android.net.Uri getUri() { return null; }
    public int hashCode() { return 0; }
    public android.graphics.drawable.Drawable loadDrawable(android.content.Context p0) { return null; }
    public android.graphics.drawable.Icon setTintBlendMode(android.graphics.BlendMode p0) { return null; }
    public android.graphics.drawable.Icon setTintList(android.content.res.ColorStateList p0) { return null; }
    public android.graphics.drawable.Icon setTintMode(android.graphics.PorterDuff.Mode p0) { return null; }
}
