// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class InsetDrawable {
    public void draw(android.graphics.Canvas p0) {}
    public android.graphics.drawable.Drawable getDrawable() { return null; }
    public boolean getPadding(android.graphics.Rect p0) { return false; }
    public void setDrawable(android.graphics.drawable.Drawable p0) {}
}
