// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class LayerDrawable {
    public android.graphics.drawable.Drawable findDrawableByLayerId(int p0) { return null; }
    public android.graphics.drawable.Drawable getDrawable(int p0) { return null; }
    public int getId(int p0) { return 0; }
    public int getLayerGravity(int p0) { return 0; }
    public int getLayerHeight(int p0) { return 0; }
    public int getLayerInsetBottom(int p0) { return 0; }
    public int getLayerInsetEnd(int p0) { return 0; }
    public int getLayerInsetLeft(int p0) { return 0; }
    public int getLayerInsetRight(int p0) { return 0; }
    public int getLayerInsetStart(int p0) { return 0; }
    public int getLayerInsetTop(int p0) { return 0; }
    public int getLayerWidth(int p0) { return 0; }
    public int getNumberOfLayers() { return 0; }
    public void invalidateDrawable(android.graphics.drawable.Drawable p0) {}
    public android.graphics.drawable.Drawable mutate() { return null; }
    public boolean onStateChange(int[] p0) { return false; }
    public void setColorFilter(int p0, android.graphics.PorterDuff.Mode p1) {}
    public boolean setDrawableByLayerId(int p0, android.graphics.drawable.Drawable p1) { return false; }
    public void setId(int p0, int p1) {}
    public void setLayerGravity(int p0, int p1) {}
    public void setLayerHeight(int p0, int p1) {}
    public void setLayerInset(int p0, int p1, int p2, int p3, int p4) {}
    public void setLayerInsetBottom(int p0, int p1) {}
    public void setLayerInsetEnd(int p0, int p1) {}
    public void setLayerInsetLeft(int p0, int p1) {}
    public void setLayerInsetRight(int p0, int p1) {}
    public void setLayerInsetStart(int p0, int p1) {}
    public void setLayerInsetTop(int p0, int p1) {}
    public void setLayerSize(int p0, int p1, int p2) {}
    public void setLayerWidth(int p0, int p1) {}
}
