// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class RippleDrawable {
    public android.graphics.drawable.Drawable.ConstantState getConstantState() { return null; }
    public android.graphics.Rect getDirtyBounds() { return null; }
    public int getRadius() { return 0; }
    public void setColor(android.content.res.ColorStateList p0) {}
    public void setRadius(int p0) {}
}
