// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class ShapeDrawable {
    public android.graphics.Paint getPaint() { return null; }
    public void setShaderFactory(android.graphics.drawable.ShapeDrawable.ShaderFactory p0) {}
    public void setShape(android.graphics.drawable.shapes.Shape p0) {}
    public void setTint(int p0) {}

    public static class ShaderFactory {
    }
}
