// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class StateListDrawable {
    public void addState(int[] p0, android.graphics.drawable.Drawable p1) {}
    public void draw(android.graphics.Canvas p0) {}
    public int getIntrinsicWidth() { return 0; }
    public void jumpToCurrentState() {}
    public boolean onStateChange(int[] p0) { return false; }
    public void setAlpha(int p0) {}
    public void setBounds(int p0, int p1, int p2, int p3) {}
    public void setColorFilter(int p0, android.graphics.PorterDuff.Mode p1) {}
    public void setEnterFadeDuration(int p0) {}
    public void setExitFadeDuration(int p0) {}
    public boolean setState(int[] p0) { return false; }
}
