// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable;

public class VectorDrawable {
    public void draw(android.graphics.Canvas p0) {}
    public int getIntrinsicHeight() { return 0; }
    public int getIntrinsicWidth() { return 0; }
}
