// @generated by gen-shims.py — do not edit by hand
package android.provider;

public class ContactsContract {

    public static class Contacts {
        public android.net.Uri getLookupUri(long p0, java.lang.String p1) { return null; }
        public android.net.Uri lookupContact(android.content.ContentResolver p0, android.net.Uri p1) { return null; }
        public java.io.InputStream openContactPhotoInputStream(android.content.ContentResolver p0, android.net.Uri p1, boolean p2) { return null; }
        public java.io.InputStream openContactPhotoInputStream(android.content.ContentResolver p0, android.net.Uri p1) { return null; }
    }

    public static class Data {
    }

    public static class Email {
    }

    public static class Groups {
    }

    public static class Phone {
    }

    public static class QuickContact {
        public void showQuickContact(android.content.Context p0, android.view.View p1, android.net.Uri p2, int p3, java.lang.String[] p4) {}
    }

    public static class RawContacts {
    }

    public static class Settings {
    }

    public static class StructuredPostal {
    }
}
