// @generated by gen-shims.py — do not edit by hand
package android.provider;

public class DocumentsContract {
    public android.net.Uri buildChildDocumentsUri(java.lang.String p0, java.lang.String p1) { return null; }
    public android.net.Uri buildChildDocumentsUriUsingTree(android.net.Uri p0, java.lang.String p1) { return null; }
    public android.net.Uri buildDocumentUri(java.lang.String p0, java.lang.String p1) { return null; }
    public android.net.Uri buildDocumentUriUsingTree(android.net.Uri p0, java.lang.String p1) { return null; }
    public android.net.Uri buildRootUri(java.lang.String p0, java.lang.String p1) { return null; }
    public android.net.Uri buildTreeDocumentUri(java.lang.String p0, java.lang.String p1) { return null; }
    public android.net.Uri createDocument(android.content.ContentResolver p0, android.net.Uri p1, java.lang.String p2, java.lang.String p3) { return null; }
    public boolean deleteDocument(android.content.ContentResolver p0, android.net.Uri p1) { return false; }
    public java.lang.String getDocumentId(android.net.Uri p0) { return null; }
    public java.lang.String getTreeDocumentId(android.net.Uri p0) { return null; }
    public boolean isDocumentUri(android.content.Context p0, android.net.Uri p1) { return false; }
    public boolean isTreeUri(android.net.Uri p0) { return false; }
    public boolean removeDocument(android.content.ContentResolver p0, android.net.Uri p1, android.net.Uri p2) { return false; }
    public android.net.Uri renameDocument(android.content.ContentResolver p0, android.net.Uri p1, java.lang.String p2) { return null; }
}
