// @generated by gen-shims.py — do not edit by hand
package android.provider;

public class MediaStore {
    public boolean canManageMedia(android.content.Context p0) { return false; }
    public android.app.PendingIntent createDeleteRequest(android.content.ContentResolver p0, java.util.Collection p1) { return null; }
    public android.app.PendingIntent createWriteRequest(android.content.ContentResolver p0, java.util.Collection p1) { return null; }
    public java.util.Set getExternalVolumeNames(android.content.Context p0) { return null; }
    public int getPickImagesMaxLimit() { return 0; }
    public android.content.res.AssetFileDescriptor openAssetFileDescriptor(android.content.ContentResolver p0, android.net.Uri p1, java.lang.String p2, android.os.CancellationSignal p3) { return null; }
    public android.net.Uri setRequireOriginal(android.net.Uri p0) { return null; }

    public static class Downloads {
        public android.net.Uri getContentUri(java.lang.String p0) { return null; }
    }

    public static class Files {
        public android.net.Uri getContentUri(java.lang.String p0) { return null; }
    }

    public static class Media {
    }

    public static class Thumbnails {
        public android.graphics.Bitmap getThumbnail(android.content.ContentResolver p0, long p1, int p2, android.graphics.BitmapFactory.Options p3) { return null; }
    }
}
