// @generated by gen-shims.py — do not edit by hand
package android.provider;

public class Settings {
    public boolean canDrawOverlays(android.content.Context p0) { return false; }

    public static class Global {
        public float getFloat(android.content.ContentResolver p0, java.lang.String p1, float p2) { return 0f; }
        public int getInt(android.content.ContentResolver p0, java.lang.String p1, int p2) { return 0; }
        public java.lang.String getString(android.content.ContentResolver p0, java.lang.String p1) { return null; }
        public android.net.Uri getUriFor(java.lang.String p0) { return null; }
    }

    public static class Secure {
        public int getInt(android.content.ContentResolver p0, java.lang.String p1, int p2) { return 0; }
        public int getInt(android.content.ContentResolver p0, java.lang.String p1) { return 0; }
        public java.lang.String getString(android.content.ContentResolver p0, java.lang.String p1) { return null; }
        public android.net.Uri getUriFor(java.lang.String p0) { return null; }
    }

    public static class System {
        public boolean canWrite(android.content.Context p0) { return false; }
        public float getFloat(android.content.ContentResolver p0, java.lang.String p1, float p2) { return 0f; }
        public int getInt(android.content.ContentResolver p0, java.lang.String p1) { return 0; }
        public int getInt(android.content.ContentResolver p0, java.lang.String p1, int p2) { return 0; }
        public java.lang.String getString(android.content.ContentResolver p0, java.lang.String p1) { return null; }
        public android.net.Uri getUriFor(java.lang.String p0) { return null; }
    }
}
