// @generated by gen-shims.py — do not edit by hand
package android.security;

public class KeyChain {
    public void choosePrivateKeyAlias(android.app.Activity p0, android.security.KeyChainAliasCallback p1, java.lang.String[] p2, java.security.Principal[] p3, java.lang.String p4, int p5, java.lang.String p6) {}
    public java.security.cert.X509Certificate[] getCertificateChain(android.content.Context p0, java.lang.String p1) { return null; }
    public java.security.PrivateKey getPrivateKey(android.content.Context p0, java.lang.String p1) { return null; }
}
