// @generated by gen-shims.py — do not edit by hand
package android.security;

public class KeyPairGeneratorSpec {

    public static class Builder {
        public android.security.KeyPairGeneratorSpec build() { return null; }
        public android.security.KeyPairGeneratorSpec.Builder setAlias(java.lang.String p0) { return null; }
        public android.security.KeyPairGeneratorSpec.Builder setEndDate(java.util.Date p0) { return null; }
        public android.security.KeyPairGeneratorSpec.Builder setSerialNumber(java.math.BigInteger p0) { return null; }
        public android.security.KeyPairGeneratorSpec.Builder setStartDate(java.util.Date p0) { return null; }
        public android.security.KeyPairGeneratorSpec.Builder setSubject(javax.security.auth.x500.X500Principal p0) { return null; }
    }
}
