// @generated by gen-shims.py — do not edit by hand
package android.security;

public class NetworkSecurityPolicy {
    public android.security.NetworkSecurityPolicy getInstance() { return null; }
    public boolean isCleartextTrafficPermitted() { return false; }
    public boolean isCleartextTrafficPermitted(java.lang.String p0) { return false; }
}
