// @generated by gen-shims.py — do not edit by hand
package android.adservices.signals;

public class ProtectedSignalsManager {
    public android.adservices.signals.ProtectedSignalsManager get(android.content.Context p0) { return null; }
    public void updateSignals(android.adservices.signals.UpdateSignalsRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
}
