// @generated by gen-shims.py — do not edit by hand
package android.app.backup;

public class BackupAgentHelper {
    public void addHelper(java.lang.String p0, android.app.backup.BackupHelper p1) {}
}
