// @generated by gen-shims.py — do not edit by hand
package android.app.backup;

public class BackupDataOutput {
    public int writeEntityData(byte[] p0, int p1) { return 0; }
    public int writeEntityHeader(java.lang.String p0, int p1) { return 0; }
}
