// @generated by gen-shims.py — do not edit by hand
package android.net;

public class ConnectivityManager {
    public void addDefaultNetworkActiveListener(android.net.ConnectivityManager.OnNetworkActiveListener p0) {}
    public android.net.Network getActiveNetwork() { return null; }
    public android.net.NetworkInfo getActiveNetworkInfo() { return null; }
    public android.net.Network[] getAllNetworks() { return null; }
    public android.net.ProxyInfo getDefaultProxy() { return null; }
    public android.net.LinkProperties getLinkProperties(android.net.Network p0) { return null; }
    public android.net.NetworkCapabilities getNetworkCapabilities(android.net.Network p0) { return null; }
    public android.net.NetworkInfo getNetworkInfo(int p0) { return null; }
    public int getRestrictBackgroundStatus() { return 0; }
    public boolean isActiveNetworkMetered() { return false; }
    public boolean isDefaultNetworkActive() { return false; }
    public void registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback p0) {}
    public void registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback p0, android.os.Handler p1) {}
    public void registerNetworkCallback(android.net.NetworkRequest p0, android.net.ConnectivityManager.NetworkCallback p1) {}
    public void registerNetworkCallback(android.net.NetworkRequest p0, android.net.ConnectivityManager.NetworkCallback p1, android.os.Handler p2) {}
    public void removeDefaultNetworkActiveListener(android.net.ConnectivityManager.OnNetworkActiveListener p0) {}
    public void reportNetworkConnectivity(android.net.Network p0, boolean p1) {}
    public void requestNetwork(android.net.NetworkRequest p0, android.net.ConnectivityManager.NetworkCallback p1) {}
    public void unregisterNetworkCallback(android.net.ConnectivityManager.NetworkCallback p0) {}

    public interface NetworkCallback {
        void onAvailable(android.net.Network p0);
        void onBlockedStatusChanged(android.net.Network p0, boolean p1);
        void onCapabilitiesChanged(android.net.Network p0, android.net.NetworkCapabilities p1);
        void onLost(android.net.Network p0);
    }

    public interface OnNetworkActiveListener {
    }
}
