// @generated by gen-shims.py — do not edit by hand
package android.net;

public class LinkProperties {
    public java.util.List getDnsServers() { return null; }
    public java.lang.String getDomains() { return null; }
    public android.net.ProxyInfo getHttpProxy() { return null; }
    public java.lang.String getPrivateDnsServerName() { return null; }
    public boolean isPrivateDnsActive() { return false; }
}
