// @generated by gen-shims.py — do not edit by hand
package android.net;

public class LocalSocket {
    public void close() {}
    public void connect(android.net.LocalSocketAddress p0) {}
    public void connect(android.net.LocalSocketAddress p0, int p1) {}
    public java.io.InputStream getInputStream() { return null; }
    public java.io.OutputStream getOutputStream() { return null; }
    public int getReceiveBufferSize() { return 0; }
    public int getSendBufferSize() { return 0; }
    public int getSoTimeout() { return 0; }
    public boolean isBound() { return false; }
    public boolean isConnected() { return false; }
    public void setReceiveBufferSize(int p0) {}
    public void setSendBufferSize(int p0) {}
    public void setSoTimeout(int p0) {}
    public void shutdownInput() {}
    public void shutdownOutput() {}
}
