// @generated by gen-shims.py — do not edit by hand
package android.net;

public class MailTo {
    public java.lang.String getBody() { return null; }
    public java.lang.String getCc() { return null; }
    public java.lang.String getSubject() { return null; }
    public java.lang.String getTo() { return null; }
    public boolean isMailTo(java.lang.String p0) { return false; }
    public android.net.MailTo parse(java.lang.String p0) { return null; }
}
