// @generated by gen-shims.py — do not edit by hand
package android.net;

public class Network {
    public void bindSocket(java.net.Socket p0) {}
    public boolean equals(java.lang.Object p0) { return false; }
    public android.net.Network fromNetworkHandle(long p0) { return null; }
    public long getNetworkHandle() { return 0; }
    public java.net.URLConnection openConnection(java.net.URL p0) { return null; }
    public java.lang.String toString() { return null; }
}
