// @generated by gen-shims.py — do not edit by hand
package android.net;

public class NetworkCapabilities {
    public int getLinkDownstreamBandwidthKbps() { return 0; }
    public int getLinkUpstreamBandwidthKbps() { return 0; }
    public int getSignalStrength() { return 0; }
    public android.net.TransportInfo getTransportInfo() { return null; }
    public boolean hasCapability(int p0) { return false; }
    public boolean hasTransport(int p0) { return false; }
    public java.lang.String toString() { return null; }
}
