// @generated by gen-shims.py — do not edit by hand
package android.net;

public class NetworkRequest {
    public boolean canBeSatisfiedBy(android.net.NetworkCapabilities p0) { return false; }
    public int[] getCapabilities() { return null; }
    public android.net.NetworkSpecifier getNetworkSpecifier() { return null; }
    public int[] getTransportTypes() { return null; }
    public boolean hasCapability(int p0) { return false; }
    public boolean hasTransport(int p0) { return false; }

    public static class Builder {
        public android.net.NetworkRequest.Builder addCapability(int p0) { return null; }
        public android.net.NetworkRequest.Builder addTransportType(int p0) { return null; }
        public android.net.NetworkRequest build() { return null; }
        public android.net.NetworkRequest.Builder removeCapability(int p0) { return null; }
    }
}
