// @generated by gen-shims.py — do not edit by hand
package android.net;

public class ProxyInfo {
    public java.lang.String[] getExclusionList() { return null; }
    public java.lang.String getHost() { return null; }
    public android.net.Uri getPacFileUrl() { return null; }
    public int getPort() { return 0; }
}
