// @generated by gen-shims.py — do not edit by hand
package android.net;

public class TrafficStats {
    public void clearThreadStatsTag() {}
    public int getThreadStatsTag() { return 0; }
    public int getThreadStatsUid() { return 0; }
    public long getTotalRxBytes() { return 0; }
    public long getTotalTxBytes() { return 0; }
    public long getUidRxBytes(int p0) { return 0; }
    public long getUidTxBytes(int p0) { return 0; }
    public void incrementOperationCount(int p0) {}
    public void incrementOperationCount(int p0, int p1) {}
    public void setThreadStatsTag(int p0) {}
    public void tagDatagramSocket(java.net.DatagramSocket p0) {}
    public void tagSocket(java.net.Socket p0) {}
    public void untagDatagramSocket(java.net.DatagramSocket p0) {}
    public void untagSocket(java.net.Socket p0) {}
}
