// @generated by gen-shims.py — do not edit by hand
package android.renderscript;

public class Allocation {
    public void copyTo(android.graphics.Bitmap p0) {}
    public android.renderscript.Allocation createFromBitmap(android.renderscript.RenderScript p0, android.graphics.Bitmap p1) { return null; }
}
