// @generated by gen-shims.py — do not edit by hand
package android.renderscript;

public class Element {
    public android.renderscript.Element U8_4(android.renderscript.RenderScript p0) { return null; }
}
