// @generated by gen-shims.py — do not edit by hand
package android.renderscript;

public class RenderScript {
    public android.renderscript.RenderScript create(android.content.Context p0) { return null; }
    public void destroy() {}
}
