// @generated by gen-shims.py — do not edit by hand
package android.renderscript;

public class ScriptIntrinsicBlur {
    public android.renderscript.ScriptIntrinsicBlur create(android.renderscript.RenderScript p0, android.renderscript.Element p1) { return null; }
    public void forEach(android.renderscript.Allocation p0) {}
    public void setInput(android.renderscript.Allocation p0) {}
    public void setRadius(float p0) {}
}
