// @generated by gen-shims.py — do not edit by hand
package android.view;

public class AbsSavedState {
    public android.os.Parcelable getSuperState() { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
