// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ActionMode {
    public void finish() {}
    public android.view.Menu getMenu() { return null; }
    public android.view.MenuInflater getMenuInflater() { return null; }
    public java.lang.Object getTag() { return null; }
    public void invalidate() {}
    public void invalidateContentRect() {}
    public void setCustomView(android.view.View p0) {}
    public void setTag(java.lang.Object p0) {}
    public void setTitle(java.lang.CharSequence p0) {}

    public interface Callback {
        boolean onActionItemClicked(android.view.ActionMode p0, android.view.MenuItem p1);
        boolean onCreateActionMode(android.view.ActionMode p0, android.view.Menu p1);
        void onDestroyActionMode(android.view.ActionMode p0);
        boolean onPrepareActionMode(android.view.ActionMode p0, android.view.Menu p1);
    }

    public static class Callback2 {
    }
}
