// @generated by gen-shims.py — do not edit by hand
package android.view;

public interface ActionProvider {
    boolean hasSubMenu();
    boolean isVisible();
    android.view.View onCreateActionView();
    android.view.View onCreateActionView(android.view.MenuItem p0);
    boolean onPerformDefaultAction();
    void onPrepareSubMenu(android.view.SubMenu p0);
    boolean overridesItemVisibility();
    void refreshVisibility();
    void setVisibilityListener(android.view.ActionProvider.VisibilityListener p0);

    public interface VisibilityListener {
    }
}
