// @generated by gen-shims.py — do not edit by hand
package android.view;

public class AttachedSurfaceControl {
    public boolean applyTransactionOnDraw(android.view.SurfaceControl.Transaction p0) { return false; }
    public android.view.SurfaceControl.Transaction buildReparentTransaction(android.view.SurfaceControl p0) { return null; }
}
