// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ContextMenu {
    public android.view.MenuItem add(int p0, int p1, int p2, int p3) { return null; }
    public android.view.ContextMenu setHeaderTitle(java.lang.CharSequence p0) { return null; }

    public static class ContextMenuInfo {
    }
}
