// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ContentInfo {
    public android.content.ClipData getClip() { return null; }
    public android.os.Bundle getExtras() { return null; }
    public int getFlags() { return 0; }
    public android.net.Uri getLinkUri() { return null; }
    public int getSource() { return 0; }

    public static class Builder {
        public android.view.ContentInfo build() { return null; }
        public android.view.ContentInfo.Builder setClip(android.content.ClipData p0) { return null; }
        public android.view.ContentInfo.Builder setExtras(android.os.Bundle p0) { return null; }
        public android.view.ContentInfo.Builder setFlags(int p0) { return null; }
        public android.view.ContentInfo.Builder setLinkUri(android.net.Uri p0) { return null; }
        public android.view.ContentInfo.Builder setSource(int p0) { return null; }
    }
}
