// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ContextThemeWrapper {
    public void applyOverrideConfiguration(android.content.res.Configuration p0) {}
    public android.content.res.Resources getResources() { return null; }
    public android.content.res.Resources.Theme getTheme() { return null; }
    public android.content.res.TypedArray obtainStyledAttributes(int[] p0) { return null; }
}
