// @generated by gen-shims.py — do not edit by hand
package android.view;

public class DisplayCutout {
    public java.util.List getBoundingRects() { return null; }
    public android.graphics.Path getCutoutPath() { return null; }
    public int getSafeInsetBottom() { return 0; }
    public int getSafeInsetLeft() { return 0; }
    public int getSafeInsetRight() { return 0; }
    public int getSafeInsetTop() { return 0; }
    public android.graphics.Insets getWaterfallInsets() { return null; }
    public int hashCode() { return 0; }

    public static class Builder {
        public android.view.DisplayCutout build() { return null; }
        public android.view.DisplayCutout.Builder setBoundingRectBottom(android.graphics.Rect p0) { return null; }
        public android.view.DisplayCutout.Builder setBoundingRectLeft(android.graphics.Rect p0) { return null; }
        public android.view.DisplayCutout.Builder setBoundingRectRight(android.graphics.Rect p0) { return null; }
        public android.view.DisplayCutout.Builder setBoundingRectTop(android.graphics.Rect p0) { return null; }
        public android.view.DisplayCutout.Builder setCutoutPath(android.graphics.Path p0) { return null; }
        public android.view.DisplayCutout.Builder setSafeInsets(android.graphics.Insets p0) { return null; }
        public android.view.DisplayCutout.Builder setWaterfallInsets(android.graphics.Insets p0) { return null; }
    }
}
