// @generated by gen-shims.py — do not edit by hand
package android.view;

public class DragEvent {
    public int getAction() { return 0; }
    public android.content.ClipData getClipData() { return null; }
    public android.content.ClipDescription getClipDescription() { return null; }
    public java.lang.Object getLocalState() { return null; }
    public float getX() { return 0f; }
    public float getY() { return 0f; }
}
