// @generated by gen-shims.py — do not edit by hand
package android.view;

public class GestureDetector {
    public boolean isLongpressEnabled() { return false; }
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public void setIsLongpressEnabled(boolean p0) {}
    public void setOnDoubleTapListener(android.view.GestureDetector.OnDoubleTapListener p0) {}

    public interface OnDoubleTapListener {
        boolean onDoubleTap(android.view.MotionEvent p0);
        boolean onDoubleTapEvent(android.view.MotionEvent p0);
        boolean onSingleTapConfirmed(android.view.MotionEvent p0);
    }

    public interface OnGestureListener {
        boolean onDown(android.view.MotionEvent p0);
        boolean onFling(android.view.MotionEvent p0, android.view.MotionEvent p1, float p2, float p3);
        void onLongPress(android.view.MotionEvent p0);
        boolean onScroll(android.view.MotionEvent p0, android.view.MotionEvent p1, float p2, float p3);
        void onShowPress(android.view.MotionEvent p0);
        boolean onSingleTapUp(android.view.MotionEvent p0);
    }

    public interface SimpleOnGestureListener {
        boolean onDoubleTap(android.view.MotionEvent p0);
        boolean onDoubleTapEvent(android.view.MotionEvent p0);
        boolean onDown(android.view.MotionEvent p0);
        boolean onFling(android.view.MotionEvent p0, android.view.MotionEvent p1, float p2, float p3);
        void onLongPress(android.view.MotionEvent p0);
        boolean onScroll(android.view.MotionEvent p0, android.view.MotionEvent p1, float p2, float p3);
        boolean onSingleTapConfirmed(android.view.MotionEvent p0);
        boolean onSingleTapUp(android.view.MotionEvent p0);
    }
}
