// @generated by gen-shims.py — do not edit by hand
package android.view;

public class Gravity {
    public void apply(int p0, int p1, int p2, android.graphics.Rect p3, int p4, int p5, android.graphics.Rect p6) {}
    public void apply(int p0, int p1, int p2, android.graphics.Rect p3, int p4, int p5, android.graphics.Rect p6, int p7) {}
    public void apply(int p0, int p1, int p2, android.graphics.Rect p3, android.graphics.Rect p4) {}
    public void apply(int p0, int p1, int p2, android.graphics.Rect p3, android.graphics.Rect p4, int p5) {}
    public void applyDisplay(int p0, android.graphics.Rect p1, android.graphics.Rect p2) {}
    public void applyDisplay(int p0, android.graphics.Rect p1, android.graphics.Rect p2, int p3) {}
    public int getAbsoluteGravity(int p0, int p1) { return 0; }
}
