// @generated by gen-shims.py — do not edit by hand
package android.view;

public class InputEvent {
    public android.view.InputDevice getDevice() { return null; }
    public boolean isFromSource(int p0) { return false; }
}
