// @generated by gen-shims.py — do not edit by hand
package android.view;

public class InputDevice {
    public android.view.InputDevice getDevice(int p0) { return null; }
    public int[] getDeviceIds() { return null; }
    public int getId() { return 0; }
    public int getKeyboardType() { return 0; }
    public android.view.InputDevice.MotionRange getMotionRange(int p0, int p1) { return null; }
    public android.view.InputDevice.MotionRange getMotionRange(int p0) { return null; }
    public java.util.List getMotionRanges() { return null; }
    public java.lang.String getName() { return null; }
    public int getSources() { return 0; }
    public boolean isVirtual() { return false; }
    public boolean supportsSource(int p0) { return false; }

    public static class MotionRange {
        public int getAxis() { return 0; }
        public float getFlat() { return 0f; }
        public float getMax() { return 0f; }
        public float getMin() { return 0f; }
        public float getRange() { return 0f; }
        public int getSource() { return 0; }
    }
}
