// @generated by gen-shims.py — do not edit by hand
package android.view;

public class KeyCharacterMap {
    public boolean deviceHasKey(int p0) { return false; }
    public int getDeadChar(int p0, int p1) { return 0; }
    public int getKeyboardType() { return 0; }
    public android.view.KeyCharacterMap load(int p0) { return null; }

    public static class KeyData {
    }
}
