// @generated by gen-shims.py — do not edit by hand
package android.view;

public class Menu {
    public android.view.MenuItem add(int p0, int p1, int p2, java.lang.CharSequence p3) { return null; }
    public android.view.MenuItem add(int p0) { return null; }
    public int addIntentOptions(int p0, int p1, int p2, android.content.ComponentName p3, android.content.Intent[] p4, android.content.Intent p5, int p6, android.view.MenuItem[] p7) { return 0; }
    public android.view.SubMenu addSubMenu(int p0, int p1, int p2, java.lang.CharSequence p3) { return null; }
    public android.view.SubMenu addSubMenu(int p0) { return null; }
    public void clear() {}
    public void close() {}
    public android.view.MenuItem findItem(int p0) { return null; }
    public android.view.MenuItem getItem(int p0) { return null; }
    public boolean hasVisibleItems() { return false; }
    public boolean isShortcutKey(int p0, android.view.KeyEvent p1) { return false; }
    public boolean performIdentifierAction(int p0, int p1) { return false; }
    public boolean performShortcut(int p0, android.view.KeyEvent p1, int p2) { return false; }
    public void removeGroup(int p0) {}
    public void removeItem(int p0) {}
    public void setGroupCheckable(int p0, boolean p1, boolean p2) {}
    public void setGroupDividerEnabled(boolean p0) {}
    public void setGroupEnabled(int p0, boolean p1) {}
    public void setGroupVisible(int p0, boolean p1) {}
    public void setQwertyMode(boolean p0) {}
    public int size() { return 0; }
}
