// @generated by gen-shims.py — do not edit by hand
package android.view;

public class PixelCopy {
    public void request(android.view.SurfaceView p0, android.graphics.Bitmap p1, android.view.PixelCopy.OnPixelCopyFinishedListener p2, android.os.Handler p3) {}
    public void request(android.view.Window p0, android.graphics.Rect p1, android.graphics.Bitmap p2, android.view.PixelCopy.OnPixelCopyFinishedListener p3, android.os.Handler p4) {}

    public interface OnPixelCopyFinishedListener {
    }
}
