// @generated by gen-shims.py — do not edit by hand
package android.view;

public class PointerIcon {
    public android.view.PointerIcon create(android.graphics.Bitmap p0, float p1, float p2) { return null; }
    public android.view.PointerIcon getSystemIcon(android.content.Context p0, int p1) { return null; }
    public int hashCode() { return 0; }
    public android.view.PointerIcon load(android.content.res.Resources p0, int p1) { return null; }
}
