// @generated by gen-shims.py — do not edit by hand
package android.view;

public class RoundedCorner {
    public android.graphics.Point getCenter() { return null; }
    public int getPosition() { return 0; }
    public int getRadius() { return 0; }
}
