// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ScaleGestureDetector {
    public float getFocusX() { return 0f; }
    public float getFocusY() { return 0f; }
    public float getScaleFactor() { return 0f; }
    public boolean isInProgress() { return false; }
    public boolean isQuickScaleEnabled() { return false; }
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public void setQuickScaleEnabled(boolean p0) {}
    public void setStylusScaleEnabled(boolean p0) {}

    public interface OnScaleGestureListener {
    }

    public interface SimpleOnScaleGestureListener {
    }
}
