// @generated by gen-shims.py — do not edit by hand
package android.view;

public interface ScrollFeedbackProvider {
    android.view.ScrollFeedbackProvider createProvider(android.view.View p0);
    void onScrollLimit(int p0, int p1, int p2, boolean p3);
    void onScrollProgress(int p0, int p1, int p2, int p3);
    void onSnapToItem(int p0, int p1, int p2);
}
