// @generated by gen-shims.py — do not edit by hand
package android.view;

public class SubMenu {
    public android.view.MenuItem add(int p0, int p1, int p2, java.lang.CharSequence p3) { return null; }
    public android.view.SubMenu addSubMenu(int p0, int p1, int p2, java.lang.CharSequence p3) { return null; }
    public void clear() {}
    public void clearHeader() {}
    public android.view.MenuItem findItem(int p0) { return null; }
    public android.view.MenuItem getItem() { return null; }
    public android.view.MenuItem getItem(int p0) { return null; }
    public boolean hasVisibleItems() { return false; }
    public android.view.SubMenu setHeaderIcon(int p0) { return null; }
    public android.view.SubMenu setHeaderTitle(int p0) { return null; }
    public android.view.SubMenu setHeaderView(android.view.View p0) { return null; }
    public android.view.SubMenu setIcon(int p0) { return null; }
    public int size() { return 0; }
}
