// @generated by gen-shims.py — do not edit by hand
package android.view;

public interface SurfaceHolder {
    void addCallback(android.view.SurfaceHolder.Callback p0);
    android.view.Surface getSurface();
    android.graphics.Rect getSurfaceFrame();
    boolean isCreating();
    android.graphics.Canvas lockCanvas();
    android.graphics.Canvas lockCanvas(android.graphics.Rect p0);
    void removeCallback(android.view.SurfaceHolder.Callback p0);
    void setFixedSize(int p0, int p1);
    void setFormat(int p0);
    void setSizeFromLayout();
    void unlockCanvasAndPost(android.graphics.Canvas p0);

    public interface Callback {
        void surfaceChanged(android.view.SurfaceHolder p0, int p1, int p2, int p3);
        void surfaceCreated(android.view.SurfaceHolder p0);
        void surfaceDestroyed(android.view.SurfaceHolder p0);
    }
}
