// @generated by gen-shims.py — do not edit by hand
package android.view;

public class VelocityTracker {
    public void addMovement(android.view.MotionEvent p0) {}
    public void clear() {}
    public void computeCurrentVelocity(int p0, float p1) {}
    public void computeCurrentVelocity(int p0) {}
    public float getAxisVelocity(int p0) { return 0f; }
    public float getAxisVelocity(int p0, int p1) { return 0f; }
    public float getXVelocity() { return 0f; }
    public float getXVelocity(int p0) { return 0f; }
    public float getYVelocity() { return 0f; }
    public float getYVelocity(int p0) { return 0f; }
    public boolean isAxisSupported(int p0) { return false; }
    public android.view.VelocityTracker obtain() { return null; }
    public void recycle() {}
}
