// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ViewStructure {
    public int addChildCount(int p0) { return 0; }
    public android.view.autofill.AutofillId getAutofillId() { return null; }
    public android.os.Bundle getExtras() { return null; }
    public android.view.ViewStructure newChild(int p0) { return null; }
    public void setAutofillHints(java.lang.String[] p0) {}
    public void setAutofillId(android.view.autofill.AutofillId p0) {}
    public void setAutofillId(android.view.autofill.AutofillId p0, int p1) {}
    public void setAutofillType(int p0) {}
    public void setAutofillValue(android.view.autofill.AutofillValue p0) {}
    public void setCheckable(boolean p0) {}
    public void setChecked(boolean p0) {}
    public void setChildCount(int p0) {}
    public void setClassName(java.lang.String p0) {}
    public void setClickable(boolean p0) {}
    public void setContentDescription(java.lang.CharSequence p0) {}
    public void setDataIsSensitive(boolean p0) {}
    public void setDimens(int p0, int p1, int p2, int p3, int p4, int p5) {}
    public void setEnabled(boolean p0) {}
    public void setFocusable(boolean p0) {}
    public void setFocused(boolean p0) {}
    public void setHint(java.lang.CharSequence p0) {}
    public void setId(int p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) {}
    public void setInputType(int p0) {}
    public void setLongClickable(boolean p0) {}
    public void setMaxTextLength(int p0) {}
    public void setOpaque(boolean p0) {}
    public void setSelected(boolean p0) {}
    public void setText(java.lang.CharSequence p0) {}
    public void setTextStyle(float p0, int p1, int p2, int p3) {}
    public void setVisibility(int p0) {}

    public static class HtmlInfo {
        public java.util.List getAttributes() { return null; }
        public java.lang.String getTag() { return null; }
    }
}
