// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ViewConfiguration {
    public android.view.ViewConfiguration get(android.content.Context p0) { return null; }
    public int getDoubleTapTimeout() { return 0; }
    public int getLongPressTimeout() { return 0; }
    public int getMaximumFlingVelocity() { return 0; }
    public int getMinimumFlingVelocity() { return 0; }
    public int getPressedStateDuration() { return 0; }
    public int getScaledDoubleTapSlop() { return 0; }
    public int getScaledEdgeSlop() { return 0; }
    public int getScaledHandwritingGestureLineMargin() { return 0; }
    public int getScaledHandwritingSlop() { return 0; }
    public float getScaledHorizontalScrollFactor() { return 0f; }
    public int getScaledHoverSlop() { return 0; }
    public int getScaledMaximumFlingVelocity() { return 0; }
    public int getScaledMaximumFlingVelocity(int p0, int p1, int p2) { return 0; }
    public int getScaledMinimumFlingVelocity() { return 0; }
    public int getScaledMinimumFlingVelocity(int p0, int p1, int p2) { return 0; }
    public int getScaledPagingTouchSlop() { return 0; }
    public int getScaledTouchSlop() { return 0; }
    public float getScaledVerticalScrollFactor() { return 0f; }
    public int getScaledWindowTouchSlop() { return 0; }
    public float getScrollFriction() { return 0f; }
    public int getTapTimeout() { return 0; }
    public boolean hasPermanentMenuKey() { return false; }
    public boolean shouldShowMenuShortcutsWhenKeyboardPresent() { return false; }
}
