// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ViewManager {
    public void addView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public void removeView(android.view.View p0) {}
    public void updateViewLayout(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
}
