// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ViewGroupOverlay {
    public void add(android.graphics.drawable.Drawable p0) {}
    public void remove(android.graphics.drawable.Drawable p0) {}
}
