// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ViewAnimationUtils {
    public android.animation.Animator createCircularReveal(android.view.View p0, int p1, int p2, float p3, float p4) { return null; }
}
