// @generated by gen-shims.py — do not edit by hand
package android.view;

public interface ViewTreeObserver {
    void addOnDrawListener(android.view.ViewTreeObserver.OnDrawListener p0);
    void addOnGlobalFocusChangeListener(android.view.ViewTreeObserver.OnGlobalFocusChangeListener p0);
    void addOnGlobalLayoutListener(android.view.ViewTreeObserver.OnGlobalLayoutListener p0);
    void addOnPreDrawListener(android.view.ViewTreeObserver.OnPreDrawListener p0);
    void addOnScrollChangedListener(android.view.ViewTreeObserver.OnScrollChangedListener p0);
    void addOnTouchModeChangeListener(android.view.ViewTreeObserver.OnTouchModeChangeListener p0);
    void addOnWindowAttachListener(android.view.ViewTreeObserver.OnWindowAttachListener p0);
    void addOnWindowFocusChangeListener(android.view.ViewTreeObserver.OnWindowFocusChangeListener p0);
    void dispatchOnGlobalLayout();
    boolean dispatchOnPreDraw();
    boolean isAlive();
    void removeGlobalOnLayoutListener(android.view.ViewTreeObserver.OnGlobalLayoutListener p0);
    void removeOnDrawListener(android.view.ViewTreeObserver.OnDrawListener p0);
    void removeOnGlobalFocusChangeListener(android.view.ViewTreeObserver.OnGlobalFocusChangeListener p0);
    void removeOnGlobalLayoutListener(android.view.ViewTreeObserver.OnGlobalLayoutListener p0);
    void removeOnPreDrawListener(android.view.ViewTreeObserver.OnPreDrawListener p0);
    void removeOnScrollChangedListener(android.view.ViewTreeObserver.OnScrollChangedListener p0);
    void removeOnTouchModeChangeListener(android.view.ViewTreeObserver.OnTouchModeChangeListener p0);
    void removeOnWindowAttachListener(android.view.ViewTreeObserver.OnWindowAttachListener p0);
    void removeOnWindowFocusChangeListener(android.view.ViewTreeObserver.OnWindowFocusChangeListener p0);

    public interface OnDrawListener {
    }

    public interface OnGlobalFocusChangeListener {
    }

    public interface OnGlobalLayoutListener {
        void onGlobalLayout();
    }

    public interface OnPreDrawListener {
    }

    public interface OnScrollChangedListener {
        void onScrollChanged();
    }

    public interface OnTouchModeChangeListener {
    }

    public interface OnWindowAttachListener {
    }

    public interface OnWindowFocusChangeListener {
    }
}
