// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ViewPropertyAnimator {
    public android.view.ViewPropertyAnimator alpha(float p0) { return null; }
    public android.view.ViewPropertyAnimator alphaBy(float p0) { return null; }
    public void cancel() {}
    public long getDuration() { return 0; }
    public android.animation.TimeInterpolator getInterpolator() { return null; }
    public long getStartDelay() { return 0; }
    public android.view.ViewPropertyAnimator rotation(float p0) { return null; }
    public android.view.ViewPropertyAnimator rotationBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator rotationX(float p0) { return null; }
    public android.view.ViewPropertyAnimator rotationXBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator rotationY(float p0) { return null; }
    public android.view.ViewPropertyAnimator rotationYBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator scaleX(float p0) { return null; }
    public android.view.ViewPropertyAnimator scaleXBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator scaleY(float p0) { return null; }
    public android.view.ViewPropertyAnimator scaleYBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator setDuration(long p0) { return null; }
    public android.view.ViewPropertyAnimator setInterpolator(android.animation.TimeInterpolator p0) { return null; }
    public android.view.ViewPropertyAnimator setListener(android.animation.Animator.AnimatorListener p0) { return null; }
    public android.view.ViewPropertyAnimator setStartDelay(long p0) { return null; }
    public android.view.ViewPropertyAnimator setUpdateListener(android.animation.ValueAnimator.AnimatorUpdateListener p0) { return null; }
    public void start() {}
    public android.view.ViewPropertyAnimator translationX(float p0) { return null; }
    public android.view.ViewPropertyAnimator translationXBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator translationY(float p0) { return null; }
    public android.view.ViewPropertyAnimator translationYBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator translationZ(float p0) { return null; }
    public android.view.ViewPropertyAnimator translationZBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator withEndAction(java.lang.Runnable p0) { return null; }
    public android.view.ViewPropertyAnimator withLayer() { return null; }
    public android.view.ViewPropertyAnimator withStartAction(java.lang.Runnable p0) { return null; }
    public android.view.ViewPropertyAnimator x(float p0) { return null; }
    public android.view.ViewPropertyAnimator xBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator y(float p0) { return null; }
    public android.view.ViewPropertyAnimator yBy(float p0) { return null; }
    public android.view.ViewPropertyAnimator z(float p0) { return null; }
    public android.view.ViewPropertyAnimator zBy(float p0) { return null; }
}
