// @generated by gen-shims.py — do not edit by hand
package android.view;

public class ViewStub {
    public int getInflatedId() { return 0; }
    public int getLayoutResource() { return 0; }
    public android.view.View inflate() { return null; }
    public void setLayoutInflater(android.view.LayoutInflater p0) {}
    public void setLayoutResource(int p0) {}
    public void setOnInflateListener(android.view.ViewStub.OnInflateListener p0) {}

    public interface OnInflateListener {
        void onInflate(android.view.ViewStub p0, android.view.View p1);
    }
}
