// @generated by gen-shims.py — do not edit by hand
package android.view;

public class WindowInsetsAnimationController {
    public void finish(boolean p0) {}
    public float getCurrentAlpha() { return 0f; }
    public float getCurrentFraction() { return 0f; }
    public android.graphics.Insets getCurrentInsets() { return null; }
    public android.graphics.Insets getHiddenStateInsets() { return null; }
    public android.graphics.Insets getShownStateInsets() { return null; }
    public int getTypes() { return 0; }
    public boolean isCancelled() { return false; }
    public boolean isFinished() { return false; }
    public boolean isReady() { return false; }
    public void setInsetsAndAlpha(android.graphics.Insets p0, float p1, float p2) {}
}
