// @generated by gen-shims.py — do not edit by hand
package android.view;

public class WindowInsetsController {
    public void addOnControllableInsetsChangedListener(android.view.WindowInsetsController.OnControllableInsetsChangedListener p0) {}
    public void controlWindowInsetsAnimation(int p0, long p1, android.view.animation.Interpolator p2, android.os.CancellationSignal p3, android.view.WindowInsetsAnimationControlListener p4) {}
    public int getSystemBarsAppearance() { return 0; }
    public int getSystemBarsBehavior() { return 0; }
    public void hide(int p0) {}
    public void removeOnControllableInsetsChangedListener(android.view.WindowInsetsController.OnControllableInsetsChangedListener p0) {}
    public void setSystemBarsAppearance(int p0, int p1) {}
    public void setSystemBarsBehavior(int p0) {}
    public void show(int p0) {}

    public interface OnControllableInsetsChangedListener {
    }
}
