// @generated by gen-shims.py — do not edit by hand
package android.view;

public class WindowInsetsAnimation {
    public float getAlpha() { return 0f; }
    public long getDurationMillis() { return 0; }
    public float getFraction() { return 0f; }
    public float getInterpolatedFraction() { return 0f; }
    public android.view.animation.Interpolator getInterpolator() { return null; }
    public int getTypeMask() { return 0; }
    public void setAlpha(float p0) {}
    public void setFraction(float p0) {}

    public static class Bounds {
        public android.graphics.Insets getLowerBound() { return null; }
        public android.graphics.Insets getUpperBound() { return null; }
    }

    public interface Callback {
    }
}
