// @generated by gen-shims.py — do not edit by hand
package android.view;

public class WindowManager {
    public void addCrossWindowBlurEnabledListener(java.util.concurrent.Executor p0, java.util.function.Consumer p1) {}
    public void addCrossWindowBlurEnabledListener(java.util.function.Consumer p0) {}
    public void addView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public android.view.WindowMetrics getCurrentWindowMetrics() { return null; }
    public android.view.Display getDefaultDisplay() { return null; }
    public android.view.WindowMetrics getMaximumWindowMetrics() { return null; }
    public boolean isCrossWindowBlurEnabled() { return false; }
    public void removeCrossWindowBlurEnabledListener(java.util.function.Consumer p0) {}
    public void removeView(android.view.View p0) {}
    public void removeViewImmediate(android.view.View p0) {}
    public void updateViewLayout(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}

    public static class LayoutParams {
        public void setBlurBehindRadius(int p0) {}
        public void setFitInsetsSides(int p0) {}
        public void setFitInsetsTypes(int p0) {}
        public void setTitle(java.lang.CharSequence p0) {}
    }
}
