// @generated by gen-shims.py — do not edit by hand
package android.view;

public class WindowId {
    public boolean equals(java.lang.Object p0) { return false; }
    public int hashCode() { return 0; }
}
