// @generated by gen-shims.py — do not edit by hand
package android.view;

public class WindowMetrics {
    public android.graphics.Rect getBounds() { return null; }
    public float getDensity() { return 0f; }
    public android.view.WindowInsets getWindowInsets() { return null; }
}
