// @generated by gen-shims.py — do not edit by hand
package android.view;

public class Window {
    public void addFlags(int p0) {}
    public void addOnFrameMetricsAvailableListener(android.view.Window.OnFrameMetricsAvailableListener p0, android.os.Handler p1) {}
    public void clearFlags(int p0) {}
    public android.view.View findViewById(int p0) { return null; }
    public android.view.WindowManager.LayoutParams getAttributes() { return null; }
    public android.view.Window.Callback getCallback() { return null; }
    public android.content.Context getContext() { return null; }
    public android.view.View getCurrentFocus() { return null; }
    public android.view.View getDecorView() { return null; }
    public android.transition.Transition getEnterTransition() { return null; }
    public android.transition.Transition getExitTransition() { return null; }
    public android.view.WindowInsetsController getInsetsController() { return null; }
    public int getNavigationBarColor() { return 0; }
    public int getNavigationBarDividerColor() { return 0; }
    public android.transition.Transition getReenterTransition() { return null; }
    public android.transition.Transition getReturnTransition() { return null; }
    public android.transition.Transition getSharedElementEnterTransition() { return null; }
    public android.transition.Transition getSharedElementExitTransition() { return null; }
    public android.transition.Transition getSharedElementReenterTransition() { return null; }
    public android.transition.Transition getSharedElementReturnTransition() { return null; }
    public int getStatusBarColor() { return 0; }
    public android.view.WindowManager getWindowManager() { return null; }
    public boolean hasFeature(int p0) { return false; }
    public android.view.View peekDecorView() { return null; }
    public void removeOnFrameMetricsAvailableListener(android.view.Window.OnFrameMetricsAvailableListener p0) {}
    public boolean requestFeature(int p0) { return false; }
    public android.view.View requireViewById(int p0) { return null; }
    public void setAttributes(android.view.WindowManager.LayoutParams p0) {}
    public void setBackgroundDrawable(android.graphics.drawable.Drawable p0) {}
    public void setBackgroundDrawableResource(int p0) {}
    public void setCallback(android.view.Window.Callback p0) {}
    public void setContentView(android.view.View p0) {}
    public void setDecorFitsSystemWindows(boolean p0) {}
    public void setDimAmount(float p0) {}
    public void setEnterTransition(android.transition.Transition p0) {}
    public void setFlags(int p0, int p1) {}
    public void setFormat(int p0) {}
    public void setGravity(int p0) {}
    public void setLayout(int p0, int p1) {}
    public void setNavigationBarColor(int p0) {}
    public void setNavigationBarContrastEnforced(boolean p0) {}
    public void setNavigationBarDividerColor(int p0) {}
    public void setReturnTransition(android.transition.Transition p0) {}
    public void setSharedElementEnterTransition(android.transition.Transition p0) {}
    public void setSharedElementReenterTransition(android.transition.Transition p0) {}
    public void setSharedElementReturnTransition(android.transition.Transition p0) {}
    public void setSoftInputMode(int p0) {}
    public void setStatusBarColor(int p0) {}
    public void setStatusBarContrastEnforced(boolean p0) {}
    public void setTransitionBackgroundFadeDuration(long p0) {}
    public void setType(int p0) {}
    public void setWindowAnimations(int p0) {}
    public boolean superDispatchKeyEvent(android.view.KeyEvent p0) { return false; }

    public interface Callback {
        boolean dispatchGenericMotionEvent(android.view.MotionEvent p0);
        boolean dispatchKeyEvent(android.view.KeyEvent p0);
        boolean dispatchKeyShortcutEvent(android.view.KeyEvent p0);
        boolean dispatchPopulateAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0);
        boolean dispatchTouchEvent(android.view.MotionEvent p0);
        boolean dispatchTrackballEvent(android.view.MotionEvent p0);
        void onActionModeFinished(android.view.ActionMode p0);
        void onActionModeStarted(android.view.ActionMode p0);
        void onAttachedToWindow();
        void onContentChanged();
        boolean onCreatePanelMenu(int p0, android.view.Menu p1);
        android.view.View onCreatePanelView(int p0);
        void onDetachedFromWindow();
        boolean onMenuItemSelected(int p0, android.view.MenuItem p1);
        boolean onMenuOpened(int p0, android.view.Menu p1);
        void onPanelClosed(int p0, android.view.Menu p1);
        void onPointerCaptureChanged(boolean p0);
        boolean onPreparePanel(int p0, android.view.View p1, android.view.Menu p2);
        void onProvideKeyboardShortcuts(java.util.List p0, android.view.Menu p1, int p2);
        boolean onSearchRequested();
        boolean onSearchRequested(android.view.SearchEvent p0);
        void onWindowAttributesChanged(android.view.WindowManager.LayoutParams p0);
        void onWindowFocusChanged(boolean p0);
        android.view.ActionMode onWindowStartingActionMode(android.view.ActionMode.Callback p0);
        android.view.ActionMode onWindowStartingActionMode(android.view.ActionMode.Callback p0, int p1);
    }

    public interface OnFrameMetricsAvailableListener {
    }
}
