// @generated by gen-shims.py — do not edit by hand
package android.text.method;

public class ArrowKeyMovementMethod {
    public android.text.method.MovementMethod getInstance() { return null; }
    public boolean onTouchEvent(android.widget.TextView p0, android.text.Spannable p1, android.view.MotionEvent p2) { return false; }
}
