// @generated by gen-shims.py — do not edit by hand
package android.text.method;

public interface DigitsKeyListener {
    android.text.method.DigitsKeyListener getInstance(java.lang.String p0);
    android.text.method.DigitsKeyListener getInstance(boolean p0, boolean p1);
}
