// @generated by gen-shims.py — do not edit by hand
package android.text.method;

public class HideReturnsTransformationMethod {
    public android.text.method.HideReturnsTransformationMethod getInstance() { return null; }
}
