// @generated by gen-shims.py — do not edit by hand
package android.text.method;

public interface KeyListener {
    void clearMetaKeyState(android.view.View p0, android.text.Editable p1, int p2);
    int getInputType();
    boolean onKeyDown(android.view.View p0, android.text.Editable p1, int p2, android.view.KeyEvent p3);
    boolean onKeyOther(android.view.View p0, android.text.Editable p1, android.view.KeyEvent p2);
    boolean onKeyUp(android.view.View p0, android.text.Editable p1, int p2, android.view.KeyEvent p3);
}
