// @generated by gen-shims.py — do not edit by hand
package android.text.method;

public class PasswordTransformationMethod {
    public android.text.method.PasswordTransformationMethod getInstance() { return null; }
}
