// @generated by gen-shims.py — do not edit by hand
package android.text.method;

public class SingleLineTransformationMethod {
    public android.text.method.SingleLineTransformationMethod getInstance() { return null; }
    public java.lang.CharSequence getTransformation(java.lang.CharSequence p0, android.view.View p1) { return null; }
}
