// @generated by gen-shims.py — do not edit by hand
package android.text.method;

public interface TextKeyListener {
    android.text.method.TextKeyListener getInstance(boolean p0, android.text.method.TextKeyListener.Capitalize p1);

    public static class Capitalize {
    }
}
