// @generated by gen-shims.py — do not edit by hand
package android.hardware.display;

public class DisplayManager {
    public android.hardware.display.VirtualDisplay createVirtualDisplay(java.lang.String p0, int p1, int p2, int p3, android.view.Surface p4, int p5) { return null; }
    public android.view.Display getDisplay(int p0) { return null; }
    public android.view.Display[] getDisplays() { return null; }
    public android.view.Display[] getDisplays(java.lang.String p0) { return null; }
    public int getMatchContentFrameRateUserPreference() { return 0; }
    public void registerDisplayListener(android.hardware.display.DisplayManager.DisplayListener p0, android.os.Handler p1) {}
    public void unregisterDisplayListener(android.hardware.display.DisplayManager.DisplayListener p0) {}

    public interface DisplayListener {
    }
}
