// @generated by gen-shims.py — do not edit by hand
package android.hardware.display;

public class VirtualDisplay {
    public android.view.Display getDisplay() { return null; }
    public void release() {}
}
