// @generated by gen-shims.py — do not edit by hand
package android.icu.util;

public class Calendar {
    public android.icu.util.Calendar getInstance(java.util.Locale p0) { return null; }
    public java.lang.String getType() { return null; }
}
