// @generated by gen-shims.py — do not edit by hand
package android.icu.util;

public class Measure {
    public java.lang.Number getNumber() { return null; }
    public android.icu.util.MeasureUnit getUnit() { return null; }
}
