// @generated by gen-shims.py — do not edit by hand
package android.icu.util;

public class ULocale {
    public android.icu.util.ULocale addLikelySubtags(android.icu.util.ULocale p0) { return null; }
    public android.icu.util.ULocale forLocale(java.util.Locale p0) { return null; }
    public java.lang.String getScript() { return null; }
}
