// @generated by gen-shims.py — do not edit by hand
package android.media.browse;

public class MediaBrowser {
    public void connect() {}
    public void disconnect() {}
    public android.os.Bundle getExtras() { return null; }
    public void getItem(java.lang.String p0, android.media.browse.MediaBrowser.ItemCallback p1) {}
    public java.lang.String getRoot() { return null; }
    public android.content.ComponentName getServiceComponent() { return null; }
    public android.media.session.MediaSession.Token getSessionToken() { return null; }
    public boolean isConnected() { return false; }
    public void subscribe(java.lang.String p0, android.media.browse.MediaBrowser.SubscriptionCallback p1) {}
    public void subscribe(java.lang.String p0, android.os.Bundle p1, android.media.browse.MediaBrowser.SubscriptionCallback p2) {}
    public void unsubscribe(java.lang.String p0) {}
    public void unsubscribe(java.lang.String p0, android.media.browse.MediaBrowser.SubscriptionCallback p1) {}

    public interface ConnectionCallback {
    }

    public interface ItemCallback {
    }

    public static class MediaItem {
        public android.media.MediaDescription getDescription() { return null; }
        public int getFlags() { return 0; }
        public java.lang.String getMediaId() { return null; }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
    }

    public interface SubscriptionCallback {
    }
}
