// @generated by gen-shims.py — do not edit by hand
package android.view.inspector;

public class PropertyMapper {
    public int mapBoolean(java.lang.String p0, int p1) { return 0; }
    public int mapFloat(java.lang.String p0, int p1) { return 0; }
    public int mapGravity(java.lang.String p0, int p1) { return 0; }
    public int mapInt(java.lang.String p0, int p1) { return 0; }
    public int mapIntEnum(java.lang.String p0, int p1, java.util.function.IntFunction p2) { return 0; }
    public int mapIntFlag(java.lang.String p0, int p1, java.util.function.IntFunction p2) { return 0; }
    public int mapObject(java.lang.String p0, int p1) { return 0; }
    public int mapResourceId(java.lang.String p0, int p1) { return 0; }
}
