// @generated by gen-shims.py — do not edit by hand
package android.adservices.customaudience;

public class CustomAudience {

    public static class Builder {
        public android.adservices.customaudience.CustomAudience build() { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setActivationTime(java.time.Instant p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setAds(java.util.List p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setBiddingLogicUri(android.net.Uri p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setBuyer(android.adservices.common.AdTechIdentifier p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setDailyUpdateUri(android.net.Uri p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setExpirationTime(java.time.Instant p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setName(java.lang.String p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setTrustedBiddingData(android.adservices.customaudience.TrustedBiddingData p0) { return null; }
        public android.adservices.customaudience.CustomAudience.Builder setUserBiddingSignals(android.adservices.common.AdSelectionSignals p0) { return null; }
    }
}
