// @generated by gen-shims.py — do not edit by hand
package android.adservices.customaudience;

public class FetchAndJoinCustomAudienceRequest {

    public static class Builder {
        public android.adservices.customaudience.FetchAndJoinCustomAudienceRequest build() { return null; }
        public android.adservices.customaudience.FetchAndJoinCustomAudienceRequest.Builder setActivationTime(java.time.Instant p0) { return null; }
        public android.adservices.customaudience.FetchAndJoinCustomAudienceRequest.Builder setExpirationTime(java.time.Instant p0) { return null; }
        public android.adservices.customaudience.FetchAndJoinCustomAudienceRequest.Builder setName(java.lang.String p0) { return null; }
        public android.adservices.customaudience.FetchAndJoinCustomAudienceRequest.Builder setUserBiddingSignals(android.adservices.common.AdSelectionSignals p0) { return null; }
    }
}
