// @generated by gen-shims.py — do not edit by hand
package android.adservices.customaudience;

public class JoinCustomAudienceRequest {

    public static class Builder {
        public android.adservices.customaudience.JoinCustomAudienceRequest build() { return null; }
        public android.adservices.customaudience.JoinCustomAudienceRequest.Builder setCustomAudience(android.adservices.customaudience.CustomAudience p0) { return null; }
    }
}
