// @generated by gen-shims.py — do not edit by hand
package android.adservices.customaudience;

public class LeaveCustomAudienceRequest {

    public static class Builder {
        public android.adservices.customaudience.LeaveCustomAudienceRequest build() { return null; }
        public android.adservices.customaudience.LeaveCustomAudienceRequest.Builder setBuyer(android.adservices.common.AdTechIdentifier p0) { return null; }
        public android.adservices.customaudience.LeaveCustomAudienceRequest.Builder setName(java.lang.String p0) { return null; }
    }
}
