// @generated by gen-shims.py — do not edit by hand
package android.adservices.customaudience;

public class TrustedBiddingData {

    public static class Builder {
        public android.adservices.customaudience.TrustedBiddingData build() { return null; }
        public android.adservices.customaudience.TrustedBiddingData.Builder setTrustedBiddingKeys(java.util.List p0) { return null; }
        public android.adservices.customaudience.TrustedBiddingData.Builder setTrustedBiddingUri(android.net.Uri p0) { return null; }
    }
}
