// @generated by gen-shims.py — do not edit by hand
package android.hardware.camera2;

public class CameraManager {
    public android.hardware.camera2.CameraCharacteristics getCameraCharacteristics(java.lang.String p0) { return null; }
    public java.lang.String[] getCameraIdList() { return null; }
}
