// @generated by gen-shims.py — do not edit by hand
package android.hardware.camera2;

public class CameraCharacteristics {
    public java.lang.Object get(android.hardware.camera2.CameraCharacteristics.Key p0) { return null; }

    public static class Key {
    }
}
