// @generated by gen-shims.py — do not edit by hand
package android.graphics.fonts;

public class Font {
    public android.graphics.fonts.FontStyle getStyle() { return null; }

    public static class Builder {
        public android.graphics.fonts.Font build() { return null; }
        public android.graphics.fonts.Font.Builder setFontVariationSettings(java.lang.String p0) { return null; }
        public android.graphics.fonts.Font.Builder setSlant(int p0) { return null; }
        public android.graphics.fonts.Font.Builder setTtcIndex(int p0) { return null; }
        public android.graphics.fonts.Font.Builder setWeight(int p0) { return null; }
    }
}
