// @generated by gen-shims.py — do not edit by hand
package android.graphics.fonts;

public class FontFamily {
    public android.graphics.fonts.Font getFont(int p0) { return null; }
    public int getSize() { return 0; }

    public static class Builder {
        public android.graphics.fonts.FontFamily.Builder addFont(android.graphics.fonts.Font p0) { return null; }
        public android.graphics.fonts.FontFamily build() { return null; }
    }
}
