// @generated by gen-shims.py — do not edit by hand
package android.graphics.fonts;

public class FontVariationAxis {
    public android.graphics.fonts.FontVariationAxis[] fromFontVariationSettings(java.lang.String p0) { return null; }
}
