// @generated by gen-shims.py — do not edit by hand
package android.icu.text;

public class CompactDecimalFormat {
    public java.lang.String format(long p0) { return null; }
    public android.icu.text.CompactDecimalFormat getInstance(java.util.Locale p0, android.icu.text.CompactDecimalFormat.CompactStyle p1) { return null; }

    public static class CompactStyle {
    }
}
