// @generated by gen-shims.py — do not edit by hand
package android.icu.text;

public class DateFormat {
    public java.lang.String format(java.util.Date p0) { return null; }
    public android.icu.text.DateFormat getInstanceForSkeleton(java.lang.String p0, java.util.Locale p1) { return null; }
    public void setContext(android.icu.text.DisplayContext p0) {}
    public void setTimeZone(android.icu.util.TimeZone p0) {}

    public static class HourCycle {
        public int ordinal() { return 0; }
        public android.icu.text.DateFormat.HourCycle[] values() { return null; }
    }
}
