// @generated by gen-shims.py — do not edit by hand
package android.icu.text;

public class DateTimePatternGenerator {
    public android.icu.text.DateFormat.HourCycle getDefaultHourCycle() { return null; }
    public android.icu.text.DateTimePatternGenerator getInstance(java.util.Locale p0) { return null; }
}
