// @generated by gen-shims.py — do not edit by hand
package android.icu.text;

public class DecimalFormatSymbols {
    public java.lang.String[] getDigitStrings() { return null; }
    public android.icu.text.DecimalFormatSymbols getInstance(java.util.Locale p0) { return null; }
    public char getZeroDigit() { return 0; }
}
