// @generated by gen-shims.py — do not edit by hand
package android.icu.text;

public interface ListFormatter {
    java.lang.String format(java.util.Collection p0);
    android.icu.text.ListFormatter getInstance();
    android.icu.text.ListFormatter getInstance(java.util.Locale p0);
}
