// @generated by gen-shims.py — do not edit by hand
package android.icu.text;

public interface RelativeDateTimeFormatter {
    java.lang.String format(double p0, android.icu.text.RelativeDateTimeFormatter.Direction p1, android.icu.text.RelativeDateTimeFormatter.RelativeUnit p2);
    java.lang.String format(android.icu.text.RelativeDateTimeFormatter.Direction p0, android.icu.text.RelativeDateTimeFormatter.AbsoluteUnit p1);
    android.icu.text.RelativeDateTimeFormatter getInstance(java.util.Locale p0);

    public static class AbsoluteUnit {
    }

    public static class Direction {
    }

    public static class RelativeUnit {
    }
}
