// @generated by gen-shims.py — do not edit by hand
package android.icu.text;

public class Transliterator {
    public android.icu.text.Transliterator getInstance(java.lang.String p0) { return null; }
    public java.lang.String transliterate(java.lang.String p0) { return null; }
}
