// @generated by gen-shims.py — do not edit by hand
package android.app.assist;

public class AssistStructure {
    public android.app.assist.AssistStructure.WindowNode getWindowNodeAt(int p0) { return null; }
    public int getWindowNodeCount() { return 0; }
    public int hashCode() { return 0; }

    public static class ViewNode {
        public java.lang.String[] getAutofillHints() { return null; }
        public android.view.autofill.AutofillId getAutofillId() { return null; }
        public java.lang.CharSequence[] getAutofillOptions() { return null; }
        public android.view.autofill.AutofillValue getAutofillValue() { return null; }
        public android.app.assist.AssistStructure.ViewNode getChildAt(int p0) { return null; }
        public int getChildCount() { return 0; }
        public java.lang.String getClassName() { return null; }
        public android.view.ViewStructure.HtmlInfo getHtmlInfo() { return null; }
        public int getInputType() { return 0; }
        public int getVisibility() { return 0; }
        public java.lang.String getWebDomain() { return null; }
        public java.lang.String getWebScheme() { return null; }
    }

    public static class WindowNode {
        public android.app.assist.AssistStructure.ViewNode getRootViewNode() { return null; }
        public java.lang.CharSequence getTitle() { return null; }
    }
}
