// @generated by gen-shims.py — do not edit by hand
package android.adservices.appsetid;

public class AppSetId {
    public java.lang.String getId() { return null; }
    public int getScope() { return 0; }
}
