// @generated by gen-shims.py — do not edit by hand
package android.adservices.appsetid;

public class AppSetIdManager {
    public android.adservices.appsetid.AppSetIdManager get(android.content.Context p0) { return null; }
    public void getAppSetId(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
}
