// @generated by gen-shims.py — do not edit by hand
package android.adservices.adid;

public class AdId {
    public java.lang.String getAdId() { return null; }
    public boolean isLimitAdTrackingEnabled() { return false; }
}
