// @generated by gen-shims.py — do not edit by hand
package android.adservices.adid;

public class AdIdManager {
    public android.adservices.adid.AdIdManager get(android.content.Context p0) { return null; }
    public void getAdId(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
}
