// @generated by gen-shims.py — do not edit by hand
package android.os.storage;

public class StorageVolume {
    public android.content.Intent createAccessIntent(java.lang.String p0) { return null; }
    public java.lang.String getDescription(android.content.Context p0) { return null; }
    public java.io.File getDirectory() { return null; }
    public java.lang.String getUuid() { return null; }
    public boolean isPrimary() { return false; }
    public boolean isRemovable() { return false; }
}
