// @generated by gen-shims.py — do not edit by hand
package android.os.storage;

public class StorageManager {
    public android.os.storage.StorageVolume getStorageVolume(android.net.Uri p0) { return null; }
    public java.util.List getStorageVolumes() { return null; }
}
