// @generated by gen-shims.py — do not edit by hand
package android.app.admin;

public class DevicePolicyManager {
    public void clearDeviceOwnerApp(java.lang.String p0) {}
    public boolean isDeviceOwnerApp(java.lang.String p0) { return false; }
}
