// @generated by gen-shims.py — do not edit by hand
package android.hardware.fingerprint;

public class FingerprintManager {
    public void authenticate(android.hardware.fingerprint.FingerprintManager.CryptoObject p0, android.os.CancellationSignal p1, int p2, android.hardware.fingerprint.FingerprintManager.AuthenticationCallback p3, android.os.Handler p4) {}
    public boolean hasEnrolledFingerprints() { return false; }
    public boolean isHardwareDetected() { return false; }

    public interface AuthenticationCallback {
    }

    public static class AuthenticationResult {
        public android.hardware.fingerprint.FingerprintManager.CryptoObject getCryptoObject() { return null; }
    }

    public static class CryptoObject {
        public javax.crypto.Cipher getCipher() { return null; }
        public javax.crypto.Mac getMac() { return null; }
        public java.security.Signature getSignature() { return null; }
    }
}
