// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class BaseInputConnection {
    public boolean beginBatchEdit() { return false; }
    public void closeConnection() {}
    public boolean commitText(java.lang.CharSequence p0, int p1) { return false; }
    public boolean deleteSurroundingText(int p0, int p1) { return false; }
    public boolean endBatchEdit() { return false; }
    public int getComposingSpanEnd(android.text.Spannable p0) { return 0; }
    public int getComposingSpanStart(android.text.Spannable p0) { return 0; }
    public void removeComposingSpans(android.text.Spannable p0) {}
    public boolean sendKeyEvent(android.view.KeyEvent p0) { return false; }
    public boolean setComposingRegion(int p0, int p1) { return false; }
    public boolean setComposingText(java.lang.CharSequence p0, int p1) { return false; }
    public boolean setSelection(int p0, int p1) { return false; }
}
