// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class CursorAnchorInfo {

    public static class Builder {
        public android.view.inputmethod.CursorAnchorInfo.Builder addCharacterBounds(int p0, float p1, float p2, float p3, float p4, int p5) { return null; }
        public android.view.inputmethod.CursorAnchorInfo.Builder addVisibleLineBounds(float p0, float p1, float p2, float p3) { return null; }
        public android.view.inputmethod.CursorAnchorInfo build() { return null; }
        public void reset() {}
        public android.view.inputmethod.CursorAnchorInfo.Builder setComposingText(int p0, java.lang.CharSequence p1) { return null; }
        public android.view.inputmethod.CursorAnchorInfo.Builder setEditorBoundsInfo(android.view.inputmethod.EditorBoundsInfo p0) { return null; }
        public android.view.inputmethod.CursorAnchorInfo.Builder setInsertionMarkerLocation(float p0, float p1, float p2, float p3, int p4) { return null; }
        public android.view.inputmethod.CursorAnchorInfo.Builder setMatrix(android.graphics.Matrix p0) { return null; }
        public android.view.inputmethod.CursorAnchorInfo.Builder setSelectionRange(int p0, int p1) { return null; }
    }
}
