// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class DeleteGesture {
    public android.graphics.RectF getDeletionArea() { return null; }
    public int getGranularity() { return 0; }
}
