// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class DeleteRangeGesture {
    public android.graphics.RectF getDeletionEndArea() { return null; }
    public android.graphics.RectF getDeletionStartArea() { return null; }
    public int getGranularity() { return 0; }
}
