// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class EditorInfo {
    public java.lang.CharSequence getInitialSelectedText(int p0) { return null; }
    public java.lang.CharSequence getInitialTextAfterCursor(int p0, int p1) { return null; }
    public java.lang.CharSequence getInitialTextBeforeCursor(int p0, int p1) { return null; }
    public boolean isStylusHandwritingEnabled() { return false; }
    public void setInitialSurroundingSubText(java.lang.CharSequence p0, int p1) {}
    public void setStylusHandwritingEnabled(boolean p0) {}
    public void setSupportedHandwritingGesturePreviews(java.util.Set p0) {}
    public void setSupportedHandwritingGestures(java.util.List p0) {}
}
