// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class EditorBoundsInfo {

    public static class Builder {
        public android.view.inputmethod.EditorBoundsInfo build() { return null; }
        public android.view.inputmethod.EditorBoundsInfo.Builder setEditorBounds(android.graphics.RectF p0) { return null; }
        public android.view.inputmethod.EditorBoundsInfo.Builder setHandwritingBounds(android.graphics.RectF p0) { return null; }
    }
}
