// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class InlineSuggestionsRequest {
    public java.util.List getInlinePresentationSpecs() { return null; }
    public int getMaxSuggestionCount() { return 0; }
}
