// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class InputMethodManager {
    public boolean acceptStylusHandwritingDelegation(android.view.View p0) { return false; }
    public void dispatchKeyEventFromInputMethod(android.view.View p0, android.view.KeyEvent p1) {}
    public void displayCompletions(android.view.View p0, android.view.inputmethod.CompletionInfo[] p1) {}
    public android.view.inputmethod.InputMethodSubtype getCurrentInputMethodSubtype() { return null; }
    public java.util.List getEnabledInputMethodList() { return null; }
    public java.util.List getEnabledInputMethodSubtypeList(android.view.inputmethod.InputMethodInfo p0, boolean p1) { return null; }
    public boolean hideSoftInputFromWindow(android.os.IBinder p0, int p1) { return false; }
    public boolean isAcceptingText() { return false; }
    public boolean isActive() { return false; }
    public boolean isActive(android.view.View p0) { return false; }
    public boolean isStylusHandwritingAvailable() { return false; }
    public void prepareStylusHandwritingDelegation(android.view.View p0) {}
    public void restartInput(android.view.View p0) {}
    public void sendAppPrivateCommand(android.view.View p0, java.lang.String p1, android.os.Bundle p2) {}
    public void showInputMethodPicker() {}
    public boolean showSoftInput(android.view.View p0, int p1) { return false; }
    public void startStylusHandwriting(android.view.View p0) {}
    public boolean switchToLastInputMethod(android.os.IBinder p0) { return false; }
    public void toggleSoftInputFromWindow(android.os.IBinder p0, int p1, int p2) {}
    public void updateCursorAnchorInfo(android.view.View p0, android.view.inputmethod.CursorAnchorInfo p1) {}
    public void updateExtractedText(android.view.View p0, int p1, android.view.inputmethod.ExtractedText p2) {}
    public void updateSelection(android.view.View p0, int p1, int p2, int p3, int p4) {}
}
