// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class InputMethodSubtype {
    public java.lang.String getLanguageTag() { return null; }
    public java.lang.String getLocale() { return null; }
    public java.lang.String getMode() { return null; }
}
