// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class InputContentInfo {
    public android.net.Uri getContentUri() { return null; }
    public android.content.ClipDescription getDescription() { return null; }
    public android.net.Uri getLinkUri() { return null; }
    public void releasePermission() {}
    public void requestPermission() {}
}
