// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class InsertGesture {
    public android.graphics.PointF getInsertionPoint() { return null; }
    public java.lang.String getTextToInsert() { return null; }
}
