// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class RemoveSpaceGesture {
    public android.graphics.PointF getEndPoint() { return null; }
    public android.graphics.PointF getStartPoint() { return null; }
}
