// @generated by gen-shims.py — do not edit by hand
package android.view.inputmethod;

public class SelectRangeGesture {
    public int getGranularity() { return 0; }
    public android.graphics.RectF getSelectionEndArea() { return null; }
    public android.graphics.RectF getSelectionStartArea() { return null; }
}
