// @generated by gen-shims.py — do not edit by hand
package android.view.textservice;

public class SpellCheckerSession {
    public void close() {}
    public void getSentenceSuggestions(android.view.textservice.TextInfo[] p0, int p1) {}

    public interface SpellCheckerSessionListener {
    }
}
