// @generated by gen-shims.py — do not edit by hand
package android.view.textservice;

public class SuggestionsInfo {
    public java.lang.String getSuggestionAt(int p0) { return null; }
    public int getSuggestionsCount() { return 0; }
}
