// @generated by gen-shims.py — do not edit by hand
package android.hardware.input;

public class InputManager {
    public android.view.InputDevice getInputDevice(int p0) { return null; }
    public int[] getInputDeviceIds() { return null; }
    public void registerInputDeviceListener(android.hardware.input.InputManager.InputDeviceListener p0, android.os.Handler p1) {}
    public void unregisterInputDeviceListener(android.hardware.input.InputManager.InputDeviceListener p0) {}

    public interface InputDeviceListener {
    }
}
