// @generated by gen-shims.py — do not edit by hand
package android.accessibilityservice;

public class AccessibilityServiceInfo {
    public boolean getCanRetrieveWindowContent() { return false; }
    public int getCapabilities() { return 0; }
    public java.lang.String getDescription() { return null; }
    public java.lang.String getId() { return null; }
    public android.content.pm.ResolveInfo getResolveInfo() { return null; }
    public java.lang.String getSettingsActivityName() { return null; }
    public java.lang.String loadDescription(android.content.pm.PackageManager p0) { return null; }
}
