// @generated by gen-shims.py — do not edit by hand
package android.media.tv;

public class TvContentRating {
    public java.lang.String flattenToString() { return null; }
    public android.media.tv.TvContentRating unflattenFromString(java.lang.String p0) { return null; }
}
