// @generated by gen-shims.py — do not edit by hand
package android.media.tv;

public class TvInputService {
    public void attachBaseContext(android.content.Context p0) {}
    public android.content.Context getApplicationContext() { return null; }
    public void onDestroy() {}

    public static class Session {
    }
}
