// @generated by gen-shims.py — do not edit by hand
package android.hardware.biometrics;

public class BiometricManager {
    public int canAuthenticate() { return 0; }
    public int canAuthenticate(int p0) { return 0; }
}
