// @generated by gen-shims.py — do not edit by hand
package android.hardware.biometrics;

public class BiometricPrompt {
    public void authenticate(android.hardware.biometrics.BiometricPrompt.CryptoObject p0, android.os.CancellationSignal p1, java.util.concurrent.Executor p2, android.hardware.biometrics.BiometricPrompt.AuthenticationCallback p3) {}
    public void authenticate(android.os.CancellationSignal p0, java.util.concurrent.Executor p1, android.hardware.biometrics.BiometricPrompt.AuthenticationCallback p2) {}

    public interface AuthenticationCallback {
        void onAuthenticationError(int p0, java.lang.CharSequence p1);
        void onAuthenticationSucceeded(android.hardware.biometrics.BiometricPrompt.AuthenticationResult p0);
    }

    public static class AuthenticationResult {
        public int getAuthenticationType() { return 0; }
        public android.hardware.biometrics.BiometricPrompt.CryptoObject getCryptoObject() { return null; }
    }

    public static class Builder {
        public android.hardware.biometrics.BiometricPrompt build() { return null; }
        public android.hardware.biometrics.BiometricPrompt.Builder setAllowedAuthenticators(int p0) { return null; }
        public android.hardware.biometrics.BiometricPrompt.Builder setConfirmationRequired(boolean p0) { return null; }
        public android.hardware.biometrics.BiometricPrompt.Builder setDescription(java.lang.CharSequence p0) { return null; }
        public android.hardware.biometrics.BiometricPrompt.Builder setDeviceCredentialAllowed(boolean p0) { return null; }
        public android.hardware.biometrics.BiometricPrompt.Builder setNegativeButton(java.lang.CharSequence p0, java.util.concurrent.Executor p1, android.content.DialogInterface.OnClickListener p2) { return null; }
        public android.hardware.biometrics.BiometricPrompt.Builder setSubtitle(java.lang.CharSequence p0) { return null; }
        public android.hardware.biometrics.BiometricPrompt.Builder setTitle(java.lang.CharSequence p0) { return null; }
    }

    public static class CryptoObject {
        public javax.crypto.Cipher getCipher() { return null; }
        public android.security.identity.IdentityCredential getIdentityCredential() { return null; }
        public javax.crypto.Mac getMac() { return null; }
        public long getOperationHandle() { return 0; }
        public android.security.identity.PresentationSession getPresentationSession() { return null; }
        public java.security.Signature getSignature() { return null; }
    }
}
