// @generated by gen-shims.py — do not edit by hand
package android.service.notification;

public class StatusBarNotification {
    public int getId() { return 0; }
    public android.app.Notification getNotification() { return null; }
    public java.lang.String getTag() { return null; }
}
