// @generated by gen-shims.py — do not edit by hand
package android.net.ssl;

public class SSLSockets {
    public boolean isSupportedSocket(javax.net.ssl.SSLSocket p0) { return false; }
    public void setUseSessionTickets(javax.net.ssl.SSLSocket p0, boolean p1) {}
}
