// @generated by gen-shims.py — do not edit by hand
package android.icu.number;

public class FormattedNumber {
    public android.icu.util.MeasureUnit getOutputUnit() { return null; }
    public java.lang.String toString() { return null; }
}
