// @generated by gen-shims.py — do not edit by hand
package android.icu.number;

public interface LocalizedNumberFormatter {
    android.icu.number.FormattedNumber format(long p0);
    android.icu.number.NumberFormatterSettings precision(android.icu.number.Precision p0);
    android.icu.number.NumberFormatterSettings unit(android.icu.util.MeasureUnit p0);
    android.icu.number.NumberFormatterSettings unitWidth(android.icu.number.NumberFormatter.UnitWidth p0);
}
