// @generated by gen-shims.py — do not edit by hand
package android.icu.number;

public interface NumberFormatter {
    android.icu.number.UnlocalizedNumberFormatter with();
    android.icu.number.LocalizedNumberFormatter withLocale(android.icu.util.ULocale p0);

    public static class UnitWidth {
    }
}
