// @generated by gen-shims.py — do not edit by hand
package android.icu.number;

public interface UnlocalizedNumberFormatter {
    android.icu.number.LocalizedNumberFormatter locale(java.util.Locale p0);
    android.icu.number.NumberFormatterSettings unit(android.icu.util.MeasureUnit p0);
    android.icu.number.NumberFormatterSettings usage(java.lang.String p0);
}
