// @generated by gen-shims.py — do not edit by hand
package android.util;

public class ArraySet {
    public boolean add(java.lang.Object p0) { return false; }
    public boolean contains(java.lang.Object p0) { return false; }
}
