// @generated by gen-shims.py — do not edit by hand
package android.util;

public class ArrayMap {
    public void clear() {}
    public boolean containsKey(java.lang.Object p0) { return false; }
    public java.lang.Object get(java.lang.Object p0) { return null; }
    public java.util.Set keySet() { return null; }
    public java.lang.Object put(java.lang.Object p0, java.lang.Object p1) { return null; }
    public java.lang.Object remove(java.lang.Object p0) { return null; }
}
