// @generated by gen-shims.py — do not edit by hand
package android.util;

public class AtomicFile {
    public void failWrite(java.io.FileOutputStream p0) {}
    public void finishWrite(java.io.FileOutputStream p0) {}
    public byte[] readFully() { return null; }
    public java.io.FileOutputStream startWrite() { return null; }
}
