// @generated by gen-shims.py — do not edit by hand
package android.util;

public class AttributeSet {
    public boolean getAttributeBooleanValue(int p0, boolean p1) { return false; }
    public boolean getAttributeBooleanValue(java.lang.String p0, java.lang.String p1, boolean p2) { return false; }
    public int getAttributeCount() { return 0; }
    public int getAttributeIntValue(java.lang.String p0, java.lang.String p1, int p2) { return 0; }
    public int getAttributeIntValue(int p0, int p1) { return 0; }
    public int getAttributeListValue(int p0, java.lang.String[] p1, int p2) { return 0; }
    public java.lang.String getAttributeName(int p0) { return null; }
    public int getAttributeNameResource(int p0) { return 0; }
    public int getAttributeResourceValue(int p0, int p1) { return 0; }
    public java.lang.String getAttributeValue(java.lang.String p0, java.lang.String p1) { return null; }
    public java.lang.String getAttributeValue(int p0) { return null; }
    public java.lang.String getClassAttribute() { return null; }
    public java.lang.String getPositionDescription() { return null; }
    public int getStyleAttribute() { return 0; }
}
