// @generated by gen-shims.py — do not edit by hand
package android.util;

public class FloatProperty {
    public java.lang.Object get(java.lang.Object p0) { return null; }
    public java.lang.String getName() { return null; }
    public void setValue(java.lang.Object p0, float p1) {}
}
