// @generated by gen-shims.py — do not edit by hand
package android.util;

public class FloatMath {
    public float cos(float p0) { return 0f; }
    public float sin(float p0) { return 0f; }
    public float sqrt(float p0) { return 0f; }
}
