// @generated by gen-shims.py — do not edit by hand
package android.util;

public class JsonReader {
    public void beginArray() {}
    public void beginObject() {}
    public void close() {}
    public void endArray() {}
    public void endObject() {}
    public boolean hasNext() { return false; }
    public boolean nextBoolean() { return false; }
    public double nextDouble() { return 0.0; }
    public int nextInt() { return 0; }
    public long nextLong() { return 0; }
    public java.lang.String nextName() { return null; }
    public java.lang.String nextString() { return null; }
    public android.util.JsonToken peek() { return null; }
    public void skipValue() {}
}
