// @generated by gen-shims.py — do not edit by hand
package android.util;

public class JsonWriter {
    public android.util.JsonWriter beginArray() { return null; }
    public android.util.JsonWriter beginObject() { return null; }
    public void close() {}
    public android.util.JsonWriter endArray() { return null; }
    public android.util.JsonWriter endObject() { return null; }
    public void flush() {}
    public android.util.JsonWriter name(java.lang.String p0) { return null; }
    public android.util.JsonWriter nullValue() { return null; }
    public android.util.JsonWriter value(double p0) { return null; }
}
