// @generated by gen-shims.py — do not edit by hand
package android.util;

public class LongSparseArray {
    public void clear() {}
    public java.lang.Object get(long p0) { return null; }
    public int indexOfKey(long p0) { return 0; }
    public int indexOfValue(java.lang.Object p0) { return 0; }
    public long keyAt(int p0) { return 0; }
    public void put(long p0, java.lang.Object p1) {}
    public void remove(long p0) {}
    public void removeAt(int p0) {}
    public int size() { return 0; }
    public java.lang.Object valueAt(int p0) { return null; }
}
