// @generated by gen-shims.py — do not edit by hand
package android.util;

public class LruCache {
    public void evictAll() {}
    public java.lang.Object get(java.lang.Object p0) { return null; }
    public int maxSize() { return 0; }
    public java.lang.Object put(java.lang.Object p0, java.lang.Object p1) { return null; }
    public java.lang.Object remove(java.lang.Object p0) { return null; }
    public int size() { return 0; }
    public void trimToSize(int p0) {}
}
