// @generated by gen-shims.py — do not edit by hand
package android.util;

public class Pair {
    public android.util.Pair create(java.lang.Object p0, java.lang.Object p1) { return null; }
    public boolean equals(java.lang.Object p0) { return false; }
}
