// @generated by gen-shims.py — do not edit by hand
package android.util;

public class Property {
    public java.lang.Object get(java.lang.Object p0) { return null; }
    public java.lang.String getName() { return null; }
    public android.util.Property of(java.lang.Class p0, java.lang.Class p1, java.lang.String p2) { return null; }
    public void set(java.lang.Object p0, java.lang.Object p1) {}
}
