// @generated by gen-shims.py — do not edit by hand
package android.util;

public class Range {
    public java.lang.Comparable clamp(java.lang.Comparable p0) { return null; }
    public android.util.Range extend(android.util.Range p0) { return null; }
    public java.lang.Comparable getLower() { return null; }
    public java.lang.Comparable getUpper() { return null; }
    public android.util.Range intersect(android.util.Range p0) { return null; }
}
