// @generated by gen-shims.py — do not edit by hand
package android.util;

public class SparseBooleanArray {
    public void append(int p0, boolean p1) {}
    public void clear() {}
    public android.util.SparseBooleanArray clone() { return null; }
    public void delete(int p0) {}
    public boolean equals(java.lang.Object p0) { return false; }
    public boolean get(int p0) { return false; }
    public boolean get(int p0, boolean p1) { return false; }
    public int hashCode() { return 0; }
    public int indexOfKey(int p0) { return 0; }
    public int indexOfValue(boolean p0) { return 0; }
    public int keyAt(int p0) { return 0; }
    public void put(int p0, boolean p1) {}
    public int size() { return 0; }
    public boolean valueAt(int p0) { return false; }
}
