// @generated by gen-shims.py — do not edit by hand
package android.util;

public class SparseIntArray {
    public void append(int p0, int p1) {}
    public void clear() {}
    public void delete(int p0) {}
    public int get(int p0) { return 0; }
    public int get(int p0, int p1) { return 0; }
    public int indexOfKey(int p0) { return 0; }
    public int indexOfValue(int p0) { return 0; }
    public int keyAt(int p0) { return 0; }
    public void put(int p0, int p1) {}
    public void removeAt(int p0) {}
    public int size() { return 0; }
    public int valueAt(int p0) { return 0; }
}
