// @generated by gen-shims.py — do not edit by hand
package android.util;

public class StatsEvent {
    public android.util.StatsEvent.Builder newBuilder() { return null; }

    public static class Builder {
        public android.util.StatsEvent.Builder addBooleanAnnotation(byte p0, boolean p1) { return null; }
        public android.util.StatsEvent build() { return null; }
        public android.util.StatsEvent.Builder setAtomId(int p0) { return null; }
        public android.util.StatsEvent.Builder usePooledBuffer() { return null; }
        public android.util.StatsEvent.Builder writeBoolean(boolean p0) { return null; }
        public android.util.StatsEvent.Builder writeInt(int p0) { return null; }
        public android.util.StatsEvent.Builder writeLong(long p0) { return null; }
        public android.util.StatsEvent.Builder writeLongArray(long[] p0) { return null; }
        public android.util.StatsEvent.Builder writeString(java.lang.String p0) { return null; }
    }
}
