// @generated by gen-shims.py — do not edit by hand
package android.util;

public class StateSet {
    public boolean stateSetMatches(int[] p0, int[] p1) { return false; }
    public int[] trimStateSet(int[] p0, int p1) { return null; }
}
