// @generated by gen-shims.py — do not edit by hand
package android.util;

public class TypedValue {
    public float applyDimension(int p0, float p1, android.util.DisplayMetrics p2) { return 0f; }
    public int complexToDimensionPixelSize(int p0, android.util.DisplayMetrics p1) { return 0; }
    public float complexToFloat(int p0) { return 0f; }
    public float deriveDimension(int p0, float p1, android.util.DisplayMetrics p2) { return 0f; }
    public int getComplexUnit() { return 0; }
    public float getDimension(android.util.DisplayMetrics p0) { return 0f; }
    public float getFloat() { return 0f; }
    public float getFraction(float p0, float p1) { return 0f; }
}
