// @generated by gen-shims.py — do not edit by hand
package android.util;

public class Xml {
    public android.util.AttributeSet asAttributeSet(org.xmlpull.v1.XmlPullParser p0) { return null; }
    public org.xmlpull.v1.XmlPullParser newPullParser() { return null; }
    public org.xmlpull.v1.XmlSerializer newSerializer() { return null; }
}
