// @generated by gen-shims.py — do not edit by hand
package android.app.sdksandbox.sdkprovider;

public class SdkSandboxController {
    public java.lang.String getClientPackageName() { return null; }
}
