// @generated by gen-shims.py — do not edit by hand
package android.hardware.usb;

public class UsbDevice {
    public android.hardware.usb.UsbInterface getInterface(int p0) { return null; }
    public java.lang.String getManufacturerName() { return null; }
    public java.lang.String getProductName() { return null; }
}
