// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class ConsoleMessage {
    public int lineNumber() { return 0; }
    public java.lang.String message() { return null; }
    public android.webkit.ConsoleMessage.MessageLevel messageLevel() { return null; }
    public java.lang.String sourceId() { return null; }

    public static class MessageLevel {
        public int ordinal() { return 0; }
        public android.webkit.ConsoleMessage.MessageLevel[] values() { return null; }
    }
}
