// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class CookieSyncManager {
    public android.webkit.CookieSyncManager createInstance(android.content.Context p0) { return null; }
    public void sync() {}
}
