// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class CookieManager {
    public boolean acceptThirdPartyCookies(android.webkit.WebView p0) { return false; }
    public java.lang.String getCookie(java.lang.String p0) { return null; }
    public android.webkit.CookieManager getInstance() { return null; }
    public void removeAllCookies(android.webkit.ValueCallback p0) {}
    public void removeExpiredCookie() {}
    public void setAcceptThirdPartyCookies(android.webkit.WebView p0, boolean p1) {}
    public void setCookie(java.lang.String p0, java.lang.String p1) {}
}
