// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class GeolocationPermissions {

    public interface Callback {
        void invoke(java.lang.String p0, boolean p1, boolean p2);
    }
}
