// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class MimeTypeMap {
    public java.lang.String getExtensionFromMimeType(java.lang.String p0) { return null; }
    public java.lang.String getFileExtensionFromUrl(java.lang.String p0) { return null; }
    public java.lang.String getMimeTypeFromExtension(java.lang.String p0) { return null; }
    public android.webkit.MimeTypeMap getSingleton() { return null; }
}
