// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class RenderProcessGoneDetail {
    public boolean didCrash() { return false; }
    public int rendererPriorityAtExit() { return 0; }
}
