// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class SafeBrowsingResponse {
    public void backToSafety(boolean p0) {}
    public void proceed(boolean p0) {}
    public void showInterstitial(boolean p0) {}
}
