// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class ServiceWorkerController {
    public android.webkit.ServiceWorkerController getInstance() { return null; }
    public android.webkit.ServiceWorkerWebSettings getServiceWorkerWebSettings() { return null; }
    public void setServiceWorkerClient(android.webkit.ServiceWorkerClient p0) {}
}
