// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class ServiceWorkerWebSettings {
    public boolean getAllowContentAccess() { return false; }
    public boolean getAllowFileAccess() { return false; }
    public boolean getBlockNetworkLoads() { return false; }
    public int getCacheMode() { return 0; }
    public void setAllowContentAccess(boolean p0) {}
    public void setAllowFileAccess(boolean p0) {}
    public void setBlockNetworkLoads(boolean p0) {}
    public void setCacheMode(int p0) {}
}
