// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class TracingConfig {

    public static class Builder {
        public android.webkit.TracingConfig.Builder addCategories(java.util.Collection p0) { return null; }
        public android.webkit.TracingConfig build() { return null; }
        public android.webkit.TracingConfig.Builder setTracingMode(int p0) { return null; }
    }
}
