// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class TracingController {
    public android.webkit.TracingController getInstance() { return null; }
    public boolean isTracing() { return false; }
    public void start(android.webkit.TracingConfig p0) {}
    public boolean stop(java.io.OutputStream p0, java.util.concurrent.Executor p1) { return false; }
}
