// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class URLUtil {
    public java.lang.String guessFileName(java.lang.String p0, java.lang.String p1, java.lang.String p2) { return null; }
    public boolean isContentUrl(java.lang.String p0) { return false; }
    public boolean isHttpUrl(java.lang.String p0) { return false; }
    public boolean isHttpsUrl(java.lang.String p0) { return false; }
    public boolean isNetworkUrl(java.lang.String p0) { return false; }
    public boolean isValidUrl(java.lang.String p0) { return false; }
}
