// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class WebChromeClient {
    public boolean onConsoleMessage(android.webkit.ConsoleMessage p0) { return false; }
    public boolean onCreateWindow(android.webkit.WebView p0, boolean p1, boolean p2, android.os.Message p3) { return false; }
    public boolean onJsConfirm(android.webkit.WebView p0, java.lang.String p1, java.lang.String p2, android.webkit.JsResult p3) { return false; }
    public void onPermissionRequest(android.webkit.PermissionRequest p0) {}
    public void onProgressChanged(android.webkit.WebView p0, int p1) {}

    public interface CustomViewCallback {
        void onCustomViewHidden();
    }
}
