// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class WebMessage {
    public java.lang.String getData() { return null; }
    public android.webkit.WebMessagePort[] getPorts() { return null; }
}
