// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class WebMessagePort {
    public void close() {}
    public void postMessage(android.webkit.WebMessage p0) {}
    public void setWebMessageCallback(android.webkit.WebMessagePort.WebMessageCallback p0) {}
    public void setWebMessageCallback(android.webkit.WebMessagePort.WebMessageCallback p0, android.os.Handler p1) {}

    public interface WebMessageCallback {
    }
}
