// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class WebResourceError {
    public java.lang.CharSequence getDescription() { return null; }
    public int getErrorCode() { return 0; }
}
