// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class WebResourceResponse {
    public java.lang.String getReasonPhrase() { return null; }
    public java.util.Map getResponseHeaders() { return null; }
    public int getStatusCode() { return 0; }
    public void setResponseHeaders(java.util.Map p0) {}
}
