// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class WebResourceRequest {
    public java.lang.String getMethod() { return null; }
    public java.util.Map getRequestHeaders() { return null; }
    public android.net.Uri getUrl() { return null; }
    public boolean isForMainFrame() { return false; }
    public boolean isRedirect() { return false; }
}
