// @generated by gen-shims.py — do not edit by hand
package android.webkit;

public class WebViewClient {
    public void doUpdateVisitedHistory(android.webkit.WebView p0, java.lang.String p1, boolean p2) {}
    public void onFormResubmission(android.webkit.WebView p0, android.os.Message p1, android.os.Message p2) {}
    public void onLoadResource(android.webkit.WebView p0, java.lang.String p1) {}
    public void onPageCommitVisible(android.webkit.WebView p0, java.lang.String p1) {}
    public void onPageFinished(android.webkit.WebView p0, java.lang.String p1) {}
    public void onPageStarted(android.webkit.WebView p0, java.lang.String p1, android.graphics.Bitmap p2) {}
    public void onReceivedClientCertRequest(android.webkit.WebView p0, android.webkit.ClientCertRequest p1) {}
    public void onReceivedError(android.webkit.WebView p0, int p1, java.lang.String p2, java.lang.String p3) {}
    public void onReceivedError(android.webkit.WebView p0, android.webkit.WebResourceRequest p1, android.webkit.WebResourceError p2) {}
    public void onReceivedHttpAuthRequest(android.webkit.WebView p0, android.webkit.HttpAuthHandler p1, java.lang.String p2, java.lang.String p3) {}
    public void onReceivedHttpError(android.webkit.WebView p0, android.webkit.WebResourceRequest p1, android.webkit.WebResourceResponse p2) {}
    public void onReceivedLoginRequest(android.webkit.WebView p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) {}
    public void onReceivedSslError(android.webkit.WebView p0, android.webkit.SslErrorHandler p1, android.net.http.SslError p2) {}
    public boolean onRenderProcessGone(android.webkit.WebView p0, android.webkit.RenderProcessGoneDetail p1) { return false; }
    public void onSafeBrowsingHit(android.webkit.WebView p0, android.webkit.WebResourceRequest p1, int p2, android.webkit.SafeBrowsingResponse p3) {}
    public void onScaleChanged(android.webkit.WebView p0, float p1, float p2) {}
    public void onTooManyRedirects(android.webkit.WebView p0, android.os.Message p1, android.os.Message p2) {}
    public void onUnhandledKeyEvent(android.webkit.WebView p0, android.view.KeyEvent p1) {}
    public android.webkit.WebResourceResponse shouldInterceptRequest(android.webkit.WebView p0, android.webkit.WebResourceRequest p1) { return null; }
    public boolean shouldOverrideKeyEvent(android.webkit.WebView p0, android.view.KeyEvent p1) { return false; }
    public boolean shouldOverrideUrlLoading(android.webkit.WebView p0, java.lang.String p1) { return false; }
}
