// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class BlendModeColorFilter {
    public int getColor() { return 0; }
    public android.graphics.BlendMode getMode() { return null; }
}
