// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class BlendMode {
    public int hashCode() { return 0; }
    public int ordinal() { return 0; }
    public android.graphics.BlendMode[] values() { return null; }
}
