// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Color {
    public int HSVToColor(float[] p0) { return 0; }
    public int HSVToColor(int p0, float[] p1) { return 0; }
    public void RGBToHSV(int p0, int p1, int p2, float[] p3) {}
    public int alpha(int p0) { return 0; }
    public float alpha() { return 0f; }
    public int argb(int p0, int p1, int p2, int p3) { return 0; }
    public int blue(int p0) { return 0; }
    public android.graphics.ColorSpace colorSpace(long p0) { return null; }
    public void colorToHSV(int p0, float[] p1) {}
    public long convert(int p0, android.graphics.ColorSpace p1) { return 0; }
    public android.graphics.Color convert(android.graphics.ColorSpace p0) { return null; }
    public android.graphics.ColorSpace getColorSpace() { return null; }
    public float getComponent(int p0) { return 0f; }
    public int getComponentCount() { return 0; }
    public float[] getComponents() { return null; }
    public android.graphics.ColorSpace.Model getModel() { return null; }
    public int green(int p0) { return 0; }
    public boolean isSrgb(long p0) { return false; }
    public boolean isWideGamut(long p0) { return false; }
    public float luminance(int p0) { return 0f; }
    public long pack(int p0) { return 0; }
    public int parseColor(java.lang.String p0) { return 0; }
    public int red(int p0) { return 0; }
    public int rgb(int p0, int p1, int p2) { return 0; }
    public int toArgb() { return 0; }
    public int toArgb(long p0) { return 0; }
    public android.graphics.Color valueOf(int p0) { return null; }
    public android.graphics.Color valueOf(float[] p0, android.graphics.ColorSpace p1) { return null; }
    public android.graphics.Color valueOf(float p0, float p1, float p2, float p3) { return null; }
}
