// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class ColorSpace {
    public boolean equals(java.lang.Object p0) { return false; }
    public android.graphics.ColorSpace get(android.graphics.ColorSpace.Named p0) { return null; }
    public int getId() { return 0; }
    public float getMaxValue(int p0) { return 0f; }
    public float getMinValue(int p0) { return 0f; }
    public boolean isWideGamut() { return false; }

    public static class Model {
    }

    public static class Named {
        public int ordinal() { return 0; }
    }

    public static class Rgb {
        public java.util.function.DoubleUnaryOperator getEotf() { return null; }
        public int getId() { return 0; }
        public float getMaxValue(int p0) { return 0f; }
        public float getMinValue(int p0) { return 0f; }
        public java.lang.String getName() { return null; }
        public java.util.function.DoubleUnaryOperator getOetf() { return null; }
        public float[] getPrimaries() { return null; }
        public Object getTransferParameters() { return null; }
        public float[] getTransform() { return null; }
        public float[] getWhitePoint() { return null; }
    }

    public static class TransferParameters {
    }
}
