// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class ColorMatrix {
    public float[] getArray() { return null; }
    public void postConcat(android.graphics.ColorMatrix p0) {}
    public void reset() {}
    public void set(float[] p0) {}
    public void setSaturation(float p0) {}
    public void setScale(float p0, float p1, float p2, float p3) {}
}
