// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Gainmap {
    public float getDisplayRatioForFullHdr() { return 0f; }
    public float[] getEpsilonHdr() { return null; }
    public float[] getEpsilonSdr() { return null; }
    public android.graphics.Bitmap getGainmapContents() { return null; }
    public float[] getGamma() { return null; }
    public float getMinDisplayRatioForHdrTransition() { return 0f; }
    public float[] getRatioMax() { return null; }
    public float[] getRatioMin() { return null; }
    public void setDisplayRatioForFullHdr(float p0) {}
    public void setEpsilonHdr(float p0, float p1, float p2) {}
    public void setEpsilonSdr(float p0, float p1, float p2) {}
    public void setGamma(float p0, float p1, float p2) {}
    public void setMinDisplayRatioForHdrTransition(float p0) {}
    public void setRatioMax(float p0, float p1, float p2) {}
    public void setRatioMin(float p0, float p1, float p2) {}
}
