// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class ImageDecoder {
    public android.graphics.ImageDecoder.Source createSource(java.nio.ByteBuffer p0) { return null; }
    public android.graphics.ImageDecoder.Source createSource(android.content.res.AssetManager p0, java.lang.String p1) { return null; }
    public android.graphics.Bitmap decodeBitmap(android.graphics.ImageDecoder.Source p0, android.graphics.ImageDecoder.OnHeaderDecodedListener p1) { return null; }
    public android.graphics.drawable.Drawable decodeDrawable(android.graphics.ImageDecoder.Source p0, android.graphics.ImageDecoder.OnHeaderDecodedListener p1) { return null; }
    public void setAllocator(int p0) {}
    public void setMemorySizePolicy(int p0) {}
    public void setOnPartialImageListener(android.graphics.ImageDecoder.OnPartialImageListener p0) {}
    public void setPostProcessor(android.graphics.PostProcessor p0) {}
    public void setTargetColorSpace(android.graphics.ColorSpace p0) {}
    public void setTargetSize(int p0, int p1) {}
    public void setUnpremultipliedRequired(boolean p0) {}

    public static class DecodeException {
    }

    public static class ImageInfo {
        public android.graphics.ColorSpace getColorSpace() { return null; }
        public android.util.Size getSize() { return null; }
    }

    public interface OnHeaderDecodedListener {
    }

    public interface OnPartialImageListener {
    }

    public static class Source {
    }
}
