// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class LightingColorFilter {
    public int getColorAdd() { return 0; }
    public int getColorMultiply() { return 0; }
}
