// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Matrix {
    public boolean equals(java.lang.Object p0) { return false; }
    public void getValues(float[] p0) {}
    public boolean invert(android.graphics.Matrix p0) { return false; }
    public boolean isIdentity() { return false; }
    public void mapPoints(float[] p0) {}
    public boolean mapRect(android.graphics.RectF p0) { return false; }
    public boolean mapRect(android.graphics.RectF p0, android.graphics.RectF p1) { return false; }
    public void mapVectors(float[] p0) {}
    public boolean postConcat(android.graphics.Matrix p0) { return false; }
    public boolean postRotate(float p0) { return false; }
    public boolean postRotate(float p0, float p1, float p2) { return false; }
    public boolean postScale(float p0, float p1) { return false; }
    public boolean postScale(float p0, float p1, float p2, float p3) { return false; }
    public boolean postTranslate(float p0, float p1) { return false; }
    public boolean preConcat(android.graphics.Matrix p0) { return false; }
    public boolean preRotate(float p0) { return false; }
    public boolean preRotate(float p0, float p1, float p2) { return false; }
    public boolean preScale(float p0, float p1) { return false; }
    public boolean preSkew(float p0, float p1) { return false; }
    public boolean preTranslate(float p0, float p1) { return false; }
    public void reset() {}
    public void set(android.graphics.Matrix p0) {}
    public boolean setRectToRect(android.graphics.RectF p0, android.graphics.RectF p1, android.graphics.Matrix.ScaleToFit p2) { return false; }
    public void setRotate(float p0, float p1, float p2) {}
    public void setRotate(float p0) {}
    public void setScale(float p0, float p1) {}
    public void setScale(float p0, float p1, float p2, float p3) {}
    public void setSkew(float p0, float p1) {}
    public void setTranslate(float p0, float p1) {}
    public void setValues(float[] p0) {}
    public java.lang.String toShortString() { return null; }
    public java.lang.String toString() { return null; }

    public static class ScaleToFit {
    }
}
