// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Movie {
    public android.graphics.Movie decodeStream(java.io.InputStream p0) { return null; }
    public void draw(android.graphics.Canvas p0, float p1, float p2, android.graphics.Paint p3) {}
    public int duration() { return 0; }
    public int height() { return 0; }
    public boolean isOpaque() { return false; }
    public boolean setTime(int p0) { return false; }
    public int width() { return 0; }
}
