// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class PathMeasure {
    public float getLength() { return 0f; }
    public boolean getPosTan(float p0, float[] p1, float[] p2) { return false; }
    public boolean getSegment(float p0, float p1, android.graphics.Path p2, boolean p3) { return false; }
    public boolean nextContour() { return false; }
    public void setPath(android.graphics.Path p0, boolean p1) {}
}
