// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class PathIterator {
    public boolean hasNext() { return false; }
    public int next(float[] p0, int p1) { return 0; }
    public int peek() { return 0; }
}
