// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Path {
    public void addArc(android.graphics.RectF p0, float p1, float p2) {}
    public void addCircle(float p0, float p1, float p2, android.graphics.Path.Direction p3) {}
    public void addOval(android.graphics.RectF p0, android.graphics.Path.Direction p1) {}
    public void addPath(android.graphics.Path p0) {}
    public void addPath(android.graphics.Path p0, android.graphics.Matrix p1) {}
    public void addPath(android.graphics.Path p0, float p1, float p2) {}
    public void addRect(android.graphics.RectF p0, android.graphics.Path.Direction p1) {}
    public void addRoundRect(android.graphics.RectF p0, float p1, float p2, android.graphics.Path.Direction p3) {}
    public void addRoundRect(android.graphics.RectF p0, float[] p1, android.graphics.Path.Direction p2) {}
    public float[] approximate(float p0) { return null; }
    public void arcTo(android.graphics.RectF p0, float p1, float p2) {}
    public void arcTo(android.graphics.RectF p0, float p1, float p2, boolean p3) {}
    public void close() {}
    public void computeBounds(android.graphics.RectF p0, boolean p1) {}
    public void cubicTo(float p0, float p1, float p2, float p3, float p4, float p5) {}
    public android.graphics.Path.FillType getFillType() { return null; }
    public android.graphics.PathIterator getPathIterator() { return null; }
    public boolean isConvex() { return false; }
    public boolean isEmpty() { return false; }
    public void lineTo(float p0, float p1) {}
    public void moveTo(float p0, float p1) {}
    public void offset(float p0, float p1) {}
    public boolean op(android.graphics.Path p0, android.graphics.Path.Op p1) { return false; }
    public boolean op(android.graphics.Path p0, android.graphics.Path p1, android.graphics.Path.Op p2) { return false; }
    public void quadTo(float p0, float p1, float p2, float p3) {}
    public void rCubicTo(float p0, float p1, float p2, float p3, float p4, float p5) {}
    public void rLineTo(float p0, float p1) {}
    public void rMoveTo(float p0, float p1) {}
    public void rQuadTo(float p0, float p1, float p2, float p3) {}
    public void reset() {}
    public void rewind() {}
    public void set(android.graphics.Path p0) {}
    public void setFillType(android.graphics.Path.FillType p0) {}
    public void transform(android.graphics.Matrix p0) {}
    public void transform(android.graphics.Matrix p0, android.graphics.Path p1) {}

    public static class Direction {
    }

    public static class FillType {
    }

    public static class Op {
    }
}
