// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Picture {
    public android.graphics.Canvas beginRecording(int p0, int p1) { return null; }
    public void draw(android.graphics.Canvas p0) {}
    public void endRecording() {}
}
