// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class PointF {
    public boolean equals(float p0, float p1) { return false; }
    public boolean equals(java.lang.Object p0) { return false; }
    public int hashCode() { return 0; }
    public float length() { return 0f; }
    public void offset(float p0, float p1) {}
    public void set(float p0, float p1) {}
    public void set(android.graphics.PointF p0) {}
}
