// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Point {
    public boolean equals(java.lang.Object p0) { return false; }
    public int hashCode() { return 0; }
    public void offset(int p0, int p1) {}
    public void set(int p0, int p1) {}
}
