// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class PorterDuff {

    public static class Mode {
        public int hashCode() { return 0; }
        public java.lang.String name() { return null; }
        public android.graphics.PorterDuff.Mode valueOf(java.lang.String p0) { return null; }
    }
}
