// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Rect {
    public int centerX() { return 0; }
    public int centerY() { return 0; }
    public boolean contains(int p0, int p1) { return false; }
    public boolean contains(android.graphics.Rect p0) { return false; }
    public boolean equals(java.lang.Object p0) { return false; }
    public float exactCenterX() { return 0f; }
    public float exactCenterY() { return 0f; }
    public int hashCode() { return 0; }
    public int height() { return 0; }
    public void inset(int p0, int p1) {}
    public boolean intersect(int p0, int p1, int p2, int p3) { return false; }
    public boolean intersect(android.graphics.Rect p0) { return false; }
    public boolean intersects(int p0, int p1, int p2, int p3) { return false; }
    public boolean isEmpty() { return false; }
    public void offset(int p0, int p1) {}
    public void offsetTo(int p0, int p1) {}
    public void set(int p0, int p1, int p2, int p3) {}
    public void set(android.graphics.Rect p0) {}
    public void setEmpty() {}
    public java.lang.String toShortString() { return null; }
    public java.lang.String toString() { return null; }
    public void union(int p0, int p1, int p2, int p3) {}
    public void union(android.graphics.Rect p0) {}
    public int width() { return 0; }
}
