// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Region {
    public boolean contains(int p0, int p1) { return false; }
    public android.graphics.Path getBoundaryPath() { return null; }
    public android.graphics.Rect getBounds() { return null; }
    public boolean isEmpty() { return false; }
    public boolean op(android.graphics.Rect p0, android.graphics.Region.Op p1) { return false; }
    public boolean op(int p0, int p1, int p2, int p3, android.graphics.Region.Op p4) { return false; }
    public boolean set(android.graphics.Rect p0) { return false; }
    public boolean set(int p0, int p1, int p2, int p3) { return false; }
    public boolean setPath(android.graphics.Path p0, android.graphics.Region p1) { return false; }
    public boolean union(android.graphics.Rect p0) { return false; }

    public static class Op {
    }
}
