// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class RenderEffect {
    public android.graphics.RenderEffect createBlurEffect(float p0, float p1, android.graphics.Shader.TileMode p2) { return null; }
    public android.graphics.RenderEffect createBlurEffect(float p0, float p1, android.graphics.RenderEffect p2, android.graphics.Shader.TileMode p3) { return null; }
    public android.graphics.RenderEffect createOffsetEffect(float p0, float p1) { return null; }
    public android.graphics.RenderEffect createOffsetEffect(float p0, float p1, android.graphics.RenderEffect p2) { return null; }
}
