// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Shader {
    public boolean getLocalMatrix(android.graphics.Matrix p0) { return false; }
    public void setLocalMatrix(android.graphics.Matrix p0) {}

    public static class TileMode {
        public int hashCode() { return 0; }
        public android.graphics.Shader.TileMode[] values() { return null; }
    }
}
