// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class SurfaceTexture {
    public void attachToGLContext(int p0) {}
    public void detachFromGLContext() {}
    public long getTimestamp() { return 0; }
    public void getTransformMatrix(float[] p0) {}
    public void release() {}
    public void setDefaultBufferSize(int p0, int p1) {}
    public void setOnFrameAvailableListener(android.graphics.SurfaceTexture.OnFrameAvailableListener p0) {}
    public void updateTexImage() {}

    public interface OnFrameAvailableListener {
    }
}
