// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class Typeface {
    public android.graphics.Typeface create(android.graphics.Typeface p0, int p1) { return null; }
    public android.graphics.Typeface create(android.graphics.Typeface p0, int p1, boolean p2) { return null; }
    public android.graphics.Typeface createFromAsset(android.content.res.AssetManager p0, java.lang.String p1) { return null; }
    public android.graphics.Typeface createFromFile(java.io.File p0) { return null; }
    public android.graphics.Typeface defaultFromStyle(int p0) { return null; }
    public boolean equals(java.lang.Object p0) { return false; }
    public int getStyle() { return 0; }
    public int getWeight() { return 0; }
    public int hashCode() { return 0; }
    public boolean isItalic() { return false; }

    public static class Builder {
        public android.graphics.Typeface build() { return null; }
        public android.graphics.Typeface.Builder setFontVariationSettings(java.lang.String p0) { return null; }
        public android.graphics.Typeface.Builder setItalic(boolean p0) { return null; }
        public android.graphics.Typeface.Builder setWeight(int p0) { return null; }
    }

    public static class CustomFallbackBuilder {
        public android.graphics.Typeface.CustomFallbackBuilder addCustomFallback(android.graphics.fonts.FontFamily p0) { return null; }
        public android.graphics.Typeface build() { return null; }
        public android.graphics.Typeface.CustomFallbackBuilder setStyle(android.graphics.fonts.FontStyle p0) { return null; }
        public android.graphics.Typeface.CustomFallbackBuilder setSystemFallback(java.lang.String p0) { return null; }
    }
}
