// @generated by gen-shims.py — do not edit by hand
package android.graphics;

public class YuvImage {
    public boolean compressToJpeg(android.graphics.Rect p0, int p1, java.io.OutputStream p2) { return false; }
}
