// @generated by gen-shims.py — do not edit by hand
package android.app.role;

public class RoleManager {
    public android.content.Intent createRequestRoleIntent(java.lang.String p0) { return null; }
    public boolean isRoleAvailable(java.lang.String p0) { return false; }
    public boolean isRoleHeld(java.lang.String p0) { return false; }
}
