// @generated by gen-shims.py — do not edit by hand
package android.inputmethodservice;

public class InputMethodService {
    public android.app.Dialog getWindow() { return null; }
    public void onBindInput() {}
    public void onCreate() {}
    public void onDestroy() {}
    public boolean onEvaluateFullscreenMode() { return false; }
    public void onStartInputView(android.view.inputmethod.EditorInfo p0, boolean p1) {}
    public void onUnbindInput() {}
    public boolean switchToPreviousInputMethod() { return false; }
}
