// @generated by gen-shims.py — do not edit by hand
package android.view.accessibility;

public class AccessibilityWindowInfo {
    public android.view.accessibility.AccessibilityNodeInfo getAnchor() { return null; }
    public void getBoundsInScreen(android.graphics.Rect p0) {}
    public android.view.accessibility.AccessibilityWindowInfo getChild(int p0) { return null; }
    public int getChildCount() { return 0; }
    public int getDisplayId() { return 0; }
    public int getId() { return 0; }
    public int getLayer() { return 0; }
    public android.os.LocaleList getLocales() { return null; }
    public android.view.accessibility.AccessibilityWindowInfo getParent() { return null; }
    public void getRegionInScreen(android.graphics.Region p0) {}
    public android.view.accessibility.AccessibilityNodeInfo getRoot() { return null; }
    public android.view.accessibility.AccessibilityNodeInfo getRoot(int p0) { return null; }
    public java.lang.CharSequence getTitle() { return null; }
    public long getTransitionTimeMillis() { return 0; }
    public int getType() { return 0; }
    public boolean isAccessibilityFocused() { return false; }
    public boolean isActive() { return false; }
    public boolean isFocused() { return false; }
    public boolean isInPictureInPictureMode() { return false; }
    public android.view.accessibility.AccessibilityWindowInfo obtain() { return null; }
    public android.view.accessibility.AccessibilityWindowInfo obtain(android.view.accessibility.AccessibilityWindowInfo p0) { return null; }
    public void recycle() {}
}
