// @generated by gen-shims.py — do not edit by hand
package android.view.accessibility;

public interface AccessibilityNodeProvider {
    void addExtraDataToAccessibilityNodeInfo(int p0, android.view.accessibility.AccessibilityNodeInfo p1, java.lang.String p2, android.os.Bundle p3);
    android.view.accessibility.AccessibilityNodeInfo createAccessibilityNodeInfo(int p0);
    java.util.List findAccessibilityNodeInfosByText(java.lang.String p0, int p1);
    boolean performAction(int p0, int p1, android.os.Bundle p2);
}
