// @generated by gen-shims.py — do not edit by hand
package android.view.accessibility;

public class AccessibilityEvent {
    public void appendRecord(android.view.accessibility.AccessibilityRecord p0) {}
    public int getAction() { return 0; }
    public int getContentChangeTypes() { return 0; }
    public java.lang.CharSequence getContentDescription() { return null; }
    public int getEventType() { return 0; }
    public int getMovementGranularity() { return 0; }
    public java.lang.CharSequence getPackageName() { return null; }
    public android.view.accessibility.AccessibilityRecord getRecord(int p0) { return null; }
    public int getRecordCount() { return 0; }
    public java.util.List getText() { return null; }
    public boolean isAccessibilityDataSensitive() { return false; }
    public android.view.accessibility.AccessibilityEvent obtain(int p0) { return null; }
    public android.view.accessibility.AccessibilityEvent obtain() { return null; }
    public void setAccessibilityDataSensitive(boolean p0) {}
    public void setAction(int p0) {}
    public void setChecked(boolean p0) {}
    public void setClassName(java.lang.CharSequence p0) {}
    public void setContentChangeTypes(int p0) {}
    public void setContentDescription(java.lang.CharSequence p0) {}
    public void setEnabled(boolean p0) {}
    public void setEventType(int p0) {}
    public void setFromIndex(int p0) {}
    public void setItemCount(int p0) {}
    public void setMovementGranularity(int p0) {}
    public void setPackageName(java.lang.CharSequence p0) {}
    public void setPassword(boolean p0) {}
    public void setScrollX(int p0) {}
    public void setScrollY(int p0) {}
    public void setScrollable(boolean p0) {}
    public void setSource(android.view.View p0) {}
    public void setToIndex(int p0) {}
}
