// @generated by gen-shims.py — do not edit by hand
package android.view.accessibility;

public class AccessibilityManager {
    public void addAccessibilityServicesStateChangeListener(android.view.accessibility.AccessibilityManager.AccessibilityServicesStateChangeListener p0) {}
    public boolean addAccessibilityStateChangeListener(android.view.accessibility.AccessibilityManager.AccessibilityStateChangeListener p0) { return false; }
    public boolean addTouchExplorationStateChangeListener(android.view.accessibility.AccessibilityManager.TouchExplorationStateChangeListener p0) { return false; }
    public java.util.List getEnabledAccessibilityServiceList(int p0) { return null; }
    public java.util.List getInstalledAccessibilityServiceList() { return null; }
    public int getRecommendedTimeoutMillis(int p0, int p1) { return 0; }
    public boolean isEnabled() { return false; }
    public boolean isRequestFromAccessibilityTool() { return false; }
    public boolean isTouchExplorationEnabled() { return false; }
    public boolean removeAccessibilityServicesStateChangeListener(android.view.accessibility.AccessibilityManager.AccessibilityServicesStateChangeListener p0) { return false; }
    public boolean removeAccessibilityStateChangeListener(android.view.accessibility.AccessibilityManager.AccessibilityStateChangeListener p0) { return false; }
    public boolean removeTouchExplorationStateChangeListener(android.view.accessibility.AccessibilityManager.TouchExplorationStateChangeListener p0) { return false; }
    public void sendAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0) {}

    public interface AccessibilityServicesStateChangeListener {
    }

    public interface AccessibilityStateChangeListener {
    }

    public interface TouchExplorationStateChangeListener {
    }
}
