// @generated by gen-shims.py — do not edit by hand
package android.view.accessibility;

public class CaptioningManager {
    public float getFontScale() { return 0f; }
    public java.util.Locale getLocale() { return null; }
    public android.view.accessibility.CaptioningManager.CaptionStyle getUserStyle() { return null; }
    public boolean isEnabled() { return false; }

    public static class CaptionStyle {
        public android.graphics.Typeface getTypeface() { return null; }
        public boolean hasBackgroundColor() { return false; }
        public boolean hasEdgeColor() { return false; }
        public boolean hasEdgeType() { return false; }
        public boolean hasForegroundColor() { return false; }
        public boolean hasWindowColor() { return false; }
    }
}
