// @generated by gen-shims.py — do not edit by hand
package android.text.style;

public class ForegroundColorSpan {
    public int getForegroundColor() { return 0; }
    public void updateDrawState(android.text.TextPaint p0) {}
}
