// @generated by gen-shims.py — do not edit by hand
package android.text.style;

public class TtsSpan {

    public static class Builder {
        public android.text.style.TtsSpan build() { return null; }
    }

    public static class TextBuilder {
    }

    public static class VerbatimBuilder {
    }
}
