// @generated by gen-shims.py — do not edit by hand
package android.text.style;

public class URLSpan {
    public java.lang.String getURL() { return null; }
    public void onClick(android.view.View p0) {}
    public void updateDrawState(android.text.TextPaint p0) {}
}
