// @generated by gen-shims.py — do not edit by hand
package android.service.autofill;

public class Field {

    public static class Builder {
        public android.service.autofill.Field build() { return null; }
        public android.service.autofill.Field.Builder setValue(android.view.autofill.AutofillValue p0) { return null; }
    }
}
