// @generated by gen-shims.py — do not edit by hand
package android.service.autofill;

public class FillRequest {
    public java.util.List getFillContexts() { return null; }
    public int getFlags() { return 0; }
    public android.view.inputmethod.InlineSuggestionsRequest getInlineSuggestionsRequest() { return null; }
}
