// @generated by gen-shims.py — do not edit by hand
package android.service.autofill;

public interface FillCallback {
    void onFailure(java.lang.CharSequence p0);
    void onSuccess(android.service.autofill.FillResponse p0);
}
