// @generated by gen-shims.py — do not edit by hand
package android.service.autofill;

public class FillResponse {

    public static class Builder {
        public android.service.autofill.FillResponse.Builder addDataset(android.service.autofill.Dataset p0) { return null; }
        public android.service.autofill.FillResponse build() { return null; }
        public android.service.autofill.FillResponse.Builder setAuthentication(android.view.autofill.AutofillId[] p0, android.content.IntentSender p1, android.service.autofill.Presentations p2) { return null; }
        public android.service.autofill.FillResponse.Builder setAuthentication(android.view.autofill.AutofillId[] p0, android.content.IntentSender p1, android.widget.RemoteViews p2, android.service.autofill.InlinePresentation p3) { return null; }
        public android.service.autofill.FillResponse.Builder setHeader(android.widget.RemoteViews p0) { return null; }
        public android.service.autofill.FillResponse.Builder setSaveInfo(android.service.autofill.SaveInfo p0) { return null; }
    }
}
