// @generated by gen-shims.py — do not edit by hand
package android.service.autofill;

public class Presentations {

    public static class Builder {
        public android.service.autofill.Presentations build() { return null; }
        public android.service.autofill.Presentations.Builder setDialogPresentation(android.widget.RemoteViews p0) { return null; }
        public android.service.autofill.Presentations.Builder setInlinePresentation(android.service.autofill.InlinePresentation p0) { return null; }
        public android.service.autofill.Presentations.Builder setMenuPresentation(android.widget.RemoteViews p0) { return null; }
    }
}
