// @generated by gen-shims.py — do not edit by hand
package android.service.autofill;

public interface SaveCallback {
    void onFailure(java.lang.CharSequence p0);
    void onSuccess(android.content.IntentSender p0);
}
