// @generated by gen-shims.py — do not edit by hand
package android.service.autofill;

public class SaveInfo {

    public static class Builder {
        public android.service.autofill.SaveInfo build() { return null; }
        public android.service.autofill.SaveInfo.Builder setOptionalIds(android.view.autofill.AutofillId[] p0) { return null; }
    }
}
