// @generated by gen-shims.py — do not edit by hand
package android.view.translation;

public class TranslationRequestValue {
    public android.view.translation.TranslationRequestValue forText(java.lang.CharSequence p0) { return null; }
}
