// @generated by gen-shims.py — do not edit by hand
package android.view.translation;

public class ViewTranslationResponse {
    public android.view.translation.TranslationResponseValue getValue(java.lang.String p0) { return null; }
}
