// @generated by gen-shims.py — do not edit by hand
package android.view.translation;

public class ViewTranslationRequest {

    public static class Builder {
        public android.view.translation.ViewTranslationRequest build() { return null; }
        public android.view.translation.ViewTranslationRequest.Builder setValue(java.lang.String p0, android.view.translation.TranslationRequestValue p1) { return null; }
    }
}
