// @generated by gen-shims.py — do not edit by hand
package android.system;

public class Os {
    public boolean access(java.lang.String p0, int p1) { return false; }
    public void chmod(java.lang.String p0, int p1) {}
    public void close(java.io.FileDescriptor p0) {}
    public java.io.FileDescriptor dup(java.io.FileDescriptor p0) { return null; }
    public void fdatasync(java.io.FileDescriptor p0) {}
    public android.system.StructStat fstat(java.io.FileDescriptor p0) { return null; }
    public android.system.StructStatVfs fstatvfs(java.io.FileDescriptor p0) { return null; }
    public void fsync(java.io.FileDescriptor p0) {}
    public void ftruncate(java.io.FileDescriptor p0, long p1) {}
    public void link(java.lang.String p0, java.lang.String p1) {}
    public long lseek(java.io.FileDescriptor p0, long p1, int p2) { return 0; }
    public android.system.StructStat lstat(java.lang.String p0) { return null; }
    public java.io.FileDescriptor memfd_create(java.lang.String p0, int p1) { return null; }
    public void mkfifo(java.lang.String p0, int p1) {}
    public java.io.FileDescriptor open(java.lang.String p0, int p1, int p2) { return null; }
    public int pread(java.io.FileDescriptor p0, java.nio.ByteBuffer p1, long p2) { return 0; }
    public int pwrite(java.io.FileDescriptor p0, java.nio.ByteBuffer p1, long p2) { return 0; }
    public int read(java.io.FileDescriptor p0, java.nio.ByteBuffer p1) { return 0; }
    public java.lang.String readlink(java.lang.String p0) { return null; }
    public long sendfile(java.io.FileDescriptor p0, java.io.FileDescriptor p1, android.system.Int64Ref p2, long p3) { return 0; }
    public android.system.StructStat stat(java.lang.String p0) { return null; }
    public android.system.StructStatVfs statvfs(java.lang.String p0) { return null; }
    public void symlink(java.lang.String p0, java.lang.String p1) {}
    public long sysconf(int p0) { return 0; }
    public int write(java.io.FileDescriptor p0, java.nio.ByteBuffer p1) { return 0; }
}
