// @generated by gen-shims.py — do not edit by hand
package android.system;

public class OsConstants {
    public boolean S_ISBLK(int p0) { return false; }
    public boolean S_ISCHR(int p0) { return false; }
    public boolean S_ISFIFO(int p0) { return false; }
    public boolean S_ISLNK(int p0) { return false; }
    public boolean S_ISREG(int p0) { return false; }
    public boolean S_ISSOCK(int p0) { return false; }
}
