// @generated by gen-shims.py — do not edit by hand
package android.net.nsd;

public class NsdManager {
    public void registerService(android.net.nsd.NsdServiceInfo p0, int p1, android.net.nsd.NsdManager.RegistrationListener p2) {}
    public void unregisterService(android.net.nsd.NsdManager.RegistrationListener p0) {}

    public interface RegistrationListener {
    }
}
