// @generated by gen-shims.py — do not edit by hand
package android.net.nsd;

public class NsdServiceInfo {
    public java.lang.String getServiceName() { return null; }
    public void setPort(int p0) {}
    public void setServiceName(java.lang.String p0) {}
    public void setServiceType(java.lang.String p0) {}
}
