// @generated by gen-shims.py — do not edit by hand
package android.view.autofill;

public class AutofillValue {
    public android.view.autofill.AutofillValue forDate(long p0) { return null; }
    public android.view.autofill.AutofillValue forList(int p0) { return null; }
    public android.view.autofill.AutofillValue forText(java.lang.CharSequence p0) { return null; }
    public android.view.autofill.AutofillValue forToggle(boolean p0) { return null; }
    public long getDateValue() { return 0; }
    public int getListValue() { return 0; }
    public java.lang.CharSequence getTextValue() { return null; }
    public boolean getToggleValue() { return false; }
    public boolean isDate() { return false; }
    public boolean isList() { return false; }
    public boolean isText() { return false; }
    public boolean isToggle() { return false; }
}
