// @generated by gen-shims.py — do not edit by hand
package android.view.autofill;

public class AutofillManager {
    public void cancel() {}
    public void commit() {}
    public boolean hasEnabledAutofillServices() { return false; }
    public boolean isAutofillSupported() { return false; }
    public boolean isEnabled() { return false; }
    public void notifyValueChanged(android.view.View p0) {}
    public void notifyValueChanged(android.view.View p0, int p1, android.view.autofill.AutofillValue p2) {}
    public void notifyViewEntered(android.view.View p0, int p1, android.graphics.Rect p2) {}
    public void notifyViewExited(android.view.View p0, int p1) {}
    public void notifyViewVisibilityChanged(android.view.View p0, int p1, boolean p2) {}
    public void registerCallback(android.view.autofill.AutofillManager.AutofillCallback p0) {}
    public void requestAutofill(android.view.View p0, int p1, android.graphics.Rect p2) {}
    public void unregisterCallback(android.view.autofill.AutofillManager.AutofillCallback p0) {}

    public interface AutofillCallback {
        void onAutofillEvent(android.view.View p0, int p1, int p2);
    }
}
