// @generated by gen-shims.py — do not edit by hand
package android.database.sqlite;

public class SQLiteStatement {
    public void bindBlob(int p0, byte[] p1) {}
    public void bindDouble(int p0, double p1) {}
    public void bindLong(int p0, long p1) {}
    public void bindNull(int p0) {}
    public void bindString(int p0, java.lang.String p1) {}
    public void close() {}
    public void execute() {}
    public long executeInsert() { return 0; }
    public int executeUpdateDelete() { return 0; }
    public long simpleQueryForLong() { return 0; }
    public java.lang.String simpleQueryForString() { return null; }
}
