// @generated by gen-shims.py — do not edit by hand
package android.database.sqlite;

public class SQLiteDatabase {
    public void beginTransaction() {}
    public void beginTransactionNonExclusive() {}
    public void beginTransactionWithListener(android.database.sqlite.SQLiteTransactionListener p0) {}
    public void beginTransactionWithListenerNonExclusive(android.database.sqlite.SQLiteTransactionListener p0) {}
    public void close() {}
    public android.database.sqlite.SQLiteStatement compileStatement(java.lang.String p0) { return null; }
    public int delete(java.lang.String p0, java.lang.String p1, java.lang.String[] p2) { return 0; }
    public boolean deleteDatabase(java.io.File p0) { return false; }
    public void disableWriteAheadLogging() {}
    public boolean enableWriteAheadLogging() { return false; }
    public void endTransaction() {}
    public void execPerConnectionSQL(java.lang.String p0, java.lang.Object[] p1) {}
    public void execSQL(java.lang.String p0) {}
    public void execSQL(java.lang.String p0, java.lang.Object[] p1) {}
    public java.util.List getAttachedDbs() { return null; }
    public long getMaximumSize() { return 0; }
    public long getPageSize() { return 0; }
    public java.lang.String getPath() { return null; }
    public int getVersion() { return 0; }
    public boolean inTransaction() { return false; }
    public long insert(java.lang.String p0, java.lang.String p1, android.content.ContentValues p2) { return 0; }
    public long insertOrThrow(java.lang.String p0, java.lang.String p1, android.content.ContentValues p2) { return 0; }
    public long insertWithOnConflict(java.lang.String p0, java.lang.String p1, android.content.ContentValues p2, int p3) { return 0; }
    public boolean isDatabaseIntegrityOk() { return false; }
    public boolean isDbLockedByCurrentThread() { return false; }
    public boolean isOpen() { return false; }
    public boolean isReadOnly() { return false; }
    public boolean isWriteAheadLoggingEnabled() { return false; }
    public boolean needUpgrade(int p0) { return false; }
    public android.database.sqlite.SQLiteDatabase openDatabase(java.lang.String p0, android.database.sqlite.SQLiteDatabase.CursorFactory p1, int p2) { return null; }
    public android.database.sqlite.SQLiteDatabase openDatabase(java.lang.String p0, android.database.sqlite.SQLiteDatabase.CursorFactory p1, int p2, android.database.DatabaseErrorHandler p3) { return null; }
    public android.database.sqlite.SQLiteDatabase openOrCreateDatabase(java.lang.String p0, android.database.sqlite.SQLiteDatabase.CursorFactory p1) { return null; }
    public android.database.Cursor query(java.lang.String p0, java.lang.String[] p1, java.lang.String p2, java.lang.String[] p3, java.lang.String p4, java.lang.String p5, java.lang.String p6) { return null; }
    public android.database.Cursor query(java.lang.String p0, java.lang.String[] p1, java.lang.String p2, java.lang.String[] p3, java.lang.String p4, java.lang.String p5, java.lang.String p6, java.lang.String p7) { return null; }
    public android.database.Cursor query(boolean p0, java.lang.String p1, java.lang.String[] p2, java.lang.String p3, java.lang.String[] p4, java.lang.String p5, java.lang.String p6, java.lang.String p7, java.lang.String p8, android.os.CancellationSignal p9) { return null; }
    public android.database.Cursor rawQuery(java.lang.String p0, java.lang.String[] p1) { return null; }
    public android.database.Cursor rawQuery(java.lang.String p0, java.lang.String[] p1, android.os.CancellationSignal p2) { return null; }
    public android.database.Cursor rawQueryWithFactory(android.database.sqlite.SQLiteDatabase.CursorFactory p0, java.lang.String p1, java.lang.String[] p2, java.lang.String p3) { return null; }
    public android.database.Cursor rawQueryWithFactory(android.database.sqlite.SQLiteDatabase.CursorFactory p0, java.lang.String p1, java.lang.String[] p2, java.lang.String p3, android.os.CancellationSignal p4) { return null; }
    public long replace(java.lang.String p0, java.lang.String p1, android.content.ContentValues p2) { return 0; }
    public long replaceOrThrow(java.lang.String p0, java.lang.String p1, android.content.ContentValues p2) { return 0; }
    public void setForeignKeyConstraintsEnabled(boolean p0) {}
    public void setLocale(java.util.Locale p0) {}
    public void setMaxSqlCacheSize(int p0) {}
    public long setMaximumSize(long p0) { return 0; }
    public void setPageSize(long p0) {}
    public void setTransactionSuccessful() {}
    public void setVersion(int p0) {}
    public int update(java.lang.String p0, android.content.ContentValues p1, java.lang.String p2, java.lang.String[] p3) { return 0; }
    public boolean yieldIfContendedSafely() { return false; }
    public boolean yieldIfContendedSafely(long p0) { return false; }

    public static class CursorFactory {
    }
}
