// @generated by gen-shims.py — do not edit by hand
package android.database.sqlite;

public class SQLiteOpenHelper {
    public void close() {}
    public java.lang.String getDatabaseName() { return null; }
    public android.database.sqlite.SQLiteDatabase getReadableDatabase() { return null; }
    public android.database.sqlite.SQLiteDatabase getWritableDatabase() { return null; }
    public void onConfigure(android.database.sqlite.SQLiteDatabase p0) {}
    public void onOpen(android.database.sqlite.SQLiteDatabase p0) {}
    public void setWriteAheadLoggingEnabled(boolean p0) {}
}
