// @generated by gen-shims.py — do not edit by hand
package android.graphics.pdf;

public class PdfDocument {
    public void close() {}
    public void finishPage(android.graphics.pdf.PdfDocument.Page p0) {}
    public void writeTo(java.io.OutputStream p0) {}

    public static class Page {
        public android.graphics.Canvas getCanvas() { return null; }
        public android.graphics.pdf.PdfDocument.PageInfo getInfo() { return null; }
    }

    public static class PageInfo {
        public android.graphics.Rect getContentRect() { return null; }
    }
}
