// @generated by gen-shims.py — do not edit by hand
package android.telephony;

public class PhoneNumberUtils {
    public java.lang.String formatNumber(java.lang.String p0) { return null; }
    public boolean isGlobalPhoneNumber(java.lang.String p0) { return false; }
    public java.lang.String normalizeNumber(java.lang.String p0) { return null; }
    public java.lang.String stripSeparators(java.lang.String p0) { return null; }
}
