// @generated by gen-shims.py — do not edit by hand
package android.telephony;

public class SignalStrength {
    public int getCdmaDbm() { return 0; }
    public java.util.List getCellSignalStrengths() { return null; }
    public int getEvdoDbm() { return 0; }
    public int getGsmSignalStrength() { return 0; }
    public int getLevel() { return 0; }
    public boolean isGsm() { return false; }
    public java.lang.String toString() { return null; }
}
