// @generated by gen-shims.py — do not edit by hand
package android.telephony;

public class TelephonyManager {
    public int getDataActivity() { return 0; }
    public int getDataNetworkType() { return 0; }
    public java.lang.String getDeviceId() { return null; }
    public java.lang.String getDeviceId(int p0) { return null; }
    public java.lang.String getImei() { return null; }
    public java.lang.String getNetworkCountryIso() { return null; }
    public java.lang.String getNetworkOperator() { return null; }
    public java.lang.String getNetworkOperatorName() { return null; }
    public int getNetworkType() { return 0; }
    public int getPhoneType() { return 0; }
    public android.telephony.SignalStrength getSignalStrength() { return null; }
    public java.lang.CharSequence getSimCarrierIdName() { return null; }
    public java.lang.String getSimCountryIso() { return null; }
    public java.lang.String getSimOperator() { return null; }
    public java.lang.String getSimOperatorName() { return null; }
    public int getSimState() { return 0; }
    public int getSubscriptionId() { return 0; }
    public boolean isDataEnabled() { return false; }
    public void listen(android.telephony.PhoneStateListener p0, int p1) {}
    public void registerTelephonyCallback(java.util.concurrent.Executor p0, android.telephony.TelephonyCallback p1) {}
    public void unregisterTelephonyCallback(android.telephony.TelephonyCallback p0) {}
}
