// @generated by gen-shims.py — do not edit by hand
package android.app.slice;

public class Slice {
    public java.util.List getItems() { return null; }
    public android.app.slice.SliceSpec getSpec() { return null; }

    public static class Builder {
        public android.app.slice.Slice.Builder addAction(android.app.PendingIntent p0, android.app.slice.Slice p1, java.lang.String p2) { return null; }
        public android.app.slice.Slice.Builder addBundle(android.os.Bundle p0, java.lang.String p1, java.util.List p2) { return null; }
        public android.app.slice.Slice.Builder addHints(java.util.List p0) { return null; }
        public android.app.slice.Slice.Builder addIcon(android.graphics.drawable.Icon p0, java.lang.String p1, java.util.List p2) { return null; }
        public android.app.slice.Slice.Builder addInt(int p0, java.lang.String p1, java.util.List p2) { return null; }
        public android.app.slice.Slice.Builder addLong(long p0, java.lang.String p1, java.util.List p2) { return null; }
        public android.app.slice.Slice.Builder addText(java.lang.CharSequence p0, java.lang.String p1, java.util.List p2) { return null; }
        public android.app.slice.Slice build() { return null; }
    }
}
