// @generated by gen-shims.py — do not edit by hand
package android.database;

public abstract class AbstractCursor {
    public void fillWindow(int p0, android.database.CursorWindow p1) {}
    public int getCount() { return 0; }
    public boolean onMove(int p0, int p1) { return false; }
}
