// @generated by gen-shims.py — do not edit by hand
package android.database;

public interface ContentObserver {
    boolean deliverSelfNotifications();
    void onChange(boolean p0);
    void onChange(boolean p0, android.net.Uri p1);
}
