// @generated by gen-shims.py — do not edit by hand
package android.database;

public class ContentObservable {
    public void dispatchChange(boolean p0, android.net.Uri p1) {}
    public void registerObserver(android.database.ContentObserver p0) {}
}
