// @generated by gen-shims.py — do not edit by hand
package android.database;

public class CursorWrapper {
    public void close() {}
    public void deactivate() {}
    public int getColumnIndex(java.lang.String p0) { return 0; }
    public int getColumnIndexOrThrow(java.lang.String p0) { return 0; }
    public java.lang.String[] getColumnNames() { return null; }
    public int getCount() { return 0; }
    public float getFloat(int p0) { return 0f; }
    public int getInt(int p0) { return 0; }
    public long getLong(int p0) { return 0; }
    public java.lang.String getString(int p0) { return null; }
    public android.database.Cursor getWrappedCursor() { return null; }
    public boolean isNull(int p0) { return false; }
    public boolean moveToFirst() { return false; }
    public boolean moveToNext() { return false; }
    public boolean moveToPosition(int p0) { return false; }
    public void registerContentObserver(android.database.ContentObserver p0) {}
    public boolean requery() { return false; }
    public void unregisterContentObserver(android.database.ContentObserver p0) {}
}
