// @generated by gen-shims.py — do not edit by hand
package android.database;

public class CursorWindow {
    public boolean allocRow() { return false; }
    public void close() {}
    public void copyStringToBuffer(int p0, int p1, android.database.CharArrayBuffer p2) {}
    public void freeLastRow() {}
    public byte[] getBlob(int p0, int p1) { return null; }
    public double getDouble(int p0, int p1) { return 0.0; }
    public float getFloat(int p0, int p1) { return 0f; }
    public int getInt(int p0, int p1) { return 0; }
    public long getLong(int p0, int p1) { return 0; }
    public int getNumRows() { return 0; }
    public int getStartPosition() { return 0; }
    public java.lang.String getString(int p0, int p1) { return null; }
    public boolean isNull(int p0, int p1) { return false; }
    public boolean putBlob(byte[] p0, int p1, int p2) { return false; }
    public boolean putDouble(double p0, int p1, int p2) { return false; }
    public boolean putLong(long p0, int p1, int p2) { return false; }
    public boolean putNull(int p0, int p1) { return false; }
    public boolean putString(java.lang.String p0, int p1, int p2) { return false; }
    public boolean setNumColumns(int p0) { return false; }
    public void setStartPosition(int p0) {}
}
