// @generated by gen-shims.py — do not edit by hand
package android.database;

public class DatabaseUtils {
    public void appendEscapedSQLString(java.lang.StringBuilder p0, java.lang.String p1) {}
    public java.lang.String dumpCurrentRowToString(android.database.Cursor p0) { return null; }
    public long queryNumEntries(android.database.sqlite.SQLiteDatabase p0, java.lang.String p1, java.lang.String p2, java.lang.String[] p3) { return 0; }
    public long queryNumEntries(android.database.sqlite.SQLiteDatabase p0, java.lang.String p1) { return 0; }
    public java.lang.String sqlEscapeString(java.lang.String p0) { return null; }
}
