// @generated by gen-shims.py — do not edit by hand
package android.database;

public class MatrixCursor {
    public void addRow(java.lang.Object[] p0) {}
    public android.database.MatrixCursor.RowBuilder newRow() { return null; }

    public static class RowBuilder {
        public android.database.MatrixCursor.RowBuilder add(java.lang.String p0, java.lang.Object p1) { return null; }
        public android.database.MatrixCursor.RowBuilder add(java.lang.Object p0) { return null; }
    }
}
