// @generated by gen-shims.py — do not edit by hand
package android.database;

public class Observable {
    public void registerObserver(java.lang.Object p0) {}
    public void unregisterAll() {}
    public void unregisterObserver(java.lang.Object p0) {}
}
