// @generated by gen-shims.py — do not edit by hand
package android.text.format;

public class DateUtils {
    public java.lang.String formatDateRange(android.content.Context p0, long p1, long p2, int p3) { return null; }
    public java.lang.String formatDateTime(android.content.Context p0, long p1, int p2) { return null; }
    public java.lang.String formatElapsedTime(long p0) { return null; }
    public java.lang.CharSequence getRelativeDateTimeString(android.content.Context p0, long p1, long p2, long p3, int p4) { return null; }
    public java.lang.CharSequence getRelativeTimeSpanString(long p0, long p1, long p2, int p3) { return null; }
    public java.lang.CharSequence getRelativeTimeSpanString(long p0, long p1, long p2) { return null; }
    public boolean isToday(long p0) { return false; }
}
