// @generated by gen-shims.py — do not edit by hand
package android.text.format;

public class DateFormat {
    public java.lang.CharSequence format(java.lang.CharSequence p0, long p1) { return null; }
    public java.lang.String getBestDateTimePattern(java.util.Locale p0, java.lang.String p1) { return null; }
    public java.text.DateFormat getDateFormat(android.content.Context p0) { return null; }
    public char[] getDateFormatOrder(android.content.Context p0) { return null; }
    public java.text.DateFormat getLongDateFormat(android.content.Context p0) { return null; }
    public java.text.DateFormat getMediumDateFormat(android.content.Context p0) { return null; }
    public java.text.DateFormat getTimeFormat(android.content.Context p0) { return null; }
    public boolean is24HourFormat(android.content.Context p0) { return false; }
}
