// @generated by gen-shims.py — do not edit by hand
package android.text.format;

public interface Formatter {
    java.lang.String formatFileSize(android.content.Context p0, long p1);
    java.lang.String formatIpAddress(int p0);
    java.lang.String formatShortFileSize(android.content.Context p0, long p1);
}
