// @generated by gen-shims.py — do not edit by hand
package android.text.format;

public class Time {
    public java.lang.String format2445() { return null; }
    public java.lang.String format3339(boolean p0) { return null; }
    public long normalize(boolean p0) { return 0; }
    public void set(long p0) {}
    public void setToNow() {}
    public long toMillis(boolean p0) { return 0; }
}
