// @generated by gen-shims.py — do not edit by hand
package android.os;

public class AsyncTask {
    public boolean cancel(boolean p0) { return false; }
    public android.os.AsyncTask execute(java.lang.Object[] p0) { return null; }
    public android.os.AsyncTask executeOnExecutor(java.util.concurrent.Executor p0, java.lang.Object[] p1) { return null; }
    public android.os.AsyncTask.Status getStatus() { return null; }
    public boolean isCancelled() { return false; }
    public void onPostExecute(java.lang.Object p0) {}
    public void onPreExecute() {}
    public void onProgressUpdate(java.lang.Object[] p0) {}

    public static class Status {
    }
}
