// @generated by gen-shims.py — do not edit by hand
package android.os;

public class BatteryManager {
    public int getIntProperty(int p0) { return 0; }
    public boolean isCharging() { return false; }
}
