// @generated by gen-shims.py — do not edit by hand
package android.os;

public class Build {
    public java.lang.String getRadioVersion() { return null; }

    public static class VERSION {
    }
}
