// @generated by gen-shims.py — do not edit by hand
package android.os;

public class Bundle {
    public void clear() {}
    public java.lang.Object clone() { return null; }
    public boolean containsKey(java.lang.String p0) { return false; }
    public java.lang.Object get(java.lang.String p0) { return null; }
    public android.os.IBinder getBinder(java.lang.String p0) { return null; }
    public boolean getBoolean(java.lang.String p0) { return false; }
    public boolean getBoolean(java.lang.String p0, boolean p1) { return false; }
    public boolean[] getBooleanArray(java.lang.String p0) { return null; }
    public android.os.Bundle getBundle(java.lang.String p0) { return null; }
    public byte getByte(java.lang.String p0) { return 0; }
    public byte[] getByteArray(java.lang.String p0) { return null; }
    public char getChar(java.lang.String p0, char p1) { return 0; }
    public char getChar(java.lang.String p0) { return 0; }
    public char[] getCharArray(java.lang.String p0) { return null; }
    public java.lang.CharSequence getCharSequence(java.lang.String p0) { return null; }
    public java.lang.CharSequence[] getCharSequenceArray(java.lang.String p0) { return null; }
    public java.util.ArrayList getCharSequenceArrayList(java.lang.String p0) { return null; }
    public java.lang.ClassLoader getClassLoader() { return null; }
    public double getDouble(java.lang.String p0) { return 0.0; }
    public double getDouble(java.lang.String p0, double p1) { return 0.0; }
    public double[] getDoubleArray(java.lang.String p0) { return null; }
    public float getFloat(java.lang.String p0) { return 0f; }
    public float getFloat(java.lang.String p0, float p1) { return 0f; }
    public float[] getFloatArray(java.lang.String p0) { return null; }
    public int getInt(java.lang.String p0) { return 0; }
    public int getInt(java.lang.String p0, int p1) { return 0; }
    public int[] getIntArray(java.lang.String p0) { return null; }
    public java.util.ArrayList getIntegerArrayList(java.lang.String p0) { return null; }
    public long getLong(java.lang.String p0) { return 0; }
    public long getLong(java.lang.String p0, long p1) { return 0; }
    public long[] getLongArray(java.lang.String p0) { return null; }
    public android.os.Parcelable getParcelable(java.lang.String p0) { return null; }
    public java.lang.Object getParcelable(java.lang.String p0, java.lang.Class p1) { return null; }
    public android.os.Parcelable[] getParcelableArray(java.lang.String p0) { return null; }
    public java.lang.Object[] getParcelableArray(java.lang.String p0, java.lang.Class p1) { return null; }
    public java.util.ArrayList getParcelableArrayList(java.lang.String p0) { return null; }
    public java.util.ArrayList getParcelableArrayList(java.lang.String p0, java.lang.Class p1) { return null; }
    public java.io.Serializable getSerializable(java.lang.String p0) { return null; }
    public java.io.Serializable getSerializable(java.lang.String p0, java.lang.Class p1) { return null; }
    public short getShort(java.lang.String p0) { return 0; }
    public short[] getShortArray(java.lang.String p0) { return null; }
    public android.util.Size getSize(java.lang.String p0) { return null; }
    public android.util.SizeF getSizeF(java.lang.String p0) { return null; }
    public android.util.SparseArray getSparseParcelableArray(java.lang.String p0) { return null; }
    public android.util.SparseArray getSparseParcelableArray(java.lang.String p0, java.lang.Class p1) { return null; }
    public java.lang.String getString(java.lang.String p0) { return null; }
    public java.lang.String getString(java.lang.String p0, java.lang.String p1) { return null; }
    public java.lang.String[] getStringArray(java.lang.String p0) { return null; }
    public java.util.ArrayList getStringArrayList(java.lang.String p0) { return null; }
    public int hashCode() { return 0; }
    public boolean isEmpty() { return false; }
    public java.util.Set keySet() { return null; }
    public void putAll(android.os.Bundle p0) {}
    public void putBinder(java.lang.String p0, android.os.IBinder p1) {}
    public void putBoolean(java.lang.String p0, boolean p1) {}
    public void putBooleanArray(java.lang.String p0, boolean[] p1) {}
    public void putBundle(java.lang.String p0, android.os.Bundle p1) {}
    public void putByte(java.lang.String p0, byte p1) {}
    public void putByteArray(java.lang.String p0, byte[] p1) {}
    public void putChar(java.lang.String p0, char p1) {}
    public void putCharArray(java.lang.String p0, char[] p1) {}
    public void putCharSequence(java.lang.String p0, java.lang.CharSequence p1) {}
    public void putCharSequenceArray(java.lang.String p0, java.lang.CharSequence[] p1) {}
    public void putCharSequenceArrayList(java.lang.String p0, java.util.ArrayList p1) {}
    public void putDouble(java.lang.String p0, double p1) {}
    public void putDoubleArray(java.lang.String p0, double[] p1) {}
    public void putFloat(java.lang.String p0, float p1) {}
    public void putFloatArray(java.lang.String p0, float[] p1) {}
    public void putInt(java.lang.String p0, int p1) {}
    public void putIntArray(java.lang.String p0, int[] p1) {}
    public void putIntegerArrayList(java.lang.String p0, java.util.ArrayList p1) {}
    public void putLong(java.lang.String p0, long p1) {}
    public void putLongArray(java.lang.String p0, long[] p1) {}
    public void putParcelable(java.lang.String p0, android.os.Parcelable p1) {}
    public void putParcelableArray(java.lang.String p0, android.os.Parcelable[] p1) {}
    public void putParcelableArrayList(java.lang.String p0, java.util.ArrayList p1) {}
    public void putSerializable(java.lang.String p0, java.io.Serializable p1) {}
    public void putShort(java.lang.String p0, short p1) {}
    public void putShortArray(java.lang.String p0, short[] p1) {}
    public void putSize(java.lang.String p0, android.util.Size p1) {}
    public void putSizeF(java.lang.String p0, android.util.SizeF p1) {}
    public void putSparseParcelableArray(java.lang.String p0, android.util.SparseArray p1) {}
    public void putString(java.lang.String p0, java.lang.String p1) {}
    public void putStringArray(java.lang.String p0, java.lang.String[] p1) {}
    public void putStringArrayList(java.lang.String p0, java.util.ArrayList p1) {}
    public void readFromParcel(android.os.Parcel p0) {}
    public void remove(java.lang.String p0) {}
    public void setClassLoader(java.lang.ClassLoader p0) {}
    public int size() { return 0; }
    public java.lang.String toString() { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
