// @generated by gen-shims.py — do not edit by hand
package android.os;

public class CancellationSignal {
    public void cancel() {}
    public boolean isCanceled() { return false; }
    public void setOnCancelListener(android.os.CancellationSignal.OnCancelListener p0) {}
    public void throwIfCanceled() {}

    public interface OnCancelListener {
    }
}
