// @generated by gen-shims.py — do not edit by hand
package android.os;

public class ConditionVariable {
    public void block() {}
    public boolean block(long p0) { return false; }
    public void close() {}
    public void open() {}
}
