// @generated by gen-shims.py — do not edit by hand
package android.os;

public class DropBoxManager {
    public android.os.DropBoxManager.Entry getNextEntry(java.lang.String p0, long p1) { return null; }

    public static class Entry {
        public void close() {}
        public java.lang.String getText(int p0) { return null; }
        public long getTimeMillis() { return 0; }
    }
}
