// @generated by gen-shims.py — do not edit by hand
package android.os;

public class Environment {
    public java.io.File getDataDirectory() { return null; }
    public java.io.File getExternalStorageDirectory() { return null; }
    public java.io.File getExternalStoragePublicDirectory(java.lang.String p0) { return null; }
    public java.lang.String getExternalStorageState() { return null; }
    public java.lang.String getExternalStorageState(java.io.File p0) { return null; }
    public java.io.File getRootDirectory() { return null; }
    public java.lang.String getStorageState(java.io.File p0) { return null; }
    public boolean isExternalStorageEmulated(java.io.File p0) { return false; }
    public boolean isExternalStorageEmulated() { return false; }
    public boolean isExternalStorageLegacy() { return false; }
    public boolean isExternalStorageManager() { return false; }
    public boolean isExternalStorageRemovable(java.io.File p0) { return false; }
}
