// @generated by gen-shims.py — do not edit by hand
package android.os;

public class HandlerThread {
    public android.os.Looper getLooper() { return null; }
    public int getThreadId() { return 0; }
    public boolean isAlive() { return false; }
    public boolean quit() { return false; }
    public boolean quitSafely() { return false; }
    public void run() {}
    public void setUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler p0) {}
    public void start() {}
}
