// @generated by gen-shims.py — do not edit by hand
package android.os;

public interface IBinder {
    void dump(java.io.FileDescriptor p0, java.lang.String[] p1);
    void dumpAsync(java.io.FileDescriptor p0, java.lang.String[] p1);
    java.lang.String getInterfaceDescriptor();
    int getSuggestedMaxIpcSizeBytes();
    boolean isBinderAlive();
    void linkToDeath(android.os.IBinder.DeathRecipient p0, int p1);
    boolean pingBinder();
    android.os.IInterface queryLocalInterface(java.lang.String p0);
    boolean transact(int p0, android.os.Parcel p1, android.os.Parcel p2, int p3);
    boolean unlinkToDeath(android.os.IBinder.DeathRecipient p0, int p1);

    public static class DeathRecipient {
    }
}
