// @generated by gen-shims.py — do not edit by hand
package android.os;

public class LocaleList {
    public boolean equals(java.lang.Object p0) { return false; }
    public android.os.LocaleList forLanguageTags(java.lang.String p0) { return null; }
    public java.util.Locale get(int p0) { return null; }
    public android.os.LocaleList getAdjustedDefault() { return null; }
    public android.os.LocaleList getDefault() { return null; }
    public java.util.Locale getFirstMatch(java.lang.String[] p0) { return null; }
    public int hashCode() { return 0; }
    public int indexOf(java.util.Locale p0) { return 0; }
    public boolean isEmpty() { return false; }
    public boolean matchesLanguageAndScript(java.util.Locale p0, java.util.Locale p1) { return false; }
    public void setDefault(android.os.LocaleList p0) {}
    public int size() { return 0; }
    public java.lang.String toLanguageTags() { return null; }
    public java.lang.String toString() { return null; }
}
