// @generated by gen-shims.py — do not edit by hand
package android.os;

public class Looper {
    public android.os.Looper getMainLooper() { return null; }
    public java.lang.Thread getThread() { return null; }
    public boolean isCurrentThread() { return false; }
    public void loop() {}
    public android.os.Looper myLooper() { return null; }
    public android.os.MessageQueue myQueue() { return null; }
    public void prepare() {}
    public void quit() {}
    public void quitSafely() {}
    public void setMessageLogging(android.util.Printer p0) {}
}
