// @generated by gen-shims.py — do not edit by hand
package android.os;

public class Messenger {
    public android.os.IBinder getBinder() { return null; }
    public void send(android.os.Message p0) {}
}
