// @generated by gen-shims.py — do not edit by hand
package android.os;

public class MessageQueue {
    public void addIdleHandler(android.os.MessageQueue.IdleHandler p0) {}
    public void removeIdleHandler(android.os.MessageQueue.IdleHandler p0) {}

    public interface IdleHandler {
    }
}
