// @generated by gen-shims.py — do not edit by hand
package android.os;

public class ParcelUuid {
    public java.util.UUID getUuid() { return null; }
    public java.lang.String toString() { return null; }
}
