// @generated by gen-shims.py — do not edit by hand
package android.os;

public class ParcelFileDescriptor {
    public android.os.ParcelFileDescriptor adoptFd(int p0) { return null; }
    public void close() {}
    public android.os.ParcelFileDescriptor[] createPipe() { return null; }
    public android.os.ParcelFileDescriptor[] createReliablePipe() { return null; }
    public int detachFd() { return 0; }
    public android.os.ParcelFileDescriptor dup(java.io.FileDescriptor p0) { return null; }
    public android.os.ParcelFileDescriptor fromDatagramSocket(java.net.DatagramSocket p0) { return null; }
    public int getFd() { return 0; }
    public java.io.FileDescriptor getFileDescriptor() { return null; }
    public long getStatSize() { return 0; }
    public android.os.ParcelFileDescriptor open(java.io.File p0, int p1) { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}

    public static class AutoCloseInputStream {
    }

    public static class AutoCloseOutputStream {
        public void close() {}
    }
}
