// @generated by gen-shims.py — do not edit by hand
package android.os;

public class PersistableBundle {
    public boolean containsKey(java.lang.String p0) { return false; }
    public boolean getBoolean(java.lang.String p0) { return false; }
    public int getInt(java.lang.String p0) { return 0; }
    public android.os.PersistableBundle getPersistableBundle(java.lang.String p0) { return null; }
    public java.lang.String getString(java.lang.String p0) { return null; }
    public void putBoolean(java.lang.String p0, boolean p1) {}
    public void putBooleanArray(java.lang.String p0, boolean[] p1) {}
    public void putDouble(java.lang.String p0, double p1) {}
    public void putDoubleArray(java.lang.String p0, double[] p1) {}
    public void putInt(java.lang.String p0, int p1) {}
    public void putIntArray(java.lang.String p0, int[] p1) {}
    public void putLong(java.lang.String p0, long p1) {}
    public void putLongArray(java.lang.String p0, long[] p1) {}
    public void putPersistableBundle(java.lang.String p0, android.os.PersistableBundle p1) {}
    public void putString(java.lang.String p0, java.lang.String p1) {}
    public void putStringArray(java.lang.String p0, java.lang.String[] p1) {}
}
