// @generated by gen-shims.py — do not edit by hand
package android.os;

public class PowerManager {
    public boolean isDeviceIdleMode() { return false; }
    public boolean isDeviceLightIdleMode() { return false; }
    public boolean isIgnoringBatteryOptimizations(java.lang.String p0) { return false; }
    public boolean isInteractive() { return false; }
    public boolean isLowPowerStandbyEnabled() { return false; }
    public boolean isPowerSaveMode() { return false; }
    public boolean isScreenOn() { return false; }
    public android.os.PowerManager.WakeLock newWakeLock(int p0, java.lang.String p1) { return null; }

    public static class WakeLock {
        public void acquire(long p0) {}
        public void acquire() {}
        public boolean isHeld() { return false; }
        public void release() {}
        public void setReferenceCounted(boolean p0) {}
        public void setWorkSource(android.os.WorkSource p0) {}
    }
}
