// @generated by gen-shims.py — do not edit by hand
package android.os;

public class Process {
    public long getElapsedCpuTime() { return 0; }
    public int getThreadPriority(int p0) { return 0; }
    public boolean is64Bit() { return false; }
    public boolean isApplicationUid(int p0) { return false; }
    public boolean isIsolated() { return false; }
    public boolean isSdkSandbox() { return false; }
    public void killProcess(int p0) {}
    public int myPid() { return 0; }
    public java.lang.String myProcessName() { return null; }
    public int myTid() { return 0; }
    public int myUid() { return 0; }
    public android.os.UserHandle myUserHandle() { return null; }
    public void sendSignal(int p0, int p1) {}
    public void setThreadPriority(int p0) {}
    public void setThreadPriority(int p0, int p1) {}
}
