// @generated by gen-shims.py — do not edit by hand
package android.os;

public class ProfilingManager {
    public void registerForAllProfilingResults(java.util.concurrent.Executor p0, java.util.function.Consumer p1) {}
    public void requestProfiling(int p0, android.os.Bundle p1, java.lang.String p2, android.os.CancellationSignal p3, java.util.concurrent.Executor p4, java.util.function.Consumer p5) {}
    public void unregisterForAllProfilingResults(java.util.function.Consumer p0) {}
}
