// @generated by gen-shims.py — do not edit by hand
package android.os;

public class RemoteCallbackList {
    public int beginBroadcast() { return 0; }
    public void finishBroadcast() {}
    public java.lang.Object getBroadcastCookie(int p0) { return null; }
    public android.os.IInterface getBroadcastItem(int p0) { return null; }
    public void kill() {}
    public boolean register(android.os.IInterface p0) { return false; }
    public boolean register(android.os.IInterface p0, java.lang.Object p1) { return false; }
    public boolean unregister(android.os.IInterface p0) { return false; }
}
