// @generated by gen-shims.py — do not edit by hand
package android.os;

public class ResultReceiver {
    public void send(int p0, android.os.Bundle p1) {}
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
