// @generated by gen-shims.py — do not edit by hand
package android.os;

public class StatFs {
    public int getAvailableBlocks() { return 0; }
    public long getAvailableBlocksLong() { return 0; }
    public long getAvailableBytes() { return 0; }
    public int getBlockCount() { return 0; }
    public long getBlockCountLong() { return 0; }
    public int getBlockSize() { return 0; }
    public long getBlockSizeLong() { return 0; }
    public long getFreeBytes() { return 0; }
    public long getTotalBytes() { return 0; }
}
