// @generated by gen-shims.py — do not edit by hand
package android.os;

public class StrictMode {
    public android.os.StrictMode.ThreadPolicy allowThreadDiskReads() { return null; }
    public android.os.StrictMode.ThreadPolicy allowThreadDiskWrites() { return null; }
    public android.os.StrictMode.ThreadPolicy getThreadPolicy() { return null; }
    public android.os.StrictMode.VmPolicy getVmPolicy() { return null; }
    public void noteSlowCall(java.lang.String p0) {}
    public void setThreadPolicy(android.os.StrictMode.ThreadPolicy p0) {}
    public void setVmPolicy(android.os.StrictMode.VmPolicy p0) {}

    public static class Builder {
        public android.os.StrictMode.VmPolicy build() { return null; }
        public Object permitUnsafeIntentLaunch() { return null; }
    }

    public static class ThreadPolicy {
    }

    public static class VmPolicy {
    }
}
