// @generated by gen-shims.py — do not edit by hand
package android.os;

public class SystemClock {
    public long currentThreadTimeMillis() { return 0; }
    public long elapsedRealtime() { return 0; }
    public long elapsedRealtimeNanos() { return 0; }
    public void sleep(long p0) {}
    public long uptimeMillis() { return 0; }
}
