// @generated by gen-shims.py — do not edit by hand
package android.os;

public class UserHandle {
    public android.os.UserHandle getUserHandleForUid(int p0) { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
