// @generated by gen-shims.py — do not edit by hand
package android.os;

public class UserManager {
    public android.os.Bundle getApplicationRestrictions(java.lang.String p0) { return null; }
    public boolean hasUserRestriction(java.lang.String p0) { return false; }
    public boolean isUserRunning(android.os.UserHandle p0) { return false; }
    public boolean isUserUnlocked() { return false; }
}
