// @generated by gen-shims.py — do not edit by hand
package android.os;

public class VibrationEffect {
    public android.os.VibrationEffect createOneShot(long p0, int p1) { return null; }
    public android.os.VibrationEffect createWaveform(long[] p0, int p1) { return null; }
}
