// @generated by gen-shims.py — do not edit by hand
package android.os;

public class Vibrator {
    public boolean areAllPrimitivesSupported(int[] p0) { return false; }
    public void cancel() {}
    public boolean hasAmplitudeControl() { return false; }
    public boolean hasVibrator() { return false; }
    public void vibrate(long p0) {}
    public void vibrate(long[] p0, int p1) {}
}
