// @generated by gen-shims.py — do not edit by hand
package android.os;

public class VibrationAttributes {

    public static class Builder {
        public android.os.VibrationAttributes build() { return null; }
        public android.os.VibrationAttributes.Builder setUsage(int p0) { return null; }
    }
}
