// @generated by gen-shims.py — do not edit by hand
package android.os;

public class WorkSource {
    public boolean add(android.os.WorkSource p0) { return false; }
    public boolean equals(java.lang.Object p0) { return false; }
}
