// @generated by gen-shims.py — do not edit by hand
package android.app;

public class ActivityOptions {
    public android.graphics.Rect getLaunchBounds() { return null; }
    public int getLaunchDisplayId() { return 0; }
    public android.app.ActivityOptions makeBasic() { return null; }
    public android.app.ActivityOptions makeClipRevealAnimation(android.view.View p0, int p1, int p2, int p3, int p4) { return null; }
    public android.app.ActivityOptions makeCustomAnimation(android.content.Context p0, int p1, int p2) { return null; }
    public android.app.ActivityOptions makeScaleUpAnimation(android.view.View p0, int p1, int p2, int p3, int p4) { return null; }
    public android.app.ActivityOptions makeSceneTransitionAnimation(android.app.Activity p0, android.view.View p1, java.lang.String p2) { return null; }
    public android.app.ActivityOptions makeSceneTransitionAnimation(android.app.Activity p0, android.util.Pair[] p1) { return null; }
    public android.app.ActivityOptions makeTaskLaunchBehind() { return null; }
    public android.app.ActivityOptions makeThumbnailScaleUpAnimation(android.view.View p0, android.graphics.Bitmap p1, int p2, int p3) { return null; }
    public void requestUsageTimeReport(android.app.PendingIntent p0) {}
    public void setAllowPassThroughOnTouchOutside(boolean p0) {}
    public android.app.ActivityOptions setLaunchBounds(android.graphics.Rect p0) { return null; }
    public android.app.ActivityOptions setLaunchDisplayId(int p0) { return null; }
    public void setPendingIntentBackgroundActivityLaunchAllowed(boolean p0) {}
    public android.app.ActivityOptions setPendingIntentBackgroundActivityStartMode(int p0) { return null; }
    public android.app.ActivityOptions setShareIdentityEnabled(boolean p0) { return null; }
    public android.os.Bundle toBundle() { return null; }
    public void update(android.app.ActivityOptions p0) {}
}
