// @generated by gen-shims.py — do not edit by hand
package android.app;

public class ActivityManager {
    public boolean clearApplicationUserData() { return false; }
    public java.util.List getAppTasks() { return null; }
    public android.content.pm.ConfigurationInfo getDeviceConfigurationInfo() { return null; }
    public java.util.List getHistoricalProcessExitReasons(java.lang.String p0, int p1, int p2) { return null; }
    public int getLargeMemoryClass() { return 0; }
    public int getLauncherLargeIconSize() { return 0; }
    public int getMemoryClass() { return 0; }
    public void getMemoryInfo(android.app.ActivityManager.MemoryInfo p0) {}
    public void getMyMemoryState(android.app.ActivityManager.RunningAppProcessInfo p0) {}
    public android.os.Debug.MemoryInfo[] getProcessMemoryInfo(int[] p0) { return null; }
    public java.util.List getProcessesInErrorState() { return null; }
    public java.util.List getRunningAppProcesses() { return null; }
    public java.util.List getRunningServices(int p0) { return null; }
    public java.util.List getRunningTasks(int p0) { return null; }
    public boolean isLowRamDevice() { return false; }

    public static class AppTask {
        public android.app.ActivityManager.RecentTaskInfo getTaskInfo() { return null; }
    }

    public static class MemoryInfo {
    }

    public static class ProcessErrorStateInfo {
    }

    public static class RecentTaskInfo {
    }

    public static class RunningAppProcessInfo {
    }

    public static class RunningServiceInfo {
    }

    public static class RunningTaskInfo {
    }

    public static class TaskDescription {
    }
}
