// @generated by gen-shims.py — do not edit by hand
package android.app;

public class ActionBar {
    public int getDisplayOptions() { return 0; }
    public java.lang.CharSequence getSubtitle() { return null; }
    public android.content.Context getThemedContext() { return null; }
    public void setDisplayShowHomeEnabled(boolean p0) {}
    public void setHomeActionContentDescription(int p0) {}
    public void setHomeAsUpIndicator(android.graphics.drawable.Drawable p0) {}
    public void setSubtitle(java.lang.CharSequence p0) {}
}
