// @generated by gen-shims.py — do not edit by hand
package android.app;

public class AppComponentFactory {
    public android.app.Activity instantiateActivity(java.lang.ClassLoader p0, java.lang.String p1, android.content.Intent p2) { return null; }
    public android.app.Application instantiateApplication(java.lang.ClassLoader p0, java.lang.String p1) { return null; }
    public android.content.ContentProvider instantiateProvider(java.lang.ClassLoader p0, java.lang.String p1) { return null; }
    public android.content.BroadcastReceiver instantiateReceiver(java.lang.ClassLoader p0, java.lang.String p1, android.content.Intent p2) { return null; }
    public android.app.Service instantiateService(java.lang.ClassLoader p0, java.lang.String p1, android.content.Intent p2) { return null; }
}
