// @generated by gen-shims.py — do not edit by hand
package android.app;

public class ApplicationExitInfo {
    public int getImportance() { return 0; }
    public int getPid() { return 0; }
    public java.lang.String getProcessName() { return null; }
    public long getPss() { return 0; }
    public int getReason() { return 0; }
    public long getRss() { return 0; }
    public long getTimestamp() { return 0; }
    public java.io.InputStream getTraceInputStream() { return null; }
    public java.lang.String toString() { return null; }
}
