// @generated by gen-shims.py — do not edit by hand
package android.app;

public class Application {
    public void attachBaseContext(android.content.Context p0) {}
    public android.content.Context getApplicationContext() { return null; }
    public java.io.File getCacheDir() { return null; }
    public android.content.ContentResolver getContentResolver() { return null; }
    public java.io.File getFilesDir() { return null; }
    public android.content.pm.PackageManager getPackageManager() { return null; }
    public java.lang.String getPackageName() { return null; }
    public java.lang.String getProcessName() { return null; }
    public android.content.res.Resources getResources() { return null; }
    public android.content.SharedPreferences getSharedPreferences(java.lang.String p0, int p1) { return null; }
    public java.lang.String getString(int p0) { return null; }
    public java.lang.Object getSystemService(java.lang.String p0) { return null; }
    public java.lang.CharSequence getText(int p0) { return null; }
    public void onConfigurationChanged(android.content.res.Configuration p0) {}
    public void onCreate() {}
    public void onLowMemory() {}
    public void onTerminate() {}
    public void onTrimMemory(int p0) {}
    public void registerActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks p0) {}
    public void registerComponentCallbacks(android.content.ComponentCallbacks p0) {}
    public void startActivity(android.content.Intent p0) {}
    public void unregisterActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks p0) {}

    public static class ActivityLifecycleCallbacks {
        public void onActivityCreated(android.app.Activity p0, android.os.Bundle p1) {}
        public void onActivityDestroyed(android.app.Activity p0) {}
        public void onActivityPaused(android.app.Activity p0) {}
        public void onActivityResumed(android.app.Activity p0) {}
        public void onActivitySaveInstanceState(android.app.Activity p0, android.os.Bundle p1) {}
        public void onActivityStarted(android.app.Activity p0) {}
        public void onActivityStopped(android.app.Activity p0) {}
    }
}
