// @generated by gen-shims.py — do not edit by hand
package android.app;

public class AppOpsManager {
    public int checkOpNoThrow(java.lang.String p0, int p1, java.lang.String p2) { return 0; }
    public void checkPackage(int p0, java.lang.String p1) {}
    public int noteOp(java.lang.String p0, int p1, java.lang.String p2) { return 0; }
    public int noteOpNoThrow(java.lang.String p0, int p1, java.lang.String p2) { return 0; }
    public int noteProxyOp(java.lang.String p0, java.lang.String p1) { return 0; }
    public int noteProxyOpNoThrow(java.lang.String p0, java.lang.String p1) { return 0; }
    public java.lang.String permissionToOp(java.lang.String p0) { return null; }
    public void startWatchingActive(java.lang.String[] p0, java.util.concurrent.Executor p1, android.app.AppOpsManager.OnOpActiveChangedListener p2) {}
    public int unsafeCheckOpNoThrow(java.lang.String p0, int p1, java.lang.String p2) { return 0; }

    public interface OnOpActiveChangedListener {
    }
}
