// @generated by gen-shims.py — do not edit by hand
package android.app;

public class BroadcastOptions {
    public android.app.BroadcastOptions makeBasic() { return null; }
    public android.app.BroadcastOptions setShareIdentityEnabled(boolean p0) { return null; }
    public android.os.Bundle toBundle() { return null; }
}
