// @generated by gen-shims.py — do not edit by hand
package android.app;

public class DatePickerDialog {
    public android.content.Context getContext() { return null; }
    public android.view.Window getWindow() { return null; }
    public void onCreate(android.os.Bundle p0) {}

    public interface OnDateSetListener {
    }
}
