// @generated by gen-shims.py — do not edit by hand
package android.app;

public class DialogFragment {
    public void onCreate(android.os.Bundle p0) {}
    public void onDismiss(android.content.DialogInterface p0) {}
    public void onSaveInstanceState(android.os.Bundle p0) {}
    public void setShowsDialog(boolean p0) {}
    public void setTargetFragment(android.app.Fragment p0, int p1) {}
    public void show(android.app.FragmentManager p0, java.lang.String p1) {}
}
