// @generated by gen-shims.py — do not edit by hand
package android.app;

public class Dialog {
    public void addContentView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public void cancel() {}
    public void dismiss() {}
    public boolean dispatchKeyEvent(android.view.KeyEvent p0) { return false; }
    public boolean dispatchTouchEvent(android.view.MotionEvent p0) { return false; }
    public android.view.View findViewById(int p0) { return null; }
    public android.content.Context getContext() { return null; }
    public android.view.LayoutInflater getLayoutInflater() { return null; }
    public android.window.OnBackInvokedDispatcher getOnBackInvokedDispatcher() { return null; }
    public android.app.Activity getOwnerActivity() { return null; }
    public android.view.Window getWindow() { return null; }
    public void hide() {}
    public boolean isShowing() { return false; }
    public void onAttachedToWindow() {}
    public void onBackPressed() {}
    public void onCreate(android.os.Bundle p0) {}
    public void onDetachedFromWindow() {}
    public boolean onKeyDown(int p0, android.view.KeyEvent p1) { return false; }
    public boolean onKeyUp(int p0, android.view.KeyEvent p1) { return false; }
    public void onRestoreInstanceState(android.os.Bundle p0) {}
    public android.os.Bundle onSaveInstanceState() { return null; }
    public void onStart() {}
    public void onStop() {}
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public void onWindowAttributesChanged(android.view.WindowManager.LayoutParams p0) {}
    public boolean requestWindowFeature(int p0) { return false; }
    public android.view.View requireViewById(int p0) { return null; }
    public void setCancelable(boolean p0) {}
    public void setCanceledOnTouchOutside(boolean p0) {}
    public void setContentView(android.view.View p0) {}
    public void setContentView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public void setDismissMessage(android.os.Message p0) {}
    public void setOnCancelListener(android.content.DialogInterface.OnCancelListener p0) {}
    public void setOnDismissListener(android.content.DialogInterface.OnDismissListener p0) {}
    public void setOnKeyListener(android.content.DialogInterface.OnKeyListener p0) {}
    public void setOnShowListener(android.content.DialogInterface.OnShowListener p0) {}
    public void setOwnerActivity(android.app.Activity p0) {}
    public void setTitle(int p0) {}
    public void show() {}
}
