// @generated by gen-shims.py — do not edit by hand
package android.app;

public class Fragment {
    public void dump(java.lang.String p0, java.io.FileDescriptor p1, java.io.PrintWriter p2, java.lang.String[] p3) {}
    public boolean equals(java.lang.Object p0) { return false; }
    public android.app.Activity getActivity() { return null; }
    public android.os.Bundle getArguments() { return null; }
    public android.content.Context getContext() { return null; }
    public android.app.FragmentManager getFragmentManager() { return null; }
    public int getId() { return 0; }
    public android.app.Fragment getParentFragment() { return null; }
    public android.content.res.Resources getResources() { return null; }
    public boolean getRetainInstance() { return false; }
    public java.lang.String getTag() { return null; }
    public android.app.Fragment getTargetFragment() { return null; }
    public int getTargetRequestCode() { return 0; }
    public boolean getUserVisibleHint() { return false; }
    public android.view.View getView() { return null; }
    public boolean isAdded() { return false; }
    public boolean isDetached() { return false; }
    public boolean isHidden() { return false; }
    public boolean isInLayout() { return false; }
    public boolean isRemoving() { return false; }
    public boolean isResumed() { return false; }
    public boolean isVisible() { return false; }
    public void onActivityCreated(android.os.Bundle p0) {}
    public void onActivityResult(int p0, int p1, android.content.Intent p2) {}
    public void onAttach(android.app.Activity p0) {}
    public void onCreate(android.os.Bundle p0) {}
    public void onDestroy() {}
    public void onDestroyView() {}
    public void onDetach() {}
    public void onPause() {}
    public void onResume() {}
    public void onSaveInstanceState(android.os.Bundle p0) {}
    public void onStart() {}
    public void onStop() {}
    public void onViewCreated(android.view.View p0, android.os.Bundle p1) {}
    public void registerForContextMenu(android.view.View p0) {}
    public void requestPermissions(java.lang.String[] p0, int p1) {}
    public void setArguments(android.os.Bundle p0) {}
    public void setEnterTransition(android.transition.Transition p0) {}
    public void setExitTransition(android.transition.Transition p0) {}
    public void setHasOptionsMenu(boolean p0) {}
    public void setMenuVisibility(boolean p0) {}
    public void setReenterTransition(android.transition.Transition p0) {}
    public void setRetainInstance(boolean p0) {}
    public void setReturnTransition(android.transition.Transition p0) {}
    public void setSharedElementEnterTransition(android.transition.Transition p0) {}
    public void setTargetFragment(android.app.Fragment p0, int p1) {}
    public void setUserVisibleHint(boolean p0) {}
    public void startActivity(android.content.Intent p0) {}
    public void startActivityForResult(android.content.Intent p0, int p1) {}
    public java.lang.String toString() { return null; }
    public void unregisterForContextMenu(android.view.View p0) {}
}
