// @generated by gen-shims.py — do not edit by hand
package android.app;

public class FragmentTransaction {
    public android.app.FragmentTransaction add(android.app.Fragment p0, java.lang.String p1) { return null; }
    public android.app.FragmentTransaction add(int p0, android.app.Fragment p1, java.lang.String p2) { return null; }
    public android.app.FragmentTransaction addSharedElement(android.view.View p0, java.lang.String p1) { return null; }
    public android.app.FragmentTransaction addToBackStack(java.lang.String p0) { return null; }
    public int commit() { return 0; }
    public int commitAllowingStateLoss() { return 0; }
    public android.app.FragmentTransaction remove(android.app.Fragment p0) { return null; }
    public android.app.FragmentTransaction replace(int p0, android.app.Fragment p1) { return null; }
    public android.app.FragmentTransaction replace(int p0, android.app.Fragment p1, java.lang.String p2) { return null; }
}
