// @generated by gen-shims.py — do not edit by hand
package android.app;

public class GrammaticalInflectionManager {
    public int getApplicationGrammaticalGender() { return 0; }
    public void setRequestedApplicationGrammaticalGender(int p0) {}
}
