// @generated by gen-shims.py — do not edit by hand
package android.app;

public class KeyguardManager {
    public android.content.Intent createConfirmDeviceCredentialIntent(java.lang.CharSequence p0, java.lang.CharSequence p1) { return null; }
    public boolean inKeyguardRestrictedInputMode() { return false; }
    public boolean isDeviceLocked() { return false; }
    public boolean isDeviceSecure() { return false; }
    public boolean isKeyguardLocked() { return false; }
    public boolean isKeyguardSecure() { return false; }
}
