// @generated by gen-shims.py — do not edit by hand
package android.app;

public class LocaleManager {
    public android.os.LocaleList getApplicationLocales() { return null; }
    public android.os.LocaleList getSystemLocales() { return null; }
    public void setApplicationLocales(android.os.LocaleList p0) {}
}
