// @generated by gen-shims.py — do not edit by hand
package android.app;

public class NotificationChannelGroup {
    public java.util.List getChannels() { return null; }
    public java.lang.String getDescription() { return null; }
    public java.lang.String getId() { return null; }
    public java.lang.CharSequence getName() { return null; }
    public boolean isBlocked() { return false; }
    public void setDescription(java.lang.String p0) {}
}
