// @generated by gen-shims.py — do not edit by hand
package android.app;

public class Notification {
    public boolean getAllowSystemGeneratedContextualActions() { return false; }
    public int getBadgeIconType() { return 0; }
    public android.app.Notification.BubbleMetadata getBubbleMetadata() { return null; }
    public java.lang.String getChannelId() { return null; }
    public java.lang.String getGroup() { return null; }
    public int getGroupAlertBehavior() { return 0; }
    public android.graphics.drawable.Icon getLargeIcon() { return null; }
    public android.content.LocusId getLocusId() { return null; }
    public java.lang.CharSequence getSettingsText() { return null; }
    public java.lang.String getShortcutId() { return null; }
    public android.graphics.drawable.Icon getSmallIcon() { return null; }
    public java.lang.String getSortKey() { return null; }
    public long getTimeoutAfter() { return 0; }
    public boolean hasPromotableCharacteristics() { return false; }
    public void setLatestEventInfo(android.content.Context p0, java.lang.CharSequence p1, java.lang.CharSequence p2, android.app.PendingIntent p3) {}
    public void writeToParcel(android.os.Parcel p0, int p1) {}

    public static class Action {
        public boolean getAllowGeneratedReplies() { return false; }
        public android.os.Bundle getExtras() { return null; }
        public android.graphics.drawable.Icon getIcon() { return null; }
        public android.app.RemoteInput[] getRemoteInputs() { return null; }
        public int getSemanticAction() { return 0; }
        public boolean isAuthenticationRequired() { return false; }
        public boolean isContextual() { return false; }
    }

    public static class BigPictureStyle {
        public android.app.Notification.BigPictureStyle bigLargeIcon(android.graphics.Bitmap p0) { return null; }
        public android.app.Notification.BigPictureStyle bigPicture(android.graphics.Bitmap p0) { return null; }
        public android.app.Notification.BigPictureStyle setBigContentTitle(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.BigPictureStyle setContentDescription(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.BigPictureStyle setSummaryText(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.BigPictureStyle showBigPictureWhenCollapsed(boolean p0) { return null; }
    }

    public static class BigTextStyle {
        public android.app.Notification.BigTextStyle bigText(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.BigTextStyle setBigContentTitle(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.BigTextStyle setSummaryText(java.lang.CharSequence p0) { return null; }
    }

    public static class BubbleMetadata {
        public boolean getAutoExpandBubble() { return false; }
        public android.app.PendingIntent getDeleteIntent() { return null; }
        public int getDesiredHeight() { return 0; }
        public int getDesiredHeightResId() { return 0; }
        public android.graphics.drawable.Icon getIcon() { return null; }
        public android.app.PendingIntent getIntent() { return null; }
        public java.lang.String getShortcutId() { return null; }
        public boolean isNotificationSuppressed() { return false; }
    }

    public static class Builder {
        public android.app.Notification.BubbleMetadata build() { return null; }
        public Object setAutoExpandBubble(boolean p0) { return null; }
        public Object setDeleteIntent(android.app.PendingIntent p0) { return null; }
        public Object setDesiredHeight(int p0) { return null; }
        public Object setDesiredHeightResId(int p0) { return null; }
        public Object setIcon(android.graphics.drawable.Icon p0) { return null; }
        public Object setIntent(android.app.PendingIntent p0) { return null; }
        public Object setSuppressNotification(boolean p0) { return null; }
    }

    public static class CallStyle {
        public android.app.Notification.CallStyle forIncomingCall(android.app.Person p0, android.app.PendingIntent p1, android.app.PendingIntent p2) { return null; }
        public android.app.Notification.CallStyle forOngoingCall(android.app.Person p0, android.app.PendingIntent p1) { return null; }
        public android.app.Notification.CallStyle forScreeningCall(android.app.Person p0, android.app.PendingIntent p1, android.app.PendingIntent p2) { return null; }
        public android.app.Notification.CallStyle setAnswerButtonColorHint(int p0) { return null; }
        public void setBuilder(android.app.Notification.Builder p0) {}
        public android.app.Notification.CallStyle setDeclineButtonColorHint(int p0) { return null; }
        public android.app.Notification.CallStyle setIsVideo(boolean p0) { return null; }
        public android.app.Notification.CallStyle setVerificationIcon(android.graphics.drawable.Icon p0) { return null; }
        public android.app.Notification.CallStyle setVerificationText(java.lang.CharSequence p0) { return null; }
    }

    public static class DecoratedCustomViewStyle {
    }

    public static class DecoratedMediaCustomViewStyle {
    }

    public static class InboxStyle {
        public android.app.Notification.InboxStyle addLine(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.InboxStyle setBigContentTitle(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.InboxStyle setSummaryText(java.lang.CharSequence p0) { return null; }
    }

    public static class MediaStyle {
        public android.app.Notification.MediaStyle setMediaSession(android.media.session.MediaSession.Token p0) { return null; }
        public android.app.Notification.MediaStyle setRemotePlaybackInfo(java.lang.CharSequence p0, int p1, android.app.PendingIntent p2) { return null; }
        public android.app.Notification.MediaStyle setShowActionsInCompactView(int[] p0) { return null; }
    }

    public static class Message {
        public Object setData(java.lang.String p0, android.net.Uri p1) { return null; }
    }

    public static class MessagingStyle {
        public android.app.Notification.MessagingStyle addHistoricMessage(Object p0) { return null; }
        public android.app.Notification.MessagingStyle addMessage(Object p0) { return null; }
        public void setBuilder(android.app.Notification.Builder p0) {}
        public android.app.Notification.MessagingStyle setConversationTitle(java.lang.CharSequence p0) { return null; }
        public android.app.Notification.MessagingStyle setGroupConversation(boolean p0) { return null; }
    }

    public static class Point {
        public Object setColor(int p0) { return null; }
        public Object setId(int p0) { return null; }
    }

    public static class ProgressStyle {
        public android.app.Notification.ProgressStyle addProgressPoint(Object p0) { return null; }
        public android.app.Notification.ProgressStyle addProgressSegment(Object p0) { return null; }
        public android.app.Notification.ProgressStyle setProgress(int p0) { return null; }
        public android.app.Notification.ProgressStyle setProgressEndIcon(android.graphics.drawable.Icon p0) { return null; }
        public android.app.Notification.ProgressStyle setProgressIndeterminate(boolean p0) { return null; }
        public android.app.Notification.ProgressStyle setProgressStartIcon(android.graphics.drawable.Icon p0) { return null; }
        public android.app.Notification.ProgressStyle setProgressTrackerIcon(android.graphics.drawable.Icon p0) { return null; }
        public android.app.Notification.ProgressStyle setStyledByProgress(boolean p0) { return null; }
    }

    public static class Segment {
        public Object setColor(int p0) { return null; }
        public Object setId(int p0) { return null; }
    }

    public static class Style {
        public void setBuilder(android.app.Notification.Builder p0) {}
    }
}
