// @generated by gen-shims.py — do not edit by hand
package android.app;

public class PendingIntent {
    public void cancel() {}
    public boolean equals(java.lang.Object p0) { return false; }
    public android.app.PendingIntent getActivities(android.content.Context p0, int p1, android.content.Intent[] p2, int p3) { return null; }
    public android.app.PendingIntent getActivities(android.content.Context p0, int p1, android.content.Intent[] p2, int p3, android.os.Bundle p4) { return null; }
    public android.app.PendingIntent getActivity(android.content.Context p0, int p1, android.content.Intent p2, int p3) { return null; }
    public android.app.PendingIntent getActivity(android.content.Context p0, int p1, android.content.Intent p2, int p3, android.os.Bundle p4) { return null; }
    public android.app.PendingIntent getBroadcast(android.content.Context p0, int p1, android.content.Intent p2, int p3) { return null; }
    public java.lang.String getCreatorPackage() { return null; }
    public android.app.PendingIntent getForegroundService(android.content.Context p0, int p1, android.content.Intent p2, int p3) { return null; }
    public android.content.IntentSender getIntentSender() { return null; }
    public android.app.PendingIntent getService(android.content.Context p0, int p1, android.content.Intent p2, int p3) { return null; }
    public java.lang.String getTargetPackage() { return null; }
    public int hashCode() { return 0; }
    public android.app.PendingIntent readPendingIntentOrNullFromParcel(android.os.Parcel p0) { return null; }
    public void send(int p0, android.app.PendingIntent.OnFinished p1, android.os.Handler p2) {}
    public void send(android.content.Context p0, int p1, android.content.Intent p2, android.app.PendingIntent.OnFinished p3, android.os.Handler p4, java.lang.String p5) {}
    public void send(android.content.Context p0, int p1, android.content.Intent p2, android.app.PendingIntent.OnFinished p3, android.os.Handler p4, java.lang.String p5, android.os.Bundle p6) {}
    public void send() {}
    public void send(android.os.Bundle p0) {}
    public void writePendingIntentOrNullToParcel(android.app.PendingIntent p0, android.os.Parcel p1) {}
    public void writeToParcel(android.os.Parcel p0, int p1) {}

    public static class OnFinished {
        public void onSendFinished(android.app.PendingIntent p0, android.content.Intent p1, int p2, java.lang.String p3, android.os.Bundle p4) {}
    }
}
