// @generated by gen-shims.py — do not edit by hand
package android.app;

public class PictureInPictureParams {

    public static class Builder {
        public android.app.PictureInPictureParams build() { return null; }
        public android.app.PictureInPictureParams.Builder setActions(java.util.List p0) { return null; }
        public android.app.PictureInPictureParams.Builder setAspectRatio(android.util.Rational p0) { return null; }
        public android.app.PictureInPictureParams.Builder setAutoEnterEnabled(boolean p0) { return null; }
        public android.app.PictureInPictureParams.Builder setSourceRectHint(android.graphics.Rect p0) { return null; }
    }
}
