// @generated by gen-shims.py — do not edit by hand
package android.app;

public class PictureInPictureUiState {
    public boolean isStashed() { return false; }
    public boolean isTransitioningToPip() { return false; }
}
