// @generated by gen-shims.py — do not edit by hand
package android.app;

public class ProgressDialog {
    public void dismiss() {}
    public void hide() {}
    public boolean isShowing() { return false; }
    public boolean requestWindowFeature(int p0) { return false; }
    public void setCancelable(boolean p0) {}
    public void setCanceledOnTouchOutside(boolean p0) {}
    public void setIndeterminate(boolean p0) {}
    public void setMax(int p0) {}
    public void setMessage(java.lang.CharSequence p0) {}
    public void setOnCancelListener(android.content.DialogInterface.OnCancelListener p0) {}
    public void setProgress(int p0) {}
    public void setProgressNumberFormat(java.lang.String p0) {}
    public void setProgressStyle(int p0) {}
    public void setTitle(java.lang.CharSequence p0) {}
    public android.app.ProgressDialog show(android.content.Context p0, java.lang.CharSequence p1, java.lang.CharSequence p2, boolean p3) { return null; }
    public void show() {}
}
