// @generated by gen-shims.py — do not edit by hand
package android.app;

public class RemoteAction {
    public android.app.PendingIntent getActionIntent() { return null; }
    public java.lang.CharSequence getContentDescription() { return null; }
    public android.graphics.drawable.Icon getIcon() { return null; }
    public java.lang.CharSequence getTitle() { return null; }
    public boolean isEnabled() { return false; }
    public void setEnabled(boolean p0) {}
    public void setShouldShowIcon(boolean p0) {}
    public boolean shouldShowIcon() { return false; }
}
