// @generated by gen-shims.py — do not edit by hand
package android.app;

public class SearchManager {
    public android.app.SearchableInfo getSearchableInfo(android.content.ComponentName p0) { return null; }
}
