// @generated by gen-shims.py — do not edit by hand
package android.app;

public class Service {
    public void attachBaseContext(android.content.Context p0) {}
    public void dump(java.io.FileDescriptor p0, java.io.PrintWriter p1, java.lang.String[] p2) {}
    public android.app.Application getApplication() { return null; }
    public android.content.Context getApplicationContext() { return null; }
    public java.lang.ClassLoader getClassLoader() { return null; }
    public android.content.pm.PackageManager getPackageManager() { return null; }
    public android.content.res.Resources getResources() { return null; }
    public java.lang.String getString(int p0) { return null; }
    public java.lang.Object getSystemService(java.lang.String p0) { return null; }
    public void onCreate() {}
    public void onDestroy() {}
    public void onRebind(android.content.Intent p0) {}
    public void onStart(android.content.Intent p0, int p1) {}
    public int onStartCommand(android.content.Intent p0, int p1, int p2) { return 0; }
    public void onTaskRemoved(android.content.Intent p0) {}
    public void onTimeout(int p0, int p1) {}
    public void onTimeout(int p0) {}
    public boolean onUnbind(android.content.Intent p0) { return false; }
    public void sendBroadcast(android.content.Intent p0) {}
    public void startForeground(int p0, android.app.Notification p1) {}
    public void startForeground(int p0, android.app.Notification p1, int p2) {}
    public android.content.ComponentName startForegroundService(android.content.Intent p0) { return null; }
    public void stopForeground(int p0) {}
    public void stopSelf() {}
    public void stopSelf(int p0) {}
    public boolean stopSelfResult(int p0) { return false; }
}
