// @generated by gen-shims.py — do not edit by hand
package android.app;

public interface SharedElementCallback {
    android.os.Parcelable onCaptureSharedElementSnapshot(android.view.View p0, android.graphics.Matrix p1, android.graphics.RectF p2);
    android.view.View onCreateSnapshotView(android.content.Context p0, android.os.Parcelable p1);

    public interface OnSharedElementsReadyListener {
        void onSharedElementsReady();
    }
}
