// @generated by gen-shims.py — do not edit by hand
package android.app;

public class UiModeManager {
    public void addContrastChangeListener(java.util.concurrent.Executor p0, android.app.UiModeManager.ContrastChangeListener p1) {}
    public float getContrast() { return 0f; }
    public int getCurrentModeType() { return 0; }
    public int getNightMode() { return 0; }
    public void removeContrastChangeListener(android.app.UiModeManager.ContrastChangeListener p0) {}
    public void setApplicationNightMode(int p0) {}

    public interface ContrastChangeListener {
    }
}
