// @generated by gen-shims.py — do not edit by hand
package android.content.pm.verify.domain;

public class DomainVerificationUserState {
    public java.util.Map getHostToStateMap() { return null; }
}
