// @generated by gen-shims.py — do not edit by hand
package android.service.wallpaper;

public class WallpaperService {
    public void onCreate() {}
    public void onDestroy() {}

    public static class Engine {
        public android.os.Bundle onCommand(java.lang.String p0, int p1, int p2, int p3, android.os.Bundle p4, boolean p5) { return null; }
        public android.app.WallpaperColors onComputeColors() { return null; }
        public void onCreate(android.view.SurfaceHolder p0) {}
        public void onDestroy() {}
        public void onOffsetsChanged(float p0, float p1, float p2, float p3, int p4, int p5) {}
        public void onSurfaceChanged(android.view.SurfaceHolder p0, int p1, int p2, int p3) {}
        public void onSurfaceCreated(android.view.SurfaceHolder p0) {}
        public void onSurfaceDestroyed(android.view.SurfaceHolder p0) {}
        public void onVisibilityChanged(boolean p0) {}
    }
}
