// @generated by gen-shims.py — do not edit by hand
package android.view.textclassifier;

public class TextClassificationManager {
    public android.view.textclassifier.TextClassifier createTextClassificationSession(android.view.textclassifier.TextClassificationContext p0) { return null; }
    public android.view.textclassifier.TextClassifier getTextClassifier() { return null; }
}
