// @generated by gen-shims.py — do not edit by hand
package android.view.textclassifier;

public class TextClassification {
    public java.util.List getActions() { return null; }
    public android.graphics.drawable.Drawable getIcon() { return null; }
    public android.content.Intent getIntent() { return null; }
    public java.lang.CharSequence getLabel() { return null; }
    public android.view.View.OnClickListener getOnClickListener() { return null; }
    public java.lang.String getText() { return null; }
    public int hashCode() { return 0; }

    public static class Builder {
        public android.view.textclassifier.TextClassification.Request build() { return null; }
        public Object setDefaultLocales(android.os.LocaleList p0) { return null; }
    }

    public static class Request {
    }
}
