// @generated by gen-shims.py — do not edit by hand
package android.view.textclassifier;

public class TextClassifier {
    public android.view.textclassifier.TextClassification classifyText(android.view.textclassifier.TextClassification.Request p0) { return null; }
    public boolean isDestroyed() { return false; }
    public android.view.textclassifier.TextSelection suggestSelection(android.view.textclassifier.TextSelection.Request p0) { return null; }
}
