// @generated by gen-shims.py — do not edit by hand
package android.media.audiofx;

public class AudioEffect {
    public boolean getEnabled() { return false; }
    public android.media.audiofx.AudioEffect.Descriptor[] queryEffects() { return null; }
    public void release() {}
    public int setEnabled(boolean p0) { return 0; }

    public static class Descriptor {
    }
}
