// @generated by gen-shims.py — do not edit by hand
package android.media.audiofx;

public class LoudnessEnhancer {
    public float getTargetGain() { return 0f; }
    public void setTargetGain(int p0) {}
}
