// @generated by gen-shims.py — do not edit by hand
package android.service.credentials;

public class BeginGetCredentialOption {
    public android.os.Bundle getCandidateQueryData() { return null; }
    public java.lang.String getId() { return null; }
    public java.lang.String getType() { return null; }
}
