// @generated by gen-shims.py — do not edit by hand
package android.service.credentials;

public class BeginGetCredentialRequest {
    public java.util.List getBeginGetCredentialOptions() { return null; }
    public android.service.credentials.CallingAppInfo getCallingAppInfo() { return null; }

    public static class Builder {
        public android.service.credentials.BeginGetCredentialRequest build() { return null; }
        public android.service.credentials.BeginGetCredentialRequest.Builder setBeginGetCredentialOptions(java.util.List p0) { return null; }
        public android.service.credentials.BeginGetCredentialRequest.Builder setCallingAppInfo(android.service.credentials.CallingAppInfo p0) { return null; }
    }
}
