// @generated by gen-shims.py — do not edit by hand
package android.service.credentials;

public class BeginGetCredentialResponse {
    public java.util.List getActions() { return null; }
    public java.util.List getAuthenticationActions() { return null; }
    public java.util.List getCredentialEntries() { return null; }
    public android.service.credentials.RemoteEntry getRemoteCredentialEntry() { return null; }

    public static class Builder {
        public android.service.credentials.BeginGetCredentialResponse.Builder addAction(android.service.credentials.Action p0) { return null; }
        public android.service.credentials.BeginGetCredentialResponse.Builder addAuthenticationAction(android.service.credentials.Action p0) { return null; }
        public android.service.credentials.BeginGetCredentialResponse.Builder addCredentialEntry(android.service.credentials.CredentialEntry p0) { return null; }
        public android.service.credentials.BeginGetCredentialResponse build() { return null; }
        public android.service.credentials.BeginGetCredentialResponse.Builder setRemoteCredentialEntry(android.service.credentials.RemoteEntry p0) { return null; }
    }
}
