// @generated by gen-shims.py — do not edit by hand
package android.service.credentials;

public class CallingAppInfo {
    public java.lang.String getOrigin() { return null; }
    public java.lang.String getPackageName() { return null; }
    public android.content.pm.SigningInfo getSigningInfo() { return null; }
}
