// @generated by gen-shims.py — do not edit by hand
package android.service.credentials;

public class CreateCredentialRequest {
    public android.service.credentials.CallingAppInfo getCallingAppInfo() { return null; }
    public android.os.Bundle getData() { return null; }
    public java.lang.String getType() { return null; }
}
