// @generated by gen-shims.py — do not edit by hand
package android.service.credentials;

public class GetCredentialRequest {
    public android.service.credentials.CallingAppInfo getCallingAppInfo() { return null; }
    public java.util.List getCredentialOptions() { return null; }
}
