// @generated by gen-shims.py — do not edit by hand
package android.hardware;

public class Camera {
    public void autoFocus(android.hardware.Camera.AutoFocusCallback p0) {}
    public void cancelAutoFocus() {}
    public void getCameraInfo(int p0, android.hardware.Camera.CameraInfo p1) {}
    public int getNumberOfCameras() { return 0; }
    public android.hardware.Camera.Parameters getParameters() { return null; }
    public android.hardware.Camera open(int p0) { return null; }
    public void release() {}
    public void setDisplayOrientation(int p0) {}
    public void setOneShotPreviewCallback(android.hardware.Camera.PreviewCallback p0) {}
    public void setParameters(android.hardware.Camera.Parameters p0) {}
    public void setPreviewDisplay(android.view.SurfaceHolder p0) {}
    public void setPreviewTexture(android.graphics.SurfaceTexture p0) {}
    public void startPreview() {}
    public void stopPreview() {}

    public static class Area {
    }

    public interface AutoFocusCallback {
    }

    public static class CameraInfo {
    }

    public static class Parameters {
        public java.lang.String flatten() { return null; }
        public java.lang.String getColorEffect() { return null; }
        public int getExposureCompensation() { return 0; }
        public float getExposureCompensationStep() { return 0f; }
        public java.lang.String getFlashMode() { return null; }
        public java.util.List getFocusAreas() { return null; }
        public java.lang.String getFocusMode() { return null; }
        public int getMaxExposureCompensation() { return 0; }
        public int getMaxNumFocusAreas() { return 0; }
        public int getMaxNumMeteringAreas() { return 0; }
        public java.util.List getMeteringAreas() { return null; }
        public int getMinExposureCompensation() { return 0; }
        public int getPreviewFormat() { return 0; }
        public void getPreviewFpsRange(int[] p0) {}
        public android.hardware.Camera.Size getPreviewSize() { return null; }
        public java.lang.String getSceneMode() { return null; }
        public java.util.List getSupportedColorEffects() { return null; }
        public java.util.List getSupportedFlashModes() { return null; }
        public java.util.List getSupportedFocusModes() { return null; }
        public java.util.List getSupportedPreviewFpsRange() { return null; }
        public java.util.List getSupportedPreviewSizes() { return null; }
        public java.util.List getSupportedSceneModes() { return null; }
        public boolean getVideoStabilization() { return false; }
        public boolean isVideoStabilizationSupported() { return false; }
        public void setColorEffect(java.lang.String p0) {}
        public void setExposureCompensation(int p0) {}
        public void setFlashMode(java.lang.String p0) {}
        public void setFocusAreas(java.util.List p0) {}
        public void setFocusMode(java.lang.String p0) {}
        public void setMeteringAreas(java.util.List p0) {}
        public void setPreviewFpsRange(int p0, int p1) {}
        public void setPreviewSize(int p0, int p1) {}
        public void setSceneMode(java.lang.String p0) {}
        public void setVideoStabilization(boolean p0) {}
        public void unflatten(java.lang.String p0) {}
    }

    public interface PreviewCallback {
    }

    public static class Size {
    }
}
