// @generated by gen-shims.py — do not edit by hand
package android.hardware;

public class SensorManager {
    public android.hardware.Sensor getDefaultSensor(int p0) { return null; }
    public float[] getOrientation(float[] p0, float[] p1) { return null; }
    public boolean getRotationMatrix(float[] p0, float[] p1, float[] p2, float[] p3) { return false; }
    public void getRotationMatrixFromVector(float[] p0, float[] p1) {}
    public java.util.List getSensorList(int p0) { return null; }
    public boolean registerListener(android.hardware.SensorEventListener p0, android.hardware.Sensor p1, int p2) { return false; }
    public boolean registerListener(android.hardware.SensorEventListener p0, android.hardware.Sensor p1, int p2, android.os.Handler p3) { return false; }
    public boolean remapCoordinateSystem(float[] p0, int p1, int p2, float[] p3) { return false; }
    public void unregisterListener(android.hardware.SensorEventListener p0) {}
    public void unregisterListener(android.hardware.SensorEventListener p0, android.hardware.Sensor p1) {}
}
