// @generated by gen-shims.py — do not edit by hand
package android.hardware;

public class Sensor {
    public java.lang.String getStringType() { return null; }
    public int getType() { return 0; }
    public java.lang.String getVendor() { return null; }
    public int getVersion() { return 0; }
}
