// @generated by gen-shims.py — do not edit by hand
package android.appwidget;

public class AppWidgetManager {
    public int[] getAppWidgetIds(android.content.ComponentName p0) { return null; }
    public android.appwidget.AppWidgetProviderInfo getAppWidgetInfo(int p0) { return null; }
    public android.os.Bundle getAppWidgetOptions(int p0) { return null; }
    public java.util.List getInstalledProviders() { return null; }
    public java.util.List getInstalledProvidersForPackage(java.lang.String p0, android.os.UserHandle p1) { return null; }
    public android.appwidget.AppWidgetManager getInstance(android.content.Context p0) { return null; }
    public boolean isRequestPinAppWidgetSupported() { return false; }
    public void notifyAppWidgetViewDataChanged(int p0, int p1) {}
    public void partiallyUpdateAppWidget(int p0, android.widget.RemoteViews p1) {}
    public boolean requestPinAppWidget(android.content.ComponentName p0, android.os.Bundle p1, android.app.PendingIntent p2) { return false; }
    public void updateAppWidget(int p0, android.widget.RemoteViews p1) {}
    public void updateAppWidgetOptions(int p0, android.os.Bundle p1) {}
}
