// @generated by gen-shims.py — do not edit by hand
package android.appwidget;

public class AppWidgetProviderInfo {
    public java.lang.String loadLabel(android.content.pm.PackageManager p0) { return null; }
}
