// @generated by gen-shims.py — do not edit by hand
package android.appwidget;

public interface AppWidgetProvider {
    void onAppWidgetOptionsChanged(android.content.Context p0, android.appwidget.AppWidgetManager p1, int p2, android.os.Bundle p3);
    void onDeleted(android.content.Context p0, int[] p1);
    void onDisabled(android.content.Context p0);
    void onEnabled(android.content.Context p0);
    void onReceive(android.content.Context p0, android.content.Intent p1);
    void onUpdate(android.content.Context p0, android.appwidget.AppWidgetManager p1, int[] p2);
}
