// @generated by gen-shims.py — do not edit by hand
package android.service.media;

public class MediaBrowserService {
    public android.os.Bundle getBrowserRootHints() { return null; }
    public android.media.session.MediaSessionManager.RemoteUserInfo getCurrentBrowserInfo() { return null; }
    public void notifyChildrenChanged(java.lang.String p0) {}
    public void notifyChildrenChanged(java.lang.String p0, android.os.Bundle p1) {}
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onCreate() {}
    public void setSessionToken(android.media.session.MediaSession.Token p0) {}

    public static class BrowserRoot {
    }

    public static class Result {
        public void detach() {}
        public void sendResult(java.lang.Object p0) {}
    }
}
