// @generated by gen-shims.py — do not edit by hand
package android.adservices.common;

public class AdData {

    public static class Builder {
        public android.adservices.common.AdData build() { return null; }
        public android.adservices.common.AdData.Builder setAdCounterKeys(java.util.Set p0) { return null; }
        public android.adservices.common.AdData.Builder setAdFilters(android.adservices.common.AdFilters p0) { return null; }
        public android.adservices.common.AdData.Builder setAdRenderId(java.lang.String p0) { return null; }
        public android.adservices.common.AdData.Builder setMetadata(java.lang.String p0) { return null; }
        public android.adservices.common.AdData.Builder setRenderUri(android.net.Uri p0) { return null; }
    }
}
