// @generated by gen-shims.py — do not edit by hand
package android.adservices.common;

public class AdFilters {

    public static class Builder {
        public android.adservices.common.AdFilters build() { return null; }
        public android.adservices.common.AdFilters.Builder setFrequencyCapFilters(android.adservices.common.FrequencyCapFilters p0) { return null; }
    }
}
