// @generated by gen-shims.py — do not edit by hand
package android.adservices.common;

public class AdSelectionSignals {
    public android.adservices.common.AdSelectionSignals fromString(java.lang.String p0) { return null; }
}
