// @generated by gen-shims.py — do not edit by hand
package android.adservices.common;

public class AdTechIdentifier {
    public android.adservices.common.AdTechIdentifier fromString(java.lang.String p0) { return null; }
}
