// @generated by gen-shims.py — do not edit by hand
package android.adservices.common;

public class FrequencyCapFilters {

    public static class Builder {
        public android.adservices.common.FrequencyCapFilters build() { return null; }
        public android.adservices.common.FrequencyCapFilters.Builder setKeyedFrequencyCapsForClickEvents(java.util.List p0) { return null; }
        public android.adservices.common.FrequencyCapFilters.Builder setKeyedFrequencyCapsForImpressionEvents(java.util.List p0) { return null; }
        public android.adservices.common.FrequencyCapFilters.Builder setKeyedFrequencyCapsForViewEvents(java.util.List p0) { return null; }
        public android.adservices.common.FrequencyCapFilters.Builder setKeyedFrequencyCapsForWinEvents(java.util.List p0) { return null; }
    }
}
