// @generated by gen-shims.py — do not edit by hand
package android.credentials;

public class CreateCredentialRequest {

    public static class Builder {
        public android.credentials.CreateCredentialRequest build() { return null; }
        public android.credentials.CreateCredentialRequest.Builder setAlwaysSendAppInfoToProvider(boolean p0) { return null; }
        public android.credentials.CreateCredentialRequest.Builder setIsSystemProviderRequired(boolean p0) { return null; }
        public android.credentials.CreateCredentialRequest.Builder setOrigin(java.lang.String p0) { return null; }
    }
}
