// @generated by gen-shims.py — do not edit by hand
package android.credentials;

public class Credential {
    public android.os.Bundle getData() { return null; }
    public java.lang.String getType() { return null; }
}
