// @generated by gen-shims.py — do not edit by hand
package android.credentials;

public class CredentialOption {
    public java.util.Set getAllowedProviders() { return null; }
    public android.os.Bundle getCandidateQueryData() { return null; }
    public android.os.Bundle getCredentialRetrievalData() { return null; }
    public java.lang.String getType() { return null; }
    public boolean isSystemProviderRequired() { return false; }

    public static class Builder {
        public android.credentials.CredentialOption build() { return null; }
        public android.credentials.CredentialOption.Builder setAllowedProviders(java.util.Set p0) { return null; }
        public android.credentials.CredentialOption.Builder setIsSystemProviderRequired(boolean p0) { return null; }
    }
}
