// @generated by gen-shims.py — do not edit by hand
package android.credentials;

public class CredentialManager {
    public void clearCredentialState(android.credentials.ClearCredentialStateRequest p0, android.os.CancellationSignal p1, java.util.concurrent.Executor p2, android.os.OutcomeReceiver p3) {}
    public void createCredential(android.content.Context p0, android.credentials.CreateCredentialRequest p1, android.os.CancellationSignal p2, java.util.concurrent.Executor p3, android.os.OutcomeReceiver p4) {}
    public void getCredential(android.content.Context p0, android.credentials.GetCredentialRequest p1, android.os.CancellationSignal p2, java.util.concurrent.Executor p3, android.os.OutcomeReceiver p4) {}
    public void prepareGetCredential(android.credentials.GetCredentialRequest p0, android.os.CancellationSignal p1, java.util.concurrent.Executor p2, android.os.OutcomeReceiver p3) {}
}
