// @generated by gen-shims.py — do not edit by hand
package android.credentials;

public class GetCredentialException {
    public java.lang.String getMessage() { return null; }
    public java.lang.String getType() { return null; }
}
