// @generated by gen-shims.py — do not edit by hand
package android.credentials;

public class PrepareGetCredentialResponse {
    public android.credentials.PrepareGetCredentialResponse.PendingGetCredentialHandle getPendingGetCredentialHandle() { return null; }
    public boolean hasAuthenticationResults() { return false; }
    public boolean hasCredentialResults(java.lang.String p0) { return false; }
    public boolean hasRemoteResults() { return false; }

    public static class PendingGetCredentialHandle {
    }
}
