// @generated by gen-shims.py — do not edit by hand
package android.transition;

public class ChangeBounds {
    public android.animation.Animator createAnimator(android.view.ViewGroup p0, android.transition.TransitionValues p1, android.transition.TransitionValues p2) { return null; }
}
