// @generated by gen-shims.py — do not edit by hand
package android.transition;

public class PathMotion {
    public android.graphics.Path getPath(float p0, float p1, float p2, float p3) { return null; }
}
