// @generated by gen-shims.py — do not edit by hand
package android.transition;

public class TransitionSet {
    public android.transition.TransitionSet addTransition(android.transition.Transition p0) { return null; }
    public java.util.List getTargets() { return null; }
    public android.transition.Transition getTransitionAt(int p0) { return null; }
    public int getTransitionCount() { return 0; }
    public android.transition.TransitionSet removeTransition(android.transition.Transition p0) { return null; }
    public android.transition.TransitionSet setOrdering(int p0) { return null; }
}
