// @generated by gen-shims.py — do not edit by hand
package android.transition;

public class TransitionManager {
    public void beginDelayedTransition(android.view.ViewGroup p0, android.transition.Transition p1) {}
    public void beginDelayedTransition(android.view.ViewGroup p0) {}
    public void go(android.transition.Scene p0, android.transition.Transition p1) {}
}
