// @generated by gen-shims.py — do not edit by hand
package android.transition;

public class Transition {
    public android.transition.Transition addListener(android.transition.Transition.TransitionListener p0) { return null; }
    public android.transition.Transition addTarget(android.view.View p0) { return null; }
    public android.transition.Transition clone() { return null; }
    public android.transition.Transition excludeChildren(int p0, boolean p1) { return null; }
    public android.transition.Transition excludeTarget(android.view.View p0, boolean p1) { return null; }
    public long getDuration() { return 0; }
    public android.animation.TimeInterpolator getInterpolator() { return null; }
    public android.transition.PathMotion getPathMotion() { return null; }
    public java.util.List getTargetIds() { return null; }
    public java.util.List getTargetNames() { return null; }
    public java.util.List getTargetTypes() { return null; }
    public java.util.List getTargets() { return null; }
    public android.transition.Transition removeListener(android.transition.Transition.TransitionListener p0) { return null; }
    public android.transition.Transition removeTarget(android.view.View p0) { return null; }
    public android.transition.Transition setDuration(long p0) { return null; }
    public void setEpicenterCallback(android.transition.Transition.EpicenterCallback p0) {}
    public android.transition.Transition setInterpolator(android.animation.TimeInterpolator p0) { return null; }
    public void setPathMotion(android.transition.PathMotion p0) {}
    public android.transition.Transition setStartDelay(long p0) { return null; }

    public interface EpicenterCallback {
    }

    public interface TransitionListener {
    }
}
