// @generated by gen-shims.py — do not edit by hand
package android.transition;

public class Visibility {
    public android.transition.Transition addListener(android.transition.Transition.TransitionListener p0) { return null; }
    public void captureEndValues(android.transition.TransitionValues p0) {}
    public void captureStartValues(android.transition.TransitionValues p0) {}
    public android.transition.Transition clone() { return null; }
    public android.animation.Animator onAppear(android.view.ViewGroup p0, android.view.View p1, android.transition.TransitionValues p2, android.transition.TransitionValues p3) { return null; }
    public android.animation.Animator onDisappear(android.view.ViewGroup p0, android.view.View p1, android.transition.TransitionValues p2, android.transition.TransitionValues p3) { return null; }
    public android.transition.Transition removeListener(android.transition.Transition.TransitionListener p0) { return null; }
    public void setEpicenterCallback(android.transition.Transition.EpicenterCallback p0) {}
    public android.transition.Transition setInterpolator(android.animation.TimeInterpolator p0) { return null; }
}
