// @generated by gen-shims.py — do not edit by hand
package android.telephony.mbms;

public class ServiceInfo {
    public java.lang.CharSequence getNameForLocale(java.util.Locale p0) { return null; }
    public java.util.Set getNamedContentLocales() { return null; }
}
