// @generated by gen-shims.py — do not edit by hand
package android.net.wifi;

public class WifiManager {
    public int calculateSignalLevel(int p0, int p1) { return 0; }
    public android.net.wifi.WifiManager.MulticastLock createMulticastLock(java.lang.String p0) { return null; }
    public android.net.wifi.WifiManager.WifiLock createWifiLock(int p0, java.lang.String p1) { return null; }
    public android.net.wifi.WifiManager.WifiLock createWifiLock(java.lang.String p0) { return null; }
    public android.net.wifi.WifiInfo getConnectionInfo() { return null; }
    public android.net.DhcpInfo getDhcpInfo() { return null; }
    public int getWifiState() { return 0; }
    public boolean isWifiEnabled() { return false; }
    public boolean setWifiEnabled(boolean p0) { return false; }

    public static class MulticastLock {
        public void acquire() {}
        public boolean isHeld() { return false; }
        public void release() {}
        public void setReferenceCounted(boolean p0) {}
    }

    public static class WifiLock {
        public void acquire() {}
        public boolean isHeld() { return false; }
        public void release() {}
        public void setReferenceCounted(boolean p0) {}
    }
}
