// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class AdSelectionOutcome {
    public long getAdSelectionId() { return 0; }
    public android.net.Uri getRenderUri() { return null; }
}
