// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class AdSelectionFromOutcomesConfig {

    public static class Builder {
        public android.adservices.adselection.AdSelectionFromOutcomesConfig build() { return null; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setAdSelectionIds(java.util.List p0) { return null; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setSelectionLogicUri(android.net.Uri p0) { return null; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setSelectionSignals(android.adservices.common.AdSelectionSignals p0) { return null; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setSeller(android.adservices.common.AdTechIdentifier p0) { return null; }
    }
}
