// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class AdSelectionConfig {

    public static class Builder {
        public android.adservices.adselection.AdSelectionConfig build() { return null; }
        public android.adservices.adselection.AdSelectionConfig.Builder setAdSelectionSignals(android.adservices.common.AdSelectionSignals p0) { return null; }
        public android.adservices.adselection.AdSelectionConfig.Builder setCustomAudienceBuyers(java.util.List p0) { return null; }
        public android.adservices.adselection.AdSelectionConfig.Builder setDecisionLogicUri(android.net.Uri p0) { return null; }
        public android.adservices.adselection.AdSelectionConfig.Builder setPerBuyerSignals(java.util.Map p0) { return null; }
        public android.adservices.adselection.AdSelectionConfig.Builder setSeller(android.adservices.common.AdTechIdentifier p0) { return null; }
        public android.adservices.adselection.AdSelectionConfig.Builder setSellerSignals(android.adservices.common.AdSelectionSignals p0) { return null; }
        public android.adservices.adselection.AdSelectionConfig.Builder setTrustedScoringSignalsUri(android.net.Uri p0) { return null; }
    }
}
