// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class AdSelectionManager {
    public android.adservices.adselection.AdSelectionManager get(android.content.Context p0) { return null; }
    public void getAdSelectionData(android.adservices.adselection.GetAdSelectionDataRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void persistAdSelectionResult(android.adservices.adselection.PersistAdSelectionResultRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void reportEvent(android.adservices.adselection.ReportEventRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void reportImpression(android.adservices.adselection.ReportImpressionRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void selectAds(android.adservices.adselection.AdSelectionConfig p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void updateAdCounterHistogram(android.adservices.adselection.UpdateAdCounterHistogramRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
}
