// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class GetAdSelectionDataRequest {

    public static class Builder {
        public android.adservices.adselection.GetAdSelectionDataRequest build() { return null; }
        public android.adservices.adselection.GetAdSelectionDataRequest.Builder setCoordinatorOriginUri(android.net.Uri p0) { return null; }
        public android.adservices.adselection.GetAdSelectionDataRequest.Builder setSeller(android.adservices.common.AdTechIdentifier p0) { return null; }
    }
}
