// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class PersistAdSelectionResultRequest {

    public static class Builder {
        public android.adservices.adselection.PersistAdSelectionResultRequest build() { return null; }
        public android.adservices.adselection.PersistAdSelectionResultRequest.Builder setAdSelectionId(long p0) { return null; }
        public android.adservices.adselection.PersistAdSelectionResultRequest.Builder setAdSelectionResult(byte[] p0) { return null; }
        public android.adservices.adselection.PersistAdSelectionResultRequest.Builder setSeller(android.adservices.common.AdTechIdentifier p0) { return null; }
    }
}
