// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class ReportEventRequest {

    public static class Builder {
        public android.adservices.adselection.ReportEventRequest build() { return null; }
        public android.adservices.adselection.ReportEventRequest.Builder setInputEvent(android.view.InputEvent p0) { return null; }
    }
}
