// @generated by gen-shims.py — do not edit by hand
package android.adservices.adselection;

public class UpdateAdCounterHistogramRequest {

    public static class Builder {
        public android.adservices.adselection.UpdateAdCounterHistogramRequest build() { return null; }
    }
}
