// @generated by gen-shims.py — do not edit by hand
package android.content.res;

public class AssetFileDescriptor {
    public void close() {}
    public java.io.FileInputStream createInputStream() { return null; }
    public long getDeclaredLength() { return 0; }
    public java.io.FileDescriptor getFileDescriptor() { return null; }
    public long getLength() { return 0; }
    public android.os.ParcelFileDescriptor getParcelFileDescriptor() { return null; }
    public long getStartOffset() { return 0; }
}
