// @generated by gen-shims.py — do not edit by hand
package android.content.res;

public class Configuration {
    public int diff(android.content.res.Configuration p0) { return 0; }
    public boolean equals(android.content.res.Configuration p0) { return false; }
    public int getLayoutDirection() { return 0; }
    public android.os.LocaleList getLocales() { return null; }
    public int hashCode() { return 0; }
    public boolean isLayoutSizeAtLeast(int p0) { return false; }
    public boolean needNewResources(int p0, int p1) { return false; }
    public void setLayoutDirection(java.util.Locale p0) {}
    public void setLocale(java.util.Locale p0) {}
    public void setLocales(android.os.LocaleList p0) {}
    public void setTo(android.content.res.Configuration p0) {}
    public int updateFrom(android.content.res.Configuration p0) { return 0; }
}
