// @generated by gen-shims.py — do not edit by hand
package android.content.res;

public class TypedArray {
    public boolean getBoolean(int p0, boolean p1) { return false; }
    public int getChangingConfigurations() { return 0; }
    public int getColor(int p0, int p1) { return 0; }
    public android.content.res.ColorStateList getColorStateList(int p0) { return null; }
    public float getDimension(int p0, float p1) { return 0f; }
    public int getDimensionPixelOffset(int p0, int p1) { return 0; }
    public int getDimensionPixelSize(int p0, int p1) { return 0; }
    public android.graphics.drawable.Drawable getDrawable(int p0) { return null; }
    public float getFloat(int p0, float p1) { return 0f; }
    public android.graphics.Typeface getFont(int p0) { return null; }
    public float getFraction(int p0, int p1, int p2, float p3) { return 0f; }
    public int getIndex(int p0) { return 0; }
    public int getIndexCount() { return 0; }
    public int getInt(int p0, int p1) { return 0; }
    public int getInteger(int p0, int p1) { return 0; }
    public int getLayoutDimension(int p0, int p1) { return 0; }
    public java.lang.String getNonResourceString(int p0) { return null; }
    public java.lang.String getPositionDescription() { return null; }
    public int getResourceId(int p0, int p1) { return 0; }
    public android.content.res.Resources getResources() { return null; }
    public java.lang.String getString(int p0) { return null; }
    public java.lang.CharSequence getText(int p0) { return null; }
    public java.lang.CharSequence[] getTextArray(int p0) { return null; }
    public int getType(int p0) { return 0; }
    public boolean getValue(int p0, android.util.TypedValue p1) { return false; }
    public boolean hasValue(int p0) { return false; }
    public int length() { return 0; }
    public android.util.TypedValue peekValue(int p0) { return null; }
    public void recycle() {}
}
