// @generated by gen-shims.py — do not edit by hand
package android.content.res;

public class XmlResourceParser {
    public void close() {}
    public int getAttributeResourceValue(java.lang.String p0, java.lang.String p1, int p2) { return 0; }
    public java.lang.String getAttributeValue(java.lang.String p0, java.lang.String p1) { return null; }
    public int getDepth() { return 0; }
    public int getEventType() { return 0; }
    public java.lang.String getName() { return null; }
    public java.lang.String getPositionDescription() { return null; }
    public int next() { return 0; }
}
