// @generated by gen-shims.py — do not edit by hand
package android.graphics.drawable.shapes;

public class OvalShape {
    public void onResize(float p0, float p1) {}
    public android.graphics.RectF rect() { return null; }
}
