// @generated by gen-shims.py — do not edit by hand
package android.view.animation;

public class Animation {
    public void applyTransformation(float p0, android.view.animation.Transformation p1) {}
    public void cancel() {}
    public long getDuration() { return 0; }
    public boolean getTransformation(long p0, android.view.animation.Transformation p1, float p2) { return false; }
    public boolean hasEnded() { return false; }
    public boolean hasStarted() { return false; }
    public void initialize(int p0, int p1, int p2, int p3) {}
    public void reset() {}
    public void setAnimationListener(android.view.animation.Animation.AnimationListener p0) {}
    public void setDuration(long p0) {}
    public void setFillAfter(boolean p0) {}
    public void setInterpolator(android.view.animation.Interpolator p0) {}
    public void setRepeatCount(int p0) {}
    public void setRepeatMode(int p0) {}
    public void start() {}

    public interface AnimationListener {
        void onAnimationEnd(android.view.animation.Animation p0);
        void onAnimationRepeat(android.view.animation.Animation p0);
        void onAnimationStart(android.view.animation.Animation p0);
    }
}
