// @generated by gen-shims.py — do not edit by hand
package android.view.animation;

public class AnimationSet {
    public void addAnimation(android.view.animation.Animation p0) {}
    public java.util.List getAnimations() { return null; }
    public boolean getTransformation(long p0, android.view.animation.Transformation p1) { return false; }
    public boolean getTransformation(long p0, android.view.animation.Transformation p1, float p2) { return false; }
    public void setDuration(long p0) {}
    public void setFillAfter(boolean p0) {}
}
