// @generated by gen-shims.py — do not edit by hand
package android.view.animation;

public class LayoutAnimationController {
    public android.view.animation.Animation getAnimation() { return null; }
}
