// @generated by gen-shims.py — do not edit by hand
package android.view.animation;

public class ScaleAnimation {
    public void setDuration(long p0) {}
    public void setInterpolator(android.view.animation.Interpolator p0) {}
}
