// @generated by gen-shims.py — do not edit by hand
package android.graphics.text;

public class LineBreakConfig {

    public static class Builder {
        public android.graphics.text.LineBreakConfig build() { return null; }
        public android.graphics.text.LineBreakConfig.Builder setLineBreakStyle(int p0) { return null; }
        public android.graphics.text.LineBreakConfig.Builder setLineBreakWordStyle(int p0) { return null; }
    }
}
