// @generated by gen-shims.py — do not edit by hand
package android.graphics.text;

public class TextRunShaper {
    public android.graphics.text.PositionedGlyphs shapeTextRun(java.lang.CharSequence p0, int p1, int p2, int p3, int p4, float p5, float p6, boolean p7, android.graphics.Paint p8) { return null; }
}
