// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class AnimatorListenerAdapter {
    public void onAnimationCancel(android.animation.Animator p0) {}
    public void onAnimationEnd(android.animation.Animator p0) {}
    public void onAnimationRepeat(android.animation.Animator p0) {}
    public void onAnimationStart(android.animation.Animator p0) {}
}
