// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class ArgbEvaluator {
    public java.lang.Object evaluate(float p0, java.lang.Object p1, java.lang.Object p2) { return null; }
}
