// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class FloatEvaluator {
    public java.lang.Float evaluate(float p0, java.lang.Number p1, java.lang.Number p2) { return null; }
}
