// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class LayoutTransition {
    public void disableTransitionType(int p0) {}
    public void enableTransitionType(int p0) {}
    public android.animation.Animator getAnimator(int p0) { return null; }
    public boolean isChangingLayout() { return false; }
    public boolean isRunning() { return false; }
    public void setAnimateParentHierarchy(boolean p0) {}
    public void setAnimator(int p0, android.animation.Animator p1) {}
    public void setDuration(long p0) {}
}
