// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class ObjectAnimator {
    public void addListener(android.animation.Animator.AnimatorListener p0) {}
    public void addPauseListener(android.animation.Animator.AnimatorPauseListener p0) {}
    public void addUpdateListener(android.animation.ValueAnimator.AnimatorUpdateListener p0) {}
    public void cancel() {}
    public void end() {}
    public java.lang.Object getAnimatedValue() { return null; }
    public java.lang.String getPropertyName() { return null; }
    public android.animation.PropertyValuesHolder[] getValues() { return null; }
    public boolean isRunning() { return false; }
    public boolean isStarted() { return false; }
    public android.animation.ObjectAnimator ofArgb(java.lang.Object p0, java.lang.String p1, int[] p2) { return null; }
    public android.animation.ObjectAnimator ofFloat(java.lang.Object p0, android.util.Property p1, float[] p2) { return null; }
    public android.animation.ObjectAnimator ofFloat(java.lang.Object p0, android.util.Property p1, android.util.Property p2, android.graphics.Path p3) { return null; }
    public android.animation.ObjectAnimator ofInt(java.lang.Object p0, android.util.Property p1, int[] p2) { return null; }
    public android.animation.ObjectAnimator ofObject(java.lang.Object p0, android.util.Property p1, android.animation.TypeConverter p2, android.graphics.Path p3) { return null; }
    public android.animation.ObjectAnimator ofPropertyValuesHolder(java.lang.Object p0, android.animation.PropertyValuesHolder[] p1) { return null; }
    public void reverse() {}
    public void setAutoCancel(boolean p0) {}
    public void setCurrentPlayTime(long p0) {}
    public android.animation.ObjectAnimator setDuration(long p0) { return null; }
    public void setEvaluator(android.animation.TypeEvaluator p0) {}
    public void setFloatValues(float[] p0) {}
    public void setIntValues(int[] p0) {}
    public void setInterpolator(android.animation.TimeInterpolator p0) {}
    public void setProperty(android.util.Property p0) {}
    public void setPropertyName(java.lang.String p0) {}
    public void setRepeatCount(int p0) {}
    public void setRepeatMode(int p0) {}
    public void setStartDelay(long p0) {}
    public void setTarget(java.lang.Object p0) {}
    public void setValues(android.animation.PropertyValuesHolder[] p0) {}
    public void start() {}
}
