// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class PropertyValuesHolder {
    public android.animation.PropertyValuesHolder clone() { return null; }
    public android.animation.PropertyValuesHolder ofFloat(android.util.Property p0, float[] p1) { return null; }
    public android.animation.PropertyValuesHolder ofInt(java.lang.String p0, int[] p1) { return null; }
    public android.animation.PropertyValuesHolder ofKeyframe(java.lang.String p0, android.animation.Keyframe[] p1) { return null; }
    public android.animation.PropertyValuesHolder ofObject(android.util.Property p0, android.animation.TypeConverter p1, android.graphics.Path p2) { return null; }
    public void setEvaluator(android.animation.TypeEvaluator p0) {}
    public void setFloatValues(float[] p0) {}
}
