// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class StateListAnimator {
    public void addState(int[] p0, android.animation.Animator p1) {}
    public void jumpToCurrentState() {}
}
