// @generated by gen-shims.py — do not edit by hand
package android.animation;

public class TimeAnimator {
    public void end() {}
    public boolean isRunning() { return false; }
    public void setTimeListener(android.animation.TimeAnimator.TimeListener p0) {}
    public void start() {}

    public interface TimeListener {
    }
}
