// @generated by gen-shims.py — do not edit by hand
package android.service.dreams;

public class DreamService {
    public void onConfigurationChanged(android.content.res.Configuration p0) {}
    public void onDetachedFromWindow() {}
    public void onDreamingStarted() {}
    public void onDreamingStopped() {}
}
