// @generated by gen-shims.py — do not edit by hand
package android.content.res.loader;

public class ResourcesLoader {
    public void addProvider(android.content.res.loader.ResourcesProvider p0) {}
}
