// @generated by gen-shims.py — do not edit by hand
package android.content.res.loader;

public interface ResourcesProvider {
    android.content.res.loader.ResourcesProvider loadFromTable(android.os.ParcelFileDescriptor p0, android.content.res.loader.AssetsProvider p1);
}
