// @generated by gen-shims.py — do not edit by hand
package android.preference;

public class CheckBoxPreference {
    public void setChecked(boolean p0) {}
    public void setEnabled(boolean p0) {}
}
