// @generated by gen-shims.py — do not edit by hand
package android.preference;

public class DialogPreference {
    public boolean callChangeListener(java.lang.Object p0) { return false; }
    public android.content.Context getContext() { return null; }
    public java.lang.String getKey() { return null; }
    public int getPersistedInt(int p0) { return 0; }
    public java.lang.CharSequence getPositiveButtonText() { return null; }
    public android.content.SharedPreferences getSharedPreferences() { return null; }
    public java.lang.CharSequence getSummary() { return null; }
    public boolean isEnabled() { return false; }
    public void onBindView(android.view.View p0) {}
    public void onPrepareDialogBuilder(android.app.AlertDialog.Builder p0) {}
    public boolean persistInt(int p0) { return false; }
    public void setSummary(java.lang.CharSequence p0) {}
    public boolean shouldPersist() { return false; }
}
