// @generated by gen-shims.py — do not edit by hand
package android.preference;

public class EditTextPreference {
    public float getPersistedFloat(float p0) { return 0f; }
    public int getPersistedInt(int p0) { return 0; }
    public boolean persistFloat(float p0) { return false; }
    public boolean persistInt(int p0) { return false; }
}
