// @generated by gen-shims.py — do not edit by hand
package android.preference;

public class ListPreference {
    public java.lang.CharSequence[] getEntries() { return null; }
    public java.lang.CharSequence[] getEntryValues() { return null; }
    public java.lang.String getValue() { return null; }
    public void setOnPreferenceChangeListener(android.preference.Preference.OnPreferenceChangeListener p0) {}
    public void setSummary(java.lang.CharSequence p0) {}
}
