// @generated by gen-shims.py — do not edit by hand
package android.preference;

public class PreferenceManager {
    public android.content.SharedPreferences getDefaultSharedPreferences(android.content.Context p0) { return null; }
}
