// @generated by gen-shims.py — do not edit by hand
package android.preference;

public class PreferenceActivity {
    public void addPreferencesFromResource(int p0) {}
    public android.preference.Preference findPreference(java.lang.CharSequence p0) { return null; }
    public void finish() {}
    public void onConfigurationChanged(android.content.res.Configuration p0) {}
    public void onCreate(android.os.Bundle p0) {}
    public void onDestroy() {}
    public boolean onKeyDown(int p0, android.view.KeyEvent p1) { return false; }
    public void setRequestedOrientation(int p0) {}
    public void startActivity(android.content.Intent p0) {}
}
