// @generated by gen-shims.py — do not edit by hand
package android.preference;

public class Preference {
    public void onAttachedToActivity() {}
    public void onBindView(android.view.View p0) {}
    public void onClick() {}
    public void setOnPreferenceClickListener(android.preference.Preference.OnPreferenceClickListener p0) {}

    public interface OnPreferenceChangeListener {
    }

    public interface OnPreferenceClickListener {
    }
}
