// @generated by gen-shims.py — do not edit by hand
package android.content;

public interface AsyncQueryHandler {
    void cancelOperation(int p0);
    void startQuery(int p0, java.lang.Object p1, android.net.Uri p2, java.lang.String[] p3, java.lang.String p4, java.lang.String[] p5, java.lang.String p6);
}
