// @generated by gen-shims.py — do not edit by hand
package android.content;

public class AsyncTaskLoader {
    public boolean cancelLoad() { return false; }
    public void deliverResult(java.lang.Object p0) {}
    public void forceLoad() {}
    public boolean isReset() { return false; }
    public boolean isStarted() { return false; }
    public void onContentChanged() {}
    public void onReset() {}
    public boolean takeContentChanged() { return false; }
}
