// @generated by gen-shims.py — do not edit by hand
package android.content;

public class BroadcastReceiver {
    public android.content.BroadcastReceiver.PendingResult goAsync() { return null; }
    public boolean isInitialStickyBroadcast() { return false; }
    public boolean isOrderedBroadcast() { return false; }
    public void onReceive(android.content.Context p0, android.content.Intent p1) {}
    public void setResultCode(int p0) {}

    public static class PendingResult {
        public void finish() {}
        public void setResultCode(int p0) {}
    }
}
