// @generated by gen-shims.py — do not edit by hand
package android.content;

public class ClipData {
    public void addItem(android.content.ClipData.Item p0) {}
    public android.content.ClipDescription getDescription() { return null; }
    public android.content.ClipData.Item getItemAt(int p0) { return null; }
    public int getItemCount() { return 0; }
    public android.content.ClipData newIntent(java.lang.CharSequence p0, android.content.Intent p1) { return null; }
    public android.content.ClipData newPlainText(java.lang.CharSequence p0, java.lang.CharSequence p1) { return null; }
    public android.content.ClipData newRawUri(java.lang.CharSequence p0, android.net.Uri p1) { return null; }
    public android.content.ClipData newUri(android.content.ContentResolver p0, java.lang.CharSequence p1, android.net.Uri p2) { return null; }

    public static class Item {
        public java.lang.CharSequence coerceToStyledText(android.content.Context p0) { return null; }
        public java.lang.CharSequence coerceToText(android.content.Context p0) { return null; }
        public java.lang.String getHtmlText() { return null; }
        public android.content.Intent getIntent() { return null; }
        public java.lang.CharSequence getText() { return null; }
        public android.view.textclassifier.TextLinks getTextLinks() { return null; }
        public android.net.Uri getUri() { return null; }
    }
}
