// @generated by gen-shims.py — do not edit by hand
package android.content;

public class ClipDescription {
    public java.lang.CharSequence getLabel() { return null; }
    public java.lang.String getMimeType(int p0) { return null; }
    public int getMimeTypeCount() { return 0; }
    public boolean hasMimeType(java.lang.String p0) { return false; }
    public void setExtras(android.os.PersistableBundle p0) {}
}
