// @generated by gen-shims.py — do not edit by hand
package android.content;

public class ComponentName {
    public boolean equals(java.lang.Object p0) { return false; }
    public java.lang.String flattenToShortString() { return null; }
    public java.lang.String flattenToString() { return null; }
    public java.lang.String getClassName() { return null; }
    public java.lang.String getPackageName() { return null; }
    public java.lang.String getShortClassName() { return null; }
    public int hashCode() { return 0; }
    public java.lang.String toShortString() { return null; }
    public java.lang.String toString() { return null; }
    public android.content.ComponentName unflattenFromString(java.lang.String p0) { return null; }
}
