// @generated by gen-shims.py — do not edit by hand
package android.content;

public class ContentProviderOperation {
    public android.content.ContentProviderOperation.Builder newInsert(android.net.Uri p0) { return null; }

    public static class Builder {
        public android.content.ContentProviderOperation build() { return null; }
        public android.content.ContentProviderOperation.Builder withValue(java.lang.String p0, java.lang.Object p1) { return null; }
    }
}
