// @generated by gen-shims.py — do not edit by hand
package android.content;

public interface ContentResolver {
    android.content.ContentProviderClient acquireUnstableContentProviderClient(android.net.Uri p0);
    android.content.ContentProviderResult[] applyBatch(java.lang.String p0, java.util.ArrayList p1);
    android.os.Bundle call(android.net.Uri p0, java.lang.String p1, java.lang.String p2, android.os.Bundle p3);
    int delete(android.net.Uri p0, android.os.Bundle p1);
    int delete(android.net.Uri p0, java.lang.String p1, java.lang.String[] p2);
    int getIsSyncable(android.accounts.Account p0, java.lang.String p1);
    boolean getMasterSyncAutomatically();
    java.util.List getPersistedUriPermissions();
    java.lang.String getType(android.net.Uri p0);
    android.net.Uri insert(android.net.Uri p0, android.content.ContentValues p1);
    android.content.res.AssetFileDescriptor openAssetFileDescriptor(android.net.Uri p0, java.lang.String p1);
    android.os.ParcelFileDescriptor openFileDescriptor(android.net.Uri p0, java.lang.String p1, android.os.CancellationSignal p2);
    android.os.ParcelFileDescriptor openFileDescriptor(android.net.Uri p0, java.lang.String p1);
    java.io.InputStream openInputStream(android.net.Uri p0);
    java.io.OutputStream openOutputStream(android.net.Uri p0);
    java.io.OutputStream openOutputStream(android.net.Uri p0, java.lang.String p1);
    android.content.res.AssetFileDescriptor openTypedAssetFile(android.net.Uri p0, java.lang.String p1, android.os.Bundle p2, android.os.CancellationSignal p3);
    android.content.res.AssetFileDescriptor openTypedAssetFileDescriptor(android.net.Uri p0, java.lang.String p1, android.os.Bundle p2);
    android.database.Cursor query(android.net.Uri p0, java.lang.String[] p1, java.lang.String p2, java.lang.String[] p3, java.lang.String p4);
    android.database.Cursor query(android.net.Uri p0, java.lang.String[] p1, java.lang.String p2, java.lang.String[] p3, java.lang.String p4, android.os.CancellationSignal p5);
    android.database.Cursor query(android.net.Uri p0, java.lang.String[] p1, android.os.Bundle p2, android.os.CancellationSignal p3);
    void registerContentObserver(android.net.Uri p0, boolean p1, android.database.ContentObserver p2);
    void releasePersistableUriPermission(android.net.Uri p0, int p1);
    void takePersistableUriPermission(android.net.Uri p0, int p1);
    void unregisterContentObserver(android.database.ContentObserver p0);
    int update(android.net.Uri p0, android.content.ContentValues p1, java.lang.String p2, java.lang.String[] p3);
}
