// @generated by gen-shims.py — do not edit by hand
package android.content;

public class ContentValues {
    public void clear() {}
    public boolean containsKey(java.lang.String p0) { return false; }
    public boolean equals(java.lang.Object p0) { return false; }
    public java.lang.Object get(java.lang.String p0) { return null; }
    public byte[] getAsByteArray(java.lang.String p0) { return null; }
    public java.lang.Integer getAsInteger(java.lang.String p0) { return null; }
    public java.lang.Long getAsLong(java.lang.String p0) { return null; }
    public java.lang.String getAsString(java.lang.String p0) { return null; }
    public int hashCode() { return 0; }
    public java.util.Set keySet() { return null; }
    public void put(java.lang.String p0, java.lang.Integer p1) {}
    public void putNull(java.lang.String p0) {}
    public void remove(java.lang.String p0) {}
    public int size() { return 0; }
    public java.lang.String toString() { return null; }
    public java.util.Set valueSet() { return null; }
}
