// @generated by gen-shims.py — do not edit by hand
package android.content;

public class ContextWrapper {
    public void attachBaseContext(android.content.Context p0) {}
    public android.content.Context createConfigurationContext(android.content.res.Configuration p0) { return null; }
    public android.content.Context createDisplayContext(android.view.Display p0) { return null; }
    public android.content.Context createPackageContext(java.lang.String p0, int p1) { return null; }
    public android.content.pm.ApplicationInfo getApplicationInfo() { return null; }
    public android.content.Context getBaseContext() { return null; }
    public java.io.File getCacheDir() { return null; }
    public java.io.File getDatabasePath(java.lang.String p0) { return null; }
    public android.view.Display getDisplay() { return null; }
    public java.io.File getExternalCacheDir() { return null; }
    public java.io.File getExternalFilesDir(java.lang.String p0) { return null; }
    public java.io.File getFilesDir() { return null; }
    public java.io.File getNoBackupFilesDir() { return null; }
    public android.content.pm.PackageManager getPackageManager() { return null; }
    public java.lang.String getPackageName() { return null; }
    public java.lang.String getPackageResourcePath() { return null; }
    public android.content.res.Resources getResources() { return null; }
    public java.lang.Object getSystemService(java.lang.String p0) { return null; }
    public android.content.res.Resources.Theme getTheme() { return null; }
    public void setTheme(int p0) {}
    public void startActivity(android.content.Intent p0) {}
}
