// @generated by gen-shims.py — do not edit by hand
package android.content;

public class DialogInterface {
    public void cancel() {}
    public void dismiss() {}

    public interface OnCancelListener {
        void onCancel(android.content.DialogInterface p0);
    }

    public interface OnClickListener {
        void onClick(android.content.DialogInterface p0, int p1);
    }

    public interface OnDismissListener {
        void onDismiss(android.content.DialogInterface p0);
    }

    public interface OnKeyListener {
        boolean onKey(android.content.DialogInterface p0, int p1, android.view.KeyEvent p2);
    }

    public interface OnMultiChoiceClickListener {
        void onClick(android.content.DialogInterface p0, int p1, boolean p2);
    }

    public interface OnShowListener {
    }
}
