// @generated by gen-shims.py — do not edit by hand
package android.content;

public class IntentSender {
    public void sendIntent(android.content.Context p0, int p1, android.content.Intent p2, android.content.IntentSender.OnFinished p3, android.os.Handler p4) {}

    public static class OnFinished {
    }

    public static class SendIntentException {
    }
}
