// @generated by gen-shims.py — do not edit by hand
package android.content;

public class IntentFilter {
    public void addAction(java.lang.String p0) {}
    public void addDataAuthority(java.lang.String p0, java.lang.String p1) {}
    public void addDataPath(java.lang.String p0, int p1) {}
    public void addDataScheme(java.lang.String p0) {}
    public java.util.Iterator authoritiesIterator() { return null; }
    public int countActions() { return 0; }
    public int countDataAuthorities() { return 0; }
    public int countDataPaths() { return 0; }
    public java.lang.String getAction(int p0) { return null; }
    public boolean hasAction(java.lang.String p0) { return false; }
    public boolean hasCategory(java.lang.String p0) { return false; }
    public int match(java.lang.String p0, java.lang.String p1, java.lang.String p2, android.net.Uri p3, java.util.Set p4, java.lang.String p5) { return 0; }
    public java.util.Iterator schemesIterator() { return null; }
    public void setPriority(int p0) {}
}
