// @generated by gen-shims.py — do not edit by hand
package android.content;

public interface ServiceConnection {
    void onServiceConnected(android.content.ComponentName p0, android.os.IBinder p1);
    void onServiceDisconnected(android.content.ComponentName p0);
}
