// @generated by gen-shims.py — do not edit by hand
package android.content;

public class SharedPreferences {
    public boolean contains(java.lang.String p0) { return false; }
    public android.content.SharedPreferences.Editor edit() { return null; }
    public java.util.Map getAll() { return null; }
    public boolean getBoolean(java.lang.String p0, boolean p1) { return false; }
    public float getFloat(java.lang.String p0, float p1) { return 0f; }
    public int getInt(java.lang.String p0, int p1) { return 0; }
    public long getLong(java.lang.String p0, long p1) { return 0; }
    public java.lang.String getString(java.lang.String p0, java.lang.String p1) { return null; }
    public java.util.Set getStringSet(java.lang.String p0, java.util.Set p1) { return null; }
    public void registerOnSharedPreferenceChangeListener(android.content.SharedPreferences.OnSharedPreferenceChangeListener p0) {}
    public void unregisterOnSharedPreferenceChangeListener(android.content.SharedPreferences.OnSharedPreferenceChangeListener p0) {}

    public static class Editor {
        public void apply() {}
        public android.content.SharedPreferences.Editor clear() { return null; }
        public boolean commit() { return false; }
        public android.content.SharedPreferences.Editor putBoolean(java.lang.String p0, boolean p1) { return null; }
        public android.content.SharedPreferences.Editor putFloat(java.lang.String p0, float p1) { return null; }
        public android.content.SharedPreferences.Editor putInt(java.lang.String p0, int p1) { return null; }
        public android.content.SharedPreferences.Editor putLong(java.lang.String p0, long p1) { return null; }
        public android.content.SharedPreferences.Editor putString(java.lang.String p0, java.lang.String p1) { return null; }
        public android.content.SharedPreferences.Editor putStringSet(java.lang.String p0, java.util.Set p1) { return null; }
        public android.content.SharedPreferences.Editor remove(java.lang.String p0) { return null; }
    }

    public interface OnSharedPreferenceChangeListener {
        void onSharedPreferenceChanged(android.content.SharedPreferences p0, java.lang.String p1);
    }
}
