// @generated by gen-shims.py — do not edit by hand
package android.content;

public class UriMatcher {
    public void addURI(java.lang.String p0, java.lang.String p1, int p2) {}
    public int match(android.net.Uri p0) { return 0; }
}
