// @generated by gen-shims.py — do not edit by hand
package android.content;

public class UriPermission {
    public android.net.Uri getUri() { return null; }
    public boolean isReadPermission() { return false; }
    public boolean isWritePermission() { return false; }
}
