// @generated by gen-shims.py — do not edit by hand
package android.media.metrics;

public class MediaMetricsManager {
    public android.media.metrics.PlaybackSession createPlaybackSession() { return null; }
}
