// @generated by gen-shims.py — do not edit by hand
package android.media.metrics;

public class NetworkEvent {

    public static class Builder {
        public android.media.metrics.NetworkEvent build() { return null; }
        public android.media.metrics.NetworkEvent.Builder setNetworkType(int p0) { return null; }
        public android.media.metrics.NetworkEvent.Builder setTimeSinceCreatedMillis(long p0) { return null; }
    }
}
