// @generated by gen-shims.py — do not edit by hand
package android.media.metrics;

public class PlaybackSession {
    public android.media.metrics.LogSessionId getSessionId() { return null; }
    public void reportNetworkEvent(android.media.metrics.NetworkEvent p0) {}
    public void reportPlaybackErrorEvent(android.media.metrics.PlaybackErrorEvent p0) {}
    public void reportPlaybackMetrics(android.media.metrics.PlaybackMetrics p0) {}
    public void reportPlaybackStateEvent(android.media.metrics.PlaybackStateEvent p0) {}
    public void reportTrackChangeEvent(android.media.metrics.TrackChangeEvent p0) {}
}
