// @generated by gen-shims.py — do not edit by hand
package android.media.metrics;

public class PlaybackStateEvent {

    public static class Builder {
        public android.media.metrics.PlaybackStateEvent build() { return null; }
        public android.media.metrics.PlaybackStateEvent.Builder setState(int p0) { return null; }
        public android.media.metrics.PlaybackStateEvent.Builder setTimeSinceCreatedMillis(long p0) { return null; }
    }
}
