// @generated by gen-shims.py — do not edit by hand
package android.media.metrics;

public class PlaybackErrorEvent {

    public static class Builder {
        public android.media.metrics.PlaybackErrorEvent build() { return null; }
        public android.media.metrics.PlaybackErrorEvent.Builder setErrorCode(int p0) { return null; }
        public android.media.metrics.PlaybackErrorEvent.Builder setException(java.lang.Exception p0) { return null; }
        public android.media.metrics.PlaybackErrorEvent.Builder setSubErrorCode(int p0) { return null; }
        public android.media.metrics.PlaybackErrorEvent.Builder setTimeSinceCreatedMillis(long p0) { return null; }
    }
}
