// @generated by gen-shims.py — do not edit by hand
package android.media.metrics;

public class TrackChangeEvent {

    public static class Builder {
        public android.media.metrics.TrackChangeEvent build() { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setAudioSampleRate(int p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setBitrate(int p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setChannelCount(int p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setCodecName(java.lang.String p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setContainerMimeType(java.lang.String p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setHeight(int p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setLanguage(java.lang.String p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setLanguageRegion(java.lang.String p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setSampleMimeType(java.lang.String p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setTimeSinceCreatedMillis(long p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setTrackChangeReason(int p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setTrackState(int p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setVideoFrameRate(float p0) { return null; }
        public android.media.metrics.TrackChangeEvent.Builder setWidth(int p0) { return null; }
    }
}
