// @generated by gen-shims.py — do not edit by hand
package android.service.quicksettings;

public class TileService {
    public android.service.quicksettings.Tile getQsTile() { return null; }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onClick() {}
    public void onStartListening() {}
    public void onTileAdded() {}
    public void requestListeningState(android.content.Context p0, android.content.ComponentName p1) {}
    public void startActivityAndCollapse(android.app.PendingIntent p0) {}
}
