// @generated by gen-shims.py — do not edit by hand
package android.adservices.topics;

public class EncryptedTopic {
    public byte[] getEncapsulatedKey() { return null; }
    public byte[] getEncryptedTopic() { return null; }
    public java.lang.String getKeyIdentifier() { return null; }
}
