// @generated by gen-shims.py — do not edit by hand
package android.adservices.topics;

public class GetTopicsResponse {
    public java.util.List getEncryptedTopics() { return null; }
    public java.util.List getTopics() { return null; }
}
