// @generated by gen-shims.py — do not edit by hand
package android.adservices.topics;

public class GetTopicsRequest {

    public static class Builder {
        public android.adservices.topics.GetTopicsRequest build() { return null; }
        public android.adservices.topics.GetTopicsRequest.Builder setAdsSdkName(java.lang.String p0) { return null; }
        public android.adservices.topics.GetTopicsRequest.Builder setShouldRecordObservation(boolean p0) { return null; }
    }
}
