// @generated by gen-shims.py — do not edit by hand
package android.adservices.topics;

public class Topic {
    public long getModelVersion() { return 0; }
    public long getTaxonomyVersion() { return 0; }
    public int getTopicId() { return 0; }
}
