// @generated by gen-shims.py — do not edit by hand
package android.media.session;

public class MediaSession {
    public android.media.session.MediaController getController() { return null; }
    public android.media.session.MediaSessionManager.RemoteUserInfo getCurrentControllerInfo() { return null; }
    public android.media.session.MediaSession.Token getSessionToken() { return null; }
    public boolean isActive() { return false; }
    public void release() {}
    public void sendSessionEvent(java.lang.String p0, android.os.Bundle p1) {}
    public void setActive(boolean p0) {}
    public void setCallback(android.media.session.MediaSession.Callback p0, android.os.Handler p1) {}
    public void setCallback(android.media.session.MediaSession.Callback p0) {}
    public void setExtras(android.os.Bundle p0) {}
    public void setFlags(int p0) {}
    public void setMediaButtonReceiver(android.app.PendingIntent p0) {}
    public void setMetadata(android.media.MediaMetadata p0) {}
    public void setPlaybackState(android.media.session.PlaybackState p0) {}
    public void setPlaybackToLocal(android.media.AudioAttributes p0) {}
    public void setPlaybackToRemote(android.media.VolumeProvider p0) {}
    public void setQueue(java.util.List p0) {}
    public void setQueueTitle(java.lang.CharSequence p0) {}
    public void setRatingType(int p0) {}
    public void setSessionActivity(android.app.PendingIntent p0) {}

    public interface Callback {
        boolean onMediaButtonEvent(android.content.Intent p0);
    }

    public static class QueueItem {
        public android.media.MediaDescription getDescription() { return null; }
        public long getQueueId() { return 0; }
    }

    public static class Token {
    }
}
