// @generated by gen-shims.py — do not edit by hand
package android.media.session;

public class MediaSessionManager {

    public static class RemoteUserInfo {
        public java.lang.String getPackageName() { return null; }
        public int getPid() { return 0; }
        public int getUid() { return 0; }
    }
}
