// @generated by gen-shims.py — do not edit by hand
package android.media.session;

public class PlaybackState {
    public long getActions() { return 0; }
    public long getActiveQueueItemId() { return 0; }
    public long getBufferedPosition() { return 0; }
    public java.util.List getCustomActions() { return null; }
    public java.lang.CharSequence getErrorMessage() { return null; }
    public android.os.Bundle getExtras() { return null; }
    public long getLastPositionUpdateTime() { return 0; }
    public float getPlaybackSpeed() { return 0f; }
    public long getPosition() { return 0; }
    public int getState() { return 0; }

    public static class Builder {
        public android.media.session.PlaybackState.CustomAction build() { return null; }
        public Object setExtras(android.os.Bundle p0) { return null; }
    }

    public static class CustomAction {
        public java.lang.String getAction() { return null; }
        public android.os.Bundle getExtras() { return null; }
        public int getIcon() { return 0; }
        public java.lang.CharSequence getName() { return null; }
    }
}
