// @generated by gen-shims.py — do not edit by hand
package android.bluetooth;

public class BluetoothAdapter {
    public boolean cancelDiscovery() { return false; }
    public boolean disable() { return false; }
    public boolean enable() { return false; }
    public java.util.Set getBondedDevices() { return null; }
    public android.bluetooth.BluetoothAdapter getDefaultAdapter() { return null; }
    public java.lang.String getName() { return null; }
    public int getProfileConnectionState(int p0) { return 0; }
    public android.bluetooth.BluetoothDevice getRemoteDevice(java.lang.String p0) { return null; }
    public int getScanMode() { return 0; }
    public boolean isEnabled() { return false; }
    public android.bluetooth.BluetoothServerSocket listenUsingInsecureRfcommWithServiceRecord(java.lang.String p0, java.util.UUID p1) { return null; }
    public boolean setName(java.lang.String p0) { return false; }
    public boolean startDiscovery() { return false; }
}
