// @generated by gen-shims.py — do not edit by hand
package android.bluetooth;

public class BluetoothServerSocket {
    public android.bluetooth.BluetoothSocket accept() { return null; }
    public void close() {}
}
