// @generated by gen-shims.py — do not edit by hand
package android.bluetooth;

public class BluetoothDevice {
    public android.bluetooth.BluetoothSocket createInsecureRfcommSocketToServiceRecord(java.util.UUID p0) { return null; }
    public java.lang.String getAddress() { return null; }
    public android.bluetooth.BluetoothClass getBluetoothClass() { return null; }
    public java.lang.String getName() { return null; }
}
