// @generated by gen-shims.py — do not edit by hand
package android.bluetooth;

public class BluetoothSocket {
    public void close() {}
    public void connect() {}
    public java.io.InputStream getInputStream() { return null; }
    public java.io.OutputStream getOutputStream() { return null; }
    public android.bluetooth.BluetoothDevice getRemoteDevice() { return null; }
    public boolean isConnected() { return false; }
}
