// @generated by gen-shims.py — do not edit by hand
package android.location;

public class Criteria {
    public void setAccuracy(int p0) {}
    public void setCostAllowed(boolean p0) {}
    public void setPowerRequirement(int p0) {}
}
