// @generated by gen-shims.py — do not edit by hand
package android.location;

public class Geocoder {
    public java.util.List getFromLocation(double p0, double p1, int p2) { return null; }
    public boolean isPresent() { return false; }
}
