// @generated by gen-shims.py — do not edit by hand
package android.location;

public class GnssMeasurementsEvent {

    public interface Callback {
        void onGnssMeasurementsReceived(android.location.GnssMeasurementsEvent p0);
        void onStatusChanged(int p0);
    }
}
