// @generated by gen-shims.py — do not edit by hand
package android.location;

public class GpsStatus {
    public java.lang.Iterable getSatellites() { return null; }
    public int getTimeToFirstFix() { return 0; }

    public interface Listener {
    }
}
