// @generated by gen-shims.py — do not edit by hand
package android.location;

public class GpsSatellite {
    public float getAzimuth() { return 0f; }
    public float getElevation() { return 0f; }
    public int getPrn() { return 0; }
    public float getSnr() { return 0f; }
    public boolean hasAlmanac() { return false; }
    public boolean hasEphemeris() { return false; }
    public boolean usedInFix() { return false; }
}
