// @generated by gen-shims.py — do not edit by hand
package android.location;

public class LocationManager {
    public boolean addGpsStatusListener(android.location.GpsStatus.Listener p0) { return false; }
    public java.util.List getAllProviders() { return null; }
    public java.lang.String getBestProvider(android.location.Criteria p0, boolean p1) { return null; }
    public void getCurrentLocation(java.lang.String p0, android.os.CancellationSignal p1, java.util.concurrent.Executor p2, java.util.function.Consumer p3) {}
    public java.lang.String getGnssHardwareModelName() { return null; }
    public int getGnssYearOfHardware() { return 0; }
    public android.location.GpsStatus getGpsStatus(android.location.GpsStatus p0) { return null; }
    public android.location.Location getLastKnownLocation(java.lang.String p0) { return null; }
    public android.location.LocationProvider getProvider(java.lang.String p0) { return null; }
    public java.util.List getProviders(boolean p0) { return null; }
    public boolean hasProvider(java.lang.String p0) { return false; }
    public boolean isLocationEnabled() { return false; }
    public boolean isProviderEnabled(java.lang.String p0) { return false; }
    public boolean registerGnssMeasurementsCallback(android.location.GnssMeasurementsEvent.Callback p0, android.os.Handler p1) { return false; }
    public boolean registerGnssMeasurementsCallback(android.location.GnssMeasurementsEvent.Callback p0) { return false; }
    public boolean registerGnssStatusCallback(android.location.GnssStatus.Callback p0, android.os.Handler p1) { return false; }
    public void removeGpsStatusListener(android.location.GpsStatus.Listener p0) {}
    public void removeUpdates(android.location.LocationListener p0) {}
    public void requestLocationUpdates(java.lang.String p0, long p1, float p2, android.location.LocationListener p3, android.os.Looper p4) {}
    public void requestLocationUpdates(java.lang.String p0, android.location.LocationRequest p1, java.util.concurrent.Executor p2, android.location.LocationListener p3) {}
    public boolean sendExtraCommand(java.lang.String p0, java.lang.String p1, android.os.Bundle p2) { return false; }
    public void unregisterGnssMeasurementsCallback(android.location.GnssMeasurementsEvent.Callback p0) {}
    public void unregisterGnssStatusCallback(android.location.GnssStatus.Callback p0) {}
}
