// @generated by gen-shims.py — do not edit by hand
package android.location;

public class LocationRequest {

    public static class Builder {
        public android.location.LocationRequest build() { return null; }
        public android.location.LocationRequest.Builder setDurationMillis(long p0) { return null; }
        public android.location.LocationRequest.Builder setMaxUpdateDelayMillis(long p0) { return null; }
        public android.location.LocationRequest.Builder setMaxUpdates(int p0) { return null; }
        public android.location.LocationRequest.Builder setMinUpdateDistanceMeters(float p0) { return null; }
        public android.location.LocationRequest.Builder setMinUpdateIntervalMillis(long p0) { return null; }
        public android.location.LocationRequest.Builder setQuality(int p0) { return null; }
    }
}
