// @generated by gen-shims.py — do not edit by hand
package android.print;

public class PrintDocumentAdapter {
    public void onFinish() {}

    public interface LayoutResultCallback {
        void onLayoutCancelled();
        void onLayoutFailed(java.lang.CharSequence p0);
        void onLayoutFinished(android.print.PrintDocumentInfo p0, boolean p1);
    }

    public interface WriteResultCallback {
        void onWriteCancelled();
        void onWriteFailed(java.lang.CharSequence p0);
        void onWriteFinished(android.print.PageRange[] p0);
    }
}
