// @generated by gen-shims.py — do not edit by hand
package android.print;

public class PrintManager {
    public android.print.PrintJob print(java.lang.String p0, android.print.PrintDocumentAdapter p1, android.print.PrintAttributes p2) { return null; }
}
