// @generated by gen-shims.py — do not edit by hand
package android.adservices.measurement;

public class DeletionRequest {

    public static class Builder {
        public android.adservices.measurement.DeletionRequest build() { return null; }
        public android.adservices.measurement.DeletionRequest.Builder setDeletionMode(int p0) { return null; }
        public android.adservices.measurement.DeletionRequest.Builder setDomainUris(java.util.List p0) { return null; }
        public android.adservices.measurement.DeletionRequest.Builder setEnd(java.time.Instant p0) { return null; }
        public android.adservices.measurement.DeletionRequest.Builder setMatchBehavior(int p0) { return null; }
        public android.adservices.measurement.DeletionRequest.Builder setOriginUris(java.util.List p0) { return null; }
        public android.adservices.measurement.DeletionRequest.Builder setStart(java.time.Instant p0) { return null; }
    }
}
