// @generated by gen-shims.py — do not edit by hand
package android.adservices.measurement;

public class MeasurementManager {
    public void deleteRegistrations(android.adservices.measurement.DeletionRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public android.adservices.measurement.MeasurementManager get(android.content.Context p0) { return null; }
    public void getMeasurementApiStatus(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public void registerSource(android.net.Uri p0, android.view.InputEvent p1, java.util.concurrent.Executor p2, android.os.OutcomeReceiver p3) {}
    public void registerTrigger(android.net.Uri p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void registerWebSource(android.adservices.measurement.WebSourceRegistrationRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void registerWebTrigger(android.adservices.measurement.WebTriggerRegistrationRequest p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
}
