// @generated by gen-shims.py — do not edit by hand
package android.adservices.measurement;

public class WebSourceParams {

    public static class Builder {
        public android.adservices.measurement.WebSourceParams build() { return null; }
        public android.adservices.measurement.WebSourceParams.Builder setDebugKeyAllowed(boolean p0) { return null; }
    }
}
