// @generated by gen-shims.py — do not edit by hand
package android.adservices.measurement;

public class WebSourceRegistrationRequest {

    public static class Builder {
        public android.adservices.measurement.WebSourceRegistrationRequest build() { return null; }
        public android.adservices.measurement.WebSourceRegistrationRequest.Builder setAppDestination(android.net.Uri p0) { return null; }
        public android.adservices.measurement.WebSourceRegistrationRequest.Builder setInputEvent(android.view.InputEvent p0) { return null; }
        public android.adservices.measurement.WebSourceRegistrationRequest.Builder setVerifiedDestination(android.net.Uri p0) { return null; }
        public android.adservices.measurement.WebSourceRegistrationRequest.Builder setWebDestination(android.net.Uri p0) { return null; }
    }
}
