// @generated by gen-shims.py — do not edit by hand
package android.adservices.measurement;

public class WebTriggerRegistrationRequest {

    public static class Builder {
        public android.adservices.measurement.WebTriggerRegistrationRequest build() { return null; }
    }
}
