// @generated by gen-shims.py — do not edit by hand
package android.adservices.measurement;

public class WebTriggerParams {

    public static class Builder {
        public android.adservices.measurement.WebTriggerParams build() { return null; }
        public android.adservices.measurement.WebTriggerParams.Builder setDebugKeyAllowed(boolean p0) { return null; }
    }
}
